### ISSUE TITLE
Vehicle mispositioned on respawn or not respawned at all

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#1]
http://trac.sa-mp.nl/lvp/ticket/1525

cake:

> I used to have this issue all the time, but now that I tried this at my local test server, it's suddenly all OK.. Needs some more testing.

cake:

> Tested again; this problem still occurs. It has to do with the following:
> - when a vehicle is created by a player (with /v create), the game registers the vehicle's position and rotation
> - then, the player moves the vehicle to a certain spot, and saves it (/v save). we store the vehicle's position and rotation, but the game still has the old figures in mind. the game only remembers the position the vehicle was created in.
> - no big deal, we will just set the vehicle's correct position and rotation upon each respawn. however, we set the rotation with: ​http://wiki.sa-mp.com/wiki/GetVehicleZAngle.
> - bug reports on the internet show this function only works when a player is streamed in.
> 
> We can fix this two ways:
> - recreate vehicle upon save
> - set rotation upon player stream in
> 
> I've opted for the last one: ​http://trac.sa-mp.nl/lvp/changeset/5080/LVP since this was an easy fix and the code needs lot of changes to make the first happen. Time for more testing.

cake:

> ​http://trac.sa-mp.nl/lvp/changeset/5085/LVP
> Gonna implement the other solution I had in mind later. This hack won't cut it.

Granny:

> To add, I believe this has introduced a new issue. Myself and other players have noticed trailers become detached and it appears to have started since this change was made. Sometimes I'm just driving in a straight line with a trailer attached to my vehicle, and it detaches. They may not be linked, but I figured I would add this here.

**Comment by ghost** [comment]
I've not seen this issue for quite some time. Tested numerous times with saving vehicles to the DB, and the alignment is fine in new sessions, upon restarts, etc. Going to close this out for now, will re-open if I spot the problem again.

**Comment by xhoogland** [comment]
Unfortunately this issue is still present.
Driving with trailers is impossible and sometimes a vehicle after just stepping out of it gets repositioned... :s

I hope I can take some good look into it soon!

**Comment by ghost** [comment]
> Driving with trailers is impossible

@Xanland - Xilent and I just spent the past few minutes driving around with our own trucks and trailers, and I'm very pleased to say, not once did they disconnect. It looks like the fix has been successful!

As for the (mis)positioning, whilst I haven't spent much time ingame since the update was pushed live yesterday evening, I've not seen this happen thus far.

**Comment by xhoogland** [comment]
https://github.com/LVPlayground/playground/commit/e32764c3b29630a2a015d6e212a34cb39bdbe997

**Comment by RussellLVP** [comment]
This should be fixed when we move to the new vehicle streamer. Closing.
