### ISSUE TITLE
LVP Houses? Creation help.

### ISSUE THREAD

**Issue by GodeyLVP** [LVPlayground/playground#100]
Hello everyone. I have a few questions regarding the making of LVP Houses.

[1] How do you want it to be? same as the buisness properties?
[2] Do you want it to get saved even after the player quits? or just house lost?
[3] Price Ranges?
[4] Some Locations where houses are to be with interiors (HELPFUL)
[5] VIP's Get to keep vehicles? (LATER)
[6] Some Interiors suggestions?

Thank you, please help.

-Godey

**Comment by mblokker** [comment]
Hey Godey, let's handle your points one-by-one.
1. I think it would be nice to have markers positioned at the doors of several houses throughout Las Venturas, which would teleport you inside the house itself. If that's too much to ask for now, something like business properties will do too.
2. The most fun thing is to have your house even after disconnecting. Maybe have the house and car locked to your own account, so nobody can use it, even when you are not ingame. However, for the initial release of the House system we could go for temporary houses which are lost upon disconnection, and then improve it to save them in between session.
3. This is a tough one. Do we want people to simply buy the house? Or must they earn it some other way? Maybe something equal to spraying tags and unlocking a car: finding hidden packages and unlocking a house, which will then cost 1 bil?
4. We could let players pick their own location, or havea designated street where are houses are located.
5. I think it would be fun for everyone to have their own vehicle. However, we should look into additional features for VIP.
6. I really don't have any ideas for this. Maybe something like the interior of Johnson's House @ Groove Street?

Maybe this can help you to start. Along the way most of these points will come together.

**Comment by GodeyLVP** [comment]
Hello,
Thanks for replying, i now got the ideas for making the houses.

Can i use different type of pawn for this?
It's real easy and won't take lot of time for me.
I assure you there won't be bugs.
If there are, I'll be there to fix them :)

I'm telling this since i'm not a developer and don't have access to ingame property edittor.
Thank you.

-Godey

**Comment by mblokker** [comment]
What do you mean, different?

It's all OK. I will check everything you code, and make sure it can integrate with our code. It would be nice if you test everything before you apply it.

**Comment by GodeyLVP** [comment]
Can you make a new folder? Like /Entities/Houses/?
And i'm InGame call me as soon as you reply :)
Thanks.

-Godey

**Comment by mblokker** [comment]
We'll do that when something is ready to be added. You don't have to worry about anything, just code something and submit it as a pull request so we can review it.

**Comment by GodeyLVP** [comment]
Ok Thanks for your help :)

**Comment by GodeyLVP** [comment]
Hey there, 

Can i give a filterscript?
It's ok, right?
I don't think it can be merged with the other codes, so let it be a fs?

Sorry, i was unavailable last night.

-Godey

**Comment by ghost** [comment]
POST removed

**Comment by ghost** [comment]
how is this

**Comment by mblokker** [comment]
Hi Hopper, did you make this yourself?

**Comment by ghost** [comment]
nope I got it for samp forum !! btw i want some thing like this 

and when we goto House then it will ask a Pass :+1: 

i <3 this house system

**Comment by mblokker** [comment]
The main problem here is that you are not referring to your source at all, simply copy-pasting whatever work they have made as yours. You're even bold enough to slam our license header on it, like this piece of code was developed by us. That's not how we do things around here.

The proper thing for you to do now would be to delete your posts, and try it again. Make a comment where you refer to the link of this code, telling us why we should use it, and what could be improved. Thanks.

**Comment by Xanland** [comment]
As drgp wonderfully said in a previous pull request of him:
> No you have not created it: http://forum.sa-mp.com/showthread.php?t=464523

**Comment by ghost** [comment]
until i know Godey is also Sandra House / Properties system !!

**Comment by GodeyLVP** [comment]
*\* NO LONGER USE THAT CODE **

I've started a new Filterscript (Long back)
There are some available bugs, But i'm on fixing it.
As soon as completed. I will submit you it.

-Godey

**Comment by RussellLVP** [comment]
We now have a house system. Closing.
