### ISSUE TITLE
Allow undercover admins to be ignored

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#104]
Players cannot /ignore undercover admins, which, to the more familiar LVP players who have 50 hours/regular membership, is an easy way to identify an undercover admin. This should be changed so that undercover admins can be ignored.

**Comment by HopperLVP** [comment]
Granny , they Identify admins through There ping  expamle :

Ricky - 500 - 1000
Granny - 60
XIilent- 30
Mr.JT-25

And Through there behaviour !!
