### ISSUE TITLE
/fix gives a player a (random) weapon

### ISSUE THREAD

**Issue by Holsje** [LVPlayground/playground#105]
As title say, when a player gets fixed (or sfixed) he/she will get (random) weapons.

Not sure how random the weapons are or what causes it, but I noticed myself getting sniper and m4 out of nothing (Used an unregistered account to test) (I remember a while ago there was something that would give you a minigun from a fix a like this video: https://www.youtube.com/watch?v=OJOsLLocJr4 )

**Comment by GodeyLVP** [comment]
Can we take a look at the code?

-Godey

**Comment by jadegraaf** [comment]
The LVP gamemode is open source! The easiest way to contribute is to install the [github desktop client](https://desktop.github.com) and press the button on the left of "download ZIP" from [this page](https://github.com/LVPlayground/playground)
