### ISSUE TITLE
Increase vehicle respawn delay

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#106]
Let's say a crew member uses **/v create [id/model]**. That vehicle will automatically respawn after 2 minutes, if there's no driver. I'd like to propose increasing this limit to 5 minutes.

The reason I bring this up is there's often times where admins are organizing events such as cruises, or doing weird and whacky stuff, like [here](https://forum.sa-mp.nl/showthread.php?tid=16033&pid=464342#pid464342), for example - and that 2 minutes seems awfully viscous. It's annoying when vehicles are respawned so quickly.

**Comment by GodeyLVP** [comment]
No Big deal, 
Change them to
`CreateVehicle(VehID, PosX, PosY, PosZ, PosAngle,  Col1, Col2, 300);`

**Comment by jadegraaf** [comment]
@GodeyLVP have you looked at the source and how our vehicle manager works? Our contribution guide can be found here https://github.com/LVPlayground/playground/blob/master/CONTRIBUTE.md
If you wish to contribute you can submit a pull request. We appreciate your effort to improve the gamemode.

**Comment by GodeyLVP** [comment]
@oostcoast Lot's of folders,
Please mention the Directory. Thanks

**Comment by mblokker** [comment]
If oostcoast needs to mention the directory he can just as well do the whole fix himself.

I suggest that you get familiar with the folders, they contain a clear structure. Entities contain stuff like player, vehicle, property, gang related code. Features contains specific code like the color picker for /my color, or the ship manager, or etc.

In this case, you would need to look into https://github.com/LVPlayground/playground/tree/master/pawn/Entities/Vehicles.

You can use the GitHub search function too, or download the LVP Pawn Editor and load the whole gamemode and search there.

**Comment by mblokker** [comment]
Thanks Godey!
