### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#110]
playground/pawn/Resources/Games/Achievements.pwn

Achievements 29-40, and 42, are commented out. 

I assume that they're either broken, or unwanted for some reason.

Could someone perhaps clarify the situation here?

FWIW I updated the list of achievements, here: https://forum.sa-mp.nl/showthread.php?tid=18329

**Comment by mblokker** [comment]
They are not supported by the gamemode anymore, so that's why.

**Comment by ghost** [comment]
I'm unsure how we store achievements in the database, so I'm hesitant about removing line 55-66 and 68, and changing the achievement numbers listed under "The numbers of the achievements".

We list up to achievement no. 65 in-game (Sprayed (Spray 100 tags)) but in actual fact, there's only 52 achievements that can be unlocked.

**Comment by ghost** [comment]
Ref: https://forum.sa-mp.nl/showthread.php?tid=32927

**Comment by RussellLVP** [comment]
We're re-doing achievements, so let's close this out.
