### ISSUE TITLE
Ingame nick changes

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#111]
I think it'd be nice if we could implement the ability for registered players to change their nickname whilst ingame. For example, players type /nick and a dialog appears in the same format we use when logging in. It would ask them to enter their new nickname (perhaps twice for verification/confirmation purposes).

This is much easier than the IRC method, and frees up admin time assuming the player asks an admin to do the change.

**Comment by RussellLVP** [comment]
There is a technical difficulty here— the gamemode (deliberately!) does not have the ability to write to the `users` and `users_nickname` tables. All their mutable information is in a table called `users_mutable`.

Perhaps we should allow name changes on the website instead?

**Comment by LVPJoe** [comment]
Allowing name changes (and password changes) on the website would be a good solution and worth looking in to.

**Comment by LVPJoe** [comment]
We're very unlikely to address this issue in the foreseeable future. A new issue will be filed if this changes; file a new issue if you feel strongly that this should be reconsidered.
