### ISSUE TITLE
Stay within the world boundries

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#12]
http://trac.sa-mp.nl/lvp/ticket/1585

Granny:

> When either winning or loosing a minigame (I've only tested with DM minigames, though it most probably happens elsewhere) you'll be presented with: Stay within the world boundries
> Here is a screenshot: ​http://i.imgur.com/UhpoH6j.jpg
> This is nothing more than a minor annoyance and doesn't impact the minigame at all (at least, from what I've observed), though it would be nice if this was fixed.

**Comment by RussellLVP** [comment]
I'm going to need more information on this one. After which minigame(s) did this happen?

**Comment by ghost** [comment]
@RussellLVP 
In this example, it was the "Minigun Madness" minigame. I'm not sure if it happens with others.

**Comment by ghost** [comment]
Yellow ones doesn't show the "stay within world boundries".
![Alt Text](http://i61.tinypic.com/30vj29d.png)

And fist fight knockout keeps on respawning you without you stepping out of the ring.
![Alt Text](http://i62.tinypic.com/21lpvdy.png) 

Note: Many of the minigames are bugged.

**Comment by ghost** [comment]
This is still an issue sadly. I just tested /knockout on the prod and test server, it's unplayable.

**Comment by ghost** [comment]
Sadly this is still an issue - players will still be presented with the message in the screenshot I initially gave: http://i.imgur.com/UhpoH6j.jpg

Note that /knockout works perfectly and can be played now - it's just a case of the world boundry messages that appear when a minigame has finished.
