### ISSUE TITLE
Minigames cannot be started

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#120]
We did have a case open for this in the past, but I believe it was on Trac as I can't find it here on Github. When trying to start a deathmatch minigame, such as /sawnoff, /random, etc, you'll be unable to:

![s7jmkfd](https://cloud.githubusercontent.com/assets/15123289/13379958/517695e6-de2d-11e5-9c1f-12b49854c082.png)

As shown in the screenshot, there's supposedly no one in a minigame. This has been happening for several hours now (or at least, I was only made aware a few hours ago).

**Comment by ghost** [comment]
This has happened again. No players are in a minigame as per /minigaming, and minigames can't be started (tried /sniper, /sawnoff, etc).

![sa-mp-003](https://cloud.githubusercontent.com/assets/15123289/14935980/6236a174-0edd-11e6-8bd9-96af8a054de4.png)

I was able to fix it with /fixminigames - but if there doesn't happen to be an admin ingame (who's alert, paying attention and more importantly, knows about the command), we have the potential to see players leave. 

I seem to remember Russell stating something about one (or more) minigames which aren't being closed/ended properly, which is causing this. Is this something I can help to troubleshoot? I'm happy to do so if someone can give me some pointers.

**Comment by xhoogland** [comment]
Are we still experiencing this issue?

**Comment by RussellLVP** [comment]
I haven't heard about occurrences for quite a while. Closing.

**Comment by ghost** [comment]
This is still an issue unfortunately. Just now I attempted to start /ww and I received this message:

![ww](https://cloud.githubusercontent.com/assets/15123289/19151071/8a0fb9c6-8bc2-11e6-97e1-6e07cc18d264.png)

Checked and no minigames were running:

![uu2cjro](https://cloud.githubusercontent.com/assets/15123289/19151079/9a970d76-8bc2-11e6-8bc5-156d8da5d31e.png)

I am fairly sure that /minigaming is accurate, as the last /ww signup was almost an hour ago as of the time I make this reply (12:48 GMT +1)

[11:54] _%Noweni:%#lvp.echo_ **\* wali (Id:18) has signed up for /wwtw.

There is some suggestion that this problem occurs when a player who signed up leaves during a minigame or gets kicked/banned. I have not yet been able to check this myself to verify these claims.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
