### ISSUE TITLE
Implement /ban [player] [days=3] [reason] to fix LVP ban system.

### ISSUE THREAD

**Issue by mblokker** [LVPlayground/playground#122]
Right now a player gets a month default ban with a chance to appeal for a lower ban duration. The proper way should be to include the amount of days with the ban itself, giving the player the opportunity to appeal to this.

If no days are input, have a default duration of 3(?).

**Comment by RussellLVP** [comment]
Parsing could be a bit tricky to support reasons.

```
/ban cake healthhax
/ban cake 5 healthhax
/ban cake 99 health
```

Supporting `/ban [player] [days=3] [reason]` seems like a great idea to me.

**Comment by mblokker** [comment]
Ofcourse I totally meant that!

**Comment by RussellLVP** [comment]
![Image of cake](http://trendyoutlook.com/wp-content/uploads/2015/04/amazing-birthday-cake.jpg)

**Comment by mblokker** [comment]
![image](https://cloud.githubusercontent.com/assets/15170813/13380588/6a17f80a-de47-11e5-9741-15f867a043b0.png)

**Comment by RussellLVP** [comment]
You should probably write a brief topic for the crew forums announcing this change?

**Comment by mblokker** [comment]
Absolutely, I thought that would be a good thing to do when it's released but I might as well write it now.
