### ISSUE TITLE
Warehouse FightClub

### ISSUE THREAD

**Issue by XilentLVP** [LVPlayground/playground#133]
A player invited me to duel in Warehouse arena,after the fight started we both saw that we couldn't take damage. I think is not needed to upload a video or something.

**Comment by HopperLVP** [comment]
as i tolded Granny Also ! This Warehouse is bugged

**Comment by xhoogland** [comment]
Seems fine to me, just tested and tried stuff with Darkfire.

**Comment by ghost** [comment]
I just tried this once more on the production server, sadly it's still an issue.
