### ISSUE TITLE
Add shadow mute functionality

### ISSUE THREAD

**Issue by jadegraaf** [LVPlayground/playground#136]
Sometimes is necessary to mute someone without them knowing it. For example trolls that keep evading.
When a player is shadow muted it must look to him that they are able to continue using the chat and their messages are send to everyone but they actually aren't.

Either we add a new command like /shadowmute [player/ID] [duration] or introduce another flag for /mute [player/ID] [duration] [shadowmute yes/no].

Only the crew should be notified when a shadow mute is set or expires, don't tell the target.

**Comment by LVPJoe** [comment]
I like this idea.

**Comment by mblokker** [comment]
I'm not seeing the benefits of adding this. If one's evading, shouldn't we serialban him instead of toying around?

**Comment by jadegraaf** [comment]
@mblokker, this isn't about toying around. As you might know serial banning isn't effective all of the time. For those few cases where it isn't shadow muting will silence those type of evaders. They can be rather annoying.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
