### ISSUE TITLE
Empty Gang Fix

### ISSUE THREAD

**Issue by harryrf3** [LVPlayground/playground#138]
Admins can enter a gang more than once without first leaving. In turn, it creates "fake" instances of the join process and shows that there are more players in a gang then their actually is.

A simple solution would be to add a check to see, first, if an admin is already in a gang, then send them a message saying so. Otherwise, allow them entry.

**Comment by xhoogland** [comment]
Fixed in commit https://github.com/LVPlayground/playground/commit/bc75ef3bb5ff4c60509318aacf5c592e8998ae10.
