### ISSUE TITLE
Improve vehicle selection of the vehicle export feature

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#14]
http://trac.sa-mp.nl/lvp/ticket/496

tl;dr - The export handler currently randomly chooses vehicles based on an array and chooses a random value for each vehicle and requests them to be delivered. 
- Vehicle choice should be automated based on the current ingame vehicles instead of chosen from an array. Obviously, boats and planes etc will need to be excepted.
- It should choose new random vehicles after an interval of 15 minutes if all requested vehicles have not been delivered
- Decrease the money received for exported vehicles; currently 91,200.

**Comment by mblokker** [comment]
I'm not sure what the original Trac ticket stated, but the vehicle selection seems to do fine now. There were some issues with vehicles located in the ocean far away from the mainland, but that got fixed here: https://github.com/LVPlayground/playground/commit/3b066355a513efb717f2eec6799fb236569f0342

If more issues appear, this ticket can be reopened.
