### ISSUE TITLE
FightClub is full without any people in it

### ISSUE THREAD

**Issue by xhoogland** [LVPlayground/playground#143]
Gives the following message:
![](http://puu.sh/o9WnQ/80fd089850.jpg)

Perhaps related that a /q doesn't set people leaving the FC?

**Comment by xhoogland** [comment]
#24

**Comment by ghost** [comment]
This still seems to be an issue. I was able to fix it with a quick /resetfc - but this is of course not ideal. 

![sa-mp-002](https://cloud.githubusercontent.com/assets/15123289/14935941/b72c8c2c-0edb-11e6-893f-bedb988281e6.png)

**Comment by RussellLVP** [comment]
I have applied a bandage patch by increasing the maximum number of running Fight Club matches. This does _not_ solve the problem, but hopefully makes it appear a bit less often.

**Comment by RussellLVP** [comment]
I haven't heard issues around this for ages. Closing.
