### ISSUE TITLE
Illegal Vehicle Mods 

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#145]
A problem I see fairly frequently is players illegally modifying their vehicle, causing other players within x proximity to crash/timeout. It can sometimes be tricky to pin-point the player responsible too. Is there any kind of automation we can implement to either automatically ban or deal with the matter in a more "soft" sense?

Note: I do see a "NoVehMods" filterscript in the filterscripts directory - perhaps we should use this. No idea how it works or if it's stable.

**Comment by mblokker** [comment]
NoVehMods filterscript is the temp. solution which kicks players abusing vehicle mods.
