### ISSUE TITLE
Quick Feedback - Gang System

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#149]
- It's possible to invite yourself to the gang. Can a blocker be created? I.e: _Error: You cannot invite yourself to the gang!_

![untitled](https://cloud.githubusercontent.com/assets/15123289/14943536/e47bae12-0fd3-11e6-89b0-03467afc8b6e.png)
- For testing purposes, I tried to invite ID 1 (**note: my ID is 0**), the output was the same as in the screenshot above. Interestingly, higher IDs (i.e. 2, 3, 4) returned nothing more than: _Usage: /gang invite  [player]_
- Using /gangs top will list the Top Gang(s) as it should do, but it also shows "Type '/gangs top' to list...blah" underneath. 

![untitled](https://cloud.githubusercontent.com/assets/15123289/14943596/239988de-0fd5-11e6-991c-b6f6879dc281.png)
- There is no flood limit, it's possible to /gang invite [id] as much as you wish. I think we should introduce a blocker to allow one invite per session, with a message such as: _Error: You have already invited [name/id]. They can accept with /gang join._
- I created a gang (as the only member) and then left it (/gang leave). What happens then? In the Gangs database table, the gang still exists, and I can create a new one with the exact same details (tag, name & goal) which also gets added to the database (there's now 2x "test" gangs).
- I created a gang, left the server, rejoined (and logged in) and I wasn't a member of any gangs.

Other than that, I see no issues. Tested all the available commands and they seem to work fine (other than changing values via /gang settings, which Russell mentioned is incomplete)

**Comment by RussellLVP** [comment]
> It's possible to invite yourself to the gang.

https://github.com/LVPlayground/playground/commit/dfb4e11a28cf431d3dd0d4bda7badfe94511ba97

> ... the output was the same as in the screenshot above ...

https://github.com/LVPlayground/playground/commit/8df8771869f2478ffa7fbd477c2e0fd32b172bfb

> ... but it also shows "Type '/gangs top' to list...blah" underneath.

https://github.com/LVPlayground/playground/commit/56bc68959f2c894d061f1925472ad91b46d5b019

> There is no flood limit, it's possible to /gang invite [id] as much as you wish

https://github.com/LVPlayground/playground/commit/29b1957f46c42d712df8af2d5b7421ac0885a47e

> I created a gang (as the only member) and then left it (/gang leave). What happens then?

Right now the `gangs` table does not have to be modified, existence of a gang is judged by having members in it. In the long term we may want to modify this for performance reasons on the website, but this is not necessary now.

> I created a gang, left the server, rejoined (and logged in) and I wasn't a member of any gangs.

The database tells me that you're in two gangs at once, well done :). Any idea how your account may have ended up this way? Did you re-join a gang after reconnecting?

**Comment by ghost** [comment]
> The database tells me that you're in two gangs at once, well done :). Any idea how your account may have ended up this way? Did you re-join a gang after reconnecting?

Not too sure how this happened. I just created a fresh account (nickname: Granny2), joined the server, used /gang create, got confirmation that it was created, left the server, rejoined and same result - I'm not in a gang.

**Comment by RussellLVP** [comment]
I have fixed that problem as well, which was because your data could not be loaded due to a bug. Let's close this— please create many more awesome bugs for any issues you find :D
