### ISSUE TITLE
Quick Feedback v2 - Gang System

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#151]
- The current Pawn version of the Gang System enables owners of the Seti@Home property to view gang chat. Whilst I understand Gang Chat has not yet been implemented, we need to remember to create the link to ensure this behaviour continues. Known as: _ReadGroupConversationsFeature_
- NAME_QUESTION, TAG_QUESTION and GOAL_QUESTION show "undefined" for the dialog title if a validation check fails.

![goal](https://cloud.githubusercontent.com/assets/15123289/14948848/93a4f6a6-103c-11e6-82d3-87b3559949a1.png)
![name](https://cloud.githubusercontent.com/assets/15123289/14948849/93c42fe4-103c-11e6-9f1f-fdc643087ec1.png)
![tag](https://cloud.githubusercontent.com/assets/15123289/14948850/93d1d8d8-103c-11e6-9531-9a179ba1ee39.png)
- I think we should only allow characters A-Z, 0-9 for Name, Tag and Purpose. I can picture people using special characters which is just going to look tacky on the /gangs listing and elsewhere.

![gang](https://cloud.githubusercontent.com/assets/15123289/14948909/360bc988-103d-11e6-9c2a-d791dd4a74b9.png)
- We seem to be lacking some consistency. For example, If I'm **not** in a gang and use the /gang invite command, usage syntax (Usage: /gang invite [player]) will appear. The same thing happens with /gang kick. Can we copy over the behaviour from the other commands? I.e. /gang leave, /gang members, /gang settings - all of which show: _Error: You need to be part of a gang in order to be able to use this command._
- There's a few too many invite notices for my liking:

![untitled](https://cloud.githubusercontent.com/assets/15123289/14949400/8dbd5f3a-1041-11e6-8b8b-0738ea1274fd.png)

If you invite a player to a gang, is it possible to hide the "Granny2 has invited xxx..." message that follows after? It just seems a bit over the top to have both. Of course, your gang members should see the invite notice in blue - just not the person who did the invite. 
- I tried to create a gang with **Name:** Team GB, **Tag:** GB and **Goal:** Test. I was told it was too similar to another gang. The message in that dialog isn't too clear either (or bugged) - why is the [GB] Tag showing up? 

![untitled](https://cloud.githubusercontent.com/assets/15123289/14954035/c1edf89e-1066-11e6-81b0-6a7b4c979449.png)

I've tested all the available Gang commands, and I can't find anything else of concern, or room for improvement. The real test will come from our players!

**Comment by GrannyLVP** [comment]
If you invite a player to a gang, is it possible to hide the "Granny2 has invited xxx..." message that follows after? It just seems a bit over the top to have both. Of course, your gang members should see the invite notice in blue - just not the person who did the invite.

**Comment by RussellLVP** [comment]
> Whilst I understand Gang Chat has not yet been implemented, we need to remember to create the link to ensure this behaviour continues.

Yes, this may or may not be part of v1. It will be interesting to figure out the best way of supporting this.

> NAME_QUESTION, TAG_QUESTION and GOAL_QUESTION show "undefined" for the dialog title if a validation check fails.

https://github.com/LVPlayground/playground/commit/9176d1f161481326767a13f5222cbe0f66752ff5

> I think we should only allow characters A-Z, 0-9 for Name, Tag and Purpose. I can picture people using special characters which is just going to look tacky on the /gangs listing and elsewhere.

This is fair. https://github.com/LVPlayground/playground/commit/e003c74b8cbb603035e976f3aaf482218cbb204f

> We seem to be lacking some consistency.

Unfortunately, no. The parameters will be parsed and validated before the command's own code will even be executed. This offers great benefits overall (much less error checking all-round), but comes with a few downsides like this one.

> There's a few too many invite notices for my liking

https://github.com/LVPlayground/playground/commit/137f9021b93441ed62b7680c003c27ceac0483e7

**Comment by RussellLVP** [comment]
All fixed :) Thank you for the feedback!
