### ISSUE TITLE
/world bug allows vehicles and weapons on ship.

### ISSUE THREAD

**Issue by harryrf3** [LVPlayground/playground#156]
TheDestroyer contacted me and reported that he had found a way to bypass the protectoins we have in place so that players cannot bring weapons/vehicles on the ship. He doesn't have a GitHub, so I said I would file a report on his behalf.

**Issue**:

Players are able to use a sequence of commands to get vehicles and weapons on the ship in the main world.

**How to recreate:**

When away from the ship/ramp. Change to a /world other than 0. Go up past the ramp onto the ship, when past the ramp, change back to /world 0. This will allow you to have a vehicle on the ship as well as weapons. 

**While on the ship:**
- Godmode is **not** enabled as it normally would be.
- Players **can** shoot from the ship.
- Players **can** continue to abuse this sequence to pile cars on the ship, that then need to be manually removed by command or by driving them into the ramp.

**When/after entering the ramp:**
- Weapons reset to fists and godmode is re-enabled.
- Cars respawn when driven unto the ramp.
- After entering the ramp on foot, if a player enters a car on the ship, the car respawns.

**Update:**

After doing some more testing, players are able to change worlds while on either the ship or ramp, wait for their weapons to come back, then change back to world 0. As long as the player does not go to near the section that the ramp and ship meet, they can keep their weapons.

**Comment by RussellLVP** [comment]
Thank you for the very detailed bug report! I have fixed it in the Zone Manager here:

https://github.com/LVPlayground/zone-manager-plugin/commit/d7b4c520f2432968275c416f4ab7d66bc2c7e67b

I would expect it to be included with the next gamemode update :)
