### ISSUE TITLE
Auto pick up weapons

### ISSUE THREAD

**Issue by LVPDarkfire** [LVPlayground/playground#158]
Hi.
Lets say there is 4-5 different players fighting in a place, 2 of these people die, and the other people run into their weapons who is left after they died, they automaticllly pick them up, this could be very annoying for some people who maybe use uzi and m4 instead of tec9 and ak-47. So if the auto pickup is removed, its all fine.

Thanks
Darkfire

**Comment by ghost** [comment]
There has been some discussion about this on the forum: 

https://forum.sa-mp.nl/showthread.php?tid=32856

Personally I like Diablo's idea:

> it will better if there is anyway to pickup weapons without switching to them

**Comment by RussellLVP** [comment]
That's exactly how it has been implemented :( This may come down to `GetPlayerWeaponData` inaccuracy. Does this problem always happen to you, or only occasionally?

**Comment by mblokker** [comment]
The problem is that `GivePlayerWeapon` will set that weapon as the player's armed weapon.
We could try and use `GetPlayerWeapon` to get the weapon they are holding before picking up a weapon, and use `SetPlayerArmedWeapon` to set this weapon back after picking up.

**Comment by RussellLVP** [comment]
That is a good idea. Let's try it!

**Comment by RussellLVP** [comment]
@LVPDarkfire confirmed that this fixes his problem.

Thank you for the idea, @mblokker!!
