### ISSUE TITLE
Minor Gang Chat Issue

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#159]
It seems that using additional exclamation marks outside of ! for normal gang chat and !! for the admin gang chat option are recognized by the gang chat system.

For example, !!! will produce:

![untitled](https://cloud.githubusercontent.com/assets/15123289/15117439/73b285b6-15ff-11e6-85fb-73aa05df02fc.png)

Can we limit the usage of ! for normal gang chat, !! for admin gang chat, and any additional exclamation marks of those will just send as a normal message.

**Comment by RussellLVP** [comment]
Fixed. To summarise the behaviour:

**Players**:
- **!message** - gang chat
- **!!message** - regular message

**Administrators**:
- **!message** - own gang chat
- **!!message** - remote gang chat
- **!!!message** - regular message
