### ISSUE TITLE
Vehicles respawn when hitting water

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#16]
http://trac.sa-mp.nl/lvp/ticket/1595

Granny:

> Ocassionally, myself, other players, and other crew members, notice an issue where by vehicles will disappear/respawn when they land in water. I must stress that this issue is intermittent, and does not happen all the time.
> 
> As an example, today I was driving an Infernus, it landed in the water and then it immediately disappeared, leaving me stranded in the same place.
> 
> I know Badeend and I believe Luce have seen this issue first hand more than once, along with me.
> 
> For what it's worth, I had pretty high packetloss at the time (26%), maybe this is relevant.
> 
> I've also tested with many other vehicles, and it's not specific to the Infernus. Same problem with Sultan, Elegy, NRG-500, Packer and many more.
> 
> This is a pretty poor bug(?) report, though I wasn't sure what other details (if any) I could provide to aid in diagnosing and resolving the issue.

eF.Holsje:

> I only notice the despawning of cars on spawed cars (/inf or /v create). It also happens sometimes when the car is about to explode, or has been repaired after almost exploding.
> 
> Also, sometimes cars spawned just randomly disappear while driving.

**Comment by ghost** [comment]
@GrannyLVP
Does this only happen in the same area/location or something?

**Comment by jadegraaf** [comment]
Are /v create vehicles removed when they are 'destroyed'?
Apparently OnVehicleDeath is also called when a vehicle becomes submerged.
http://wiki.sa-mp.com/wiki/OnVehicleDeath

**Comment by ghost** [comment]
@strikerLVP 
I've seen it in many different areas (near chilliad, inside LV -- everywhere I believe). I cannot _always_ re-produce it, though. 

What @oostcoast has pointed out seems to make sense, perhaps that can be investigated?

**Comment by jadegraaf** [comment]
Please do. If my theory is correct /v create and /inf vehicles will be removed only if the vehicle health becomes 0 or they hit water. Could you monitor this with /dl?

**Comment by ghost** [comment]
I've spent the last few minutes testing this with various /v create vehicles, plus /inf on both my normal admin account, and under another name with /modlogin, in various different locations which I know for sure have been problematic before

My vehicle didn't disappear/respawn at all. Tried setting the vehicle health to low values (e.g. 250) as well.

As I cannot re-produce this anymore, perhaps it's no longer a problem. 

I think we can close this out for now.

**Comment by jadegraaf** [comment]
Great, lets do that. Thanks for providing more information.
