### ISSUE TITLE
Race System Issues

### ISSUE THREAD

**Issue by LVPJoe** [LVPlayground/playground#165]
Today I initiated race 5 through the race menu, another player signed up to enter, only I was taken to the race, and it outputs that I am unable to leave as I'm not in a minigame, but the checkpoints and race dashboard are seeming to function.

**Comment by LVPJoe** [comment]
It seems all races have the issue with /leave not working though

**Comment by LVPJoe** [comment]
Racers also do not show up in /minigaming, and racers can be teleported to

**Comment by RussellLVP** [comment]
I have rewritten much of the race system (oh the redness in https://github.com/LVPlayground/playground/commit/3f1fd174c27d89f8f178e3320a78558f1caabb07 ... <3) and these bugs have been fixed.

Please try it out on the test server, and let me know your experiences!

**Comment by LVPJoe** [comment]
Russ, all of the above mentioned bugs have been fixed. However, while testing them, found more issues that need to be fixed now that we're at a point of basic functionality.
- Race 34 and 35 have issues spawning the objects simultaneously with racers entering the arena; could we have them spawn pre-emptively at the point when race signups are initialized to reduce the delay? (100% of tested cases had at least one failure, which is unacceptable. It's certainly not an occasional issue.)
- All races fail to show race signups as an admin message or at the bottom of the display as all other minigames do.
- Any instances (specifically race 35) with rain as the forced weather should be reconsidered, as it causes FPS drop to an almost unplayable level, certainly skewing the results. (I drop from 70FPS average to 26 for example, and I know there are players with worse computers than I)

**Comment by RussellLVP** [comment]
All addressed, please file new bugs if you find them :)

Specifically to race 35, this player works well for some players, not very well for others. I don't think we should remove it based on that.
