### ISSUE TITLE
Remove race object preloading

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#17]
http://trac.sa-mp.nl/lvp/ticket/1576

Jay:

> Object preloading was implemented with races to resolve an issue with SA-MP object textures not loading in vehicles:
> ​https://www.youtube.com/watch?v=xdfPH_Pp7zI
> This was fixed in SA-MP 0.3z and so can be removed.

**Comment by ghost** [comment]
@RussellLVP This has been done right or I'm confused with something else?

**Comment by RussellLVP** [comment]
I really don't know actually. Perhaps ask Jay?

**Comment by mblokker** [comment]
I removed object preloading for map zones here: http://trac.sa-mp.nl/lvp/changeset/5111/LVP
However race object preloading hasn't been removed afaik, since the whole Race manager was built on it.

**Comment by RussellLVP** [comment]
Yes :( I changed the limits for the race system a few days ago and decreased the .amx size by 10%. I'm sure there's another 10-20% (!!!) to gain by removing preloads from there.

**Comment by RussellLVP** [comment]
This will be done by replacing the race handler in its entirety.
