### ISSUE TITLE
/derby 10

### ISSUE THREAD

**Issue by LVPJoe** [LVPlayground/playground#171]
When signing up for derby 10 for the second time in a row, I spawned underground near the haystack arena, and was then automatically disqualified when the car emerged back onto the ground.

**Comment by LVPJoe** [comment]
On the test server with three players I was unable to reproduce, but results may be different when the current revision on the test server goes live. Will test again at that point and update. I did experience this bug 2 times over the course of 20ish derbies on the main server, and was confirmed by NightFury that it does happen to him occasionally also.

**Comment by LVPJoe** [comment]
Figured out why I believe this happens; when more than the 4 allowable people manage to sign up due to simultaneous timing, there are only 4 spawn locations, so the 5th goes to a random location causing a failure in the script.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
