### ISSUE TITLE
Uncaught promise rejection: PlayerDisconnectError

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#175]
I was searching through the logs on the staging server to see if I could spot an obvious cause for #174, and whilst I couldn't, a bit further down and I saw this:

> [20/05 08:00:21] [part] George has left the server (0:1)
> [20/05 08:00:21] =========================
> [20/05 08:00:21] Uncaught promise rejection: PlayerDisconnectError: The player has disconnected from the server.
> [20/05 08:00:21]     in PlayerDisconnectError (base/errors/player_disconnect_error.js:12)
> [20/05 08:00:21]     in onPlayerDisconnect (components/dialogs/dialog_manager.js:71)
> [20/05 08:00:21] =========================

**Comment by RussellLVP** [comment]
This is fine, don't worry about it. At some point I'll fix it, but nothing will screw up because of it.

**Comment by RussellLVP** [comment]
This is gone :).
