### ISSUE TITLE
/vr all

### ISSUE THREAD

**Issue by LVPJoe** [LVPlayground/playground#176]
This would be a useful command for large cruises and such.

**Comment by mblokker** [comment]
Better yet, grant everyone godmode who's in range of the cruise leader (outside LV).

**Comment by mblokker** [comment]
I've given this some second thoughts. Is it useful? Or is it another unnecessary feature that we'll not use very often.

**Comment by ghost** [comment]
I don't particularly like the idea of a _/vr all_ command, as I think it will introduce extra concerns for both players & crew, i.e. abuse - a player's vehicle who's not in a cruise is getting shot at, suddenly it gets repaired. If we were to introduce this command, I'd definitely want to see an Admin Notice: _George has used the /vr all command._

My personal feeling is that the cruise system is fine as it is. We do advertise quite clearly, throughout the duration of the cruise, that players can use /vr outside of LV.

**Comment by LVPJoe** [comment]
I think it would be rarely used, but could be useful in certain circumstances. I've on two occasions in the past month had all but one player online involved in a cruise. I think these scenarios, while not daily, happen often enough that it would be worth the command existing. An admin notice would be expected; I also think that regular /vr should have an admin notice.

A different solution could be that when /cruise start is initiated, you could /cruise add id. When added to the cruise, /cruise vr could exist and repair all cruiser's vehicles.

**Comment by LVPJoe** [comment]
Perhaps /vr can be added to the /lvp access submenu?
