### ISSUE TITLE
Team chat

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#179]
Tonight in /robbery, Lithirm pointed out that we can't teamchat with the usual ! prefix. Unsure what an ideal fix would be here, perhaps change the prefix to ~

**Comment by SAPlayground** [comment]
Good Idea That Problem is in some DeathMatches Area's Like 

That Be good if LVP Change Team Prefix to ~ and Customize ! For DM Area's and Minigames

**Comment by ghost** [comment]
Good Idea That Problem is in some DeathMatches Area's too

That Be good if LVP Change Team Prefix to ~ and Customize ! For DM Area's and Minigames
