### ISSUE TITLE
Map zone vehicles falling from the sky in world 0.

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#18]
http://trac.sa-mp.nl/lvp/ticket/1524

cake:

> Map zones utilize several platforms in the sky where these cars are spawned on. However, after some time these cars fall through the sky on their respective positions.

**Comment by ghost** [comment]
I've gathered a couple screenshots:

http://i.imgur.com/klH8biz.jpg
http://i.imgur.com/K1ydTyj.png
http://i.imgur.com/eK18oBy.jpg

This always tends to happen in the same locations.

**Comment by mblokker** [comment]
I have done some tests, and it seems that quite a lot of jumps are bugged. Jumps involving cars either have cars falling from the sky in world 0, or I don't even get teleported to the jump spawn at all.
