### ISSUE TITLE
Streamer Plugin Update

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#183]
As a notice, a new version of the Streamer plugin has been released:

https://github.com/samp-incognito/samp-streamer-plugin/releases/tag/v2.8.1

**Comment by mblokker** [comment]
The update has been pushed to LVP: https://github.com/LVPlayground/playground/commit/0390a5539a22259ab8c4cc2c6ec11bbad4461fec

Note to self: update mainserver streamer.so upon restarting server.
