### ISSUE TITLE
Crew Coverage Graph

### ISSUE THREAD

**Issue by LVPJoe** [LVPlayground/playground#184]
It would be nice to have a crew coverage graph, broken down by day, week, and per hour of the last 48 perhaps? Whether it's simply a count, or a list of which crew, it would be helpful. Thank you.

**Comment by ghost** [comment]
Whilst we don't have anything like this right now, these may be helpful:
- https://forum.sa-mp.nl/showthread.php?tid=32916
- https://sa-mp.nl/online/toplist/week.html
- https://sa-mp.nl/players/staff-members/1/active/asc.html

**Comment by LVPJoe** [comment]
We're very unlikely to address this issue in the foreseeable future. A new issue will be filed if this changes; file a new issue if you feel strongly that this should be reconsidered.
