### ISSUE TITLE
/report integration

### ISSUE THREAD

**Issue by LVPJoe** [LVPlayground/playground#186]
I think it would be nice if when a report comes in, you could just do /watch without an id and immediately watch the id that was reported last. 

Also, /report should fail if the name cannot be found, or the id is invalid, to force people to use /report on valid players. This also can prevent report spam, as it could output "You've already reported this user" on 2nd and 3rd attempts.

**Comment by xhoogland** [comment]
Forcing is built-in at the new version. /watch would be a bit harder at the moment and checking for already reported can be built-in.

**Comment by xhoogland** [comment]
Above 4 commits implement the "checking for already reported"-feature.

**Comment by LVPJoe** [comment]
We're very unlikely to address the /watch component of this feature in the foreseeable future. A new issue will be filed if this changes; file a new issue if you feel strongly that this should be reconsidered.
