### ISSUE TITLE
Jetpack Restrictions

### ISSUE THREAD

**Issue by LVPJoe** [LVPlayground/playground#190]
Jetpacks currently are largely unrestricted, lack cost, and as a result of LVP10's free use of them, have become expected by players. By implementing the coding restrictions discussed (A cost, godmode, weapons disabled, and 100 health to initialize) this feature can again be made available to players.

**Comment by RussellLVP** [comment]
> have become expected by players.

Could you clarify why you think this is the case?

I would like us to think carefully before introducing this. Does it fit in the direction we'd like to move LVP in? I feel that jetpacks are a significant step in moving from a DM-style server to a Freeroam-style server.

Do we have evidence that players think this is a good idea?

**Comment by LVPJoe** [comment]
A few players in the past five days have requested jetpacks from crew with varying levels of success. They also were quite popular and went over well with the general population over the LVP10 weekend, even without restrictions that would prevent abuse in place. I think that continuing to have the feature able to be enabled and disabled is a good idea, for instance, to disable during killtime. Also, should there be negative feedback, we could work with players to figure out the solution that best satisfies all parties. I believe it fits in the direction of accommodating and appealing to more players, while still having restrictions to prevent DMer anger. 

A restriction that I thought of, which would make sense to prevent abuse, is to allow jetpacks to be obtained only at airports. This could also make implementation easy, as we could add it to the menu that currently exists at airports to initiate a flight to other cities.

**Comment by LVPJoe** [comment]
GM was updated to allow management to enable jetpack commands, thus issue is solved.
