### ISSUE TITLE
Race Handler Issue when joining a race whilst already being in a vehicle

### ISSUE THREAD

**Issue by LVPJay** [LVPlayground/playground#192]
The race handler get's confused when a players state changes when they are teleported to the race start point - it kicks them out and leaves the countdown textdraw stuck on their screen.

 Steps to replicate:
1. Whilst in a vehicle, join any race e.g. /race 1
2. Wait for the signup phase to end and the race to start
3. When you're teleported to the race start point, it will say you left your vehicle and will remove you from the race.
4. You will also be stuck with the countdown textdraw on your screen with no way to remove it other than a rejoin.

Logic needs to be added for players that are in a vehicle when they signup for a race, so that when their state changes it doesn't think they have left the race. The flag which determines that they are in the race probably needs to be updated after they have been teleported.

Screenshot attached 
![sa-mp-001](https://cloud.githubusercontent.com/assets/19611398/15612472/cf91e57c-2426-11e6-8733-b2340e9dbbe2.png)

**Comment by xhoogland** [comment]
@mblokker Didn't you do anything with this in a commit already?

**Comment by LVPJay** [comment]
Nope not touched it, I'll take a look at it though assign it to me I need to be added to the project :+1:

**Comment by xhoogland** [comment]
https://github.com/LVPlayground/playground/commit/f93b56f7525c8364715c2eec073ae33659daf0bb

**Comment by mblokker** [comment]
https://github.com/LVPlayground/playground/issues/181
