### ISSUE TITLE
Race Signup Textdraw Issues

### ISSUE THREAD

**Issue by LVPJoe** [LVPlayground/playground#196]
When a race is started, the player signup textdraw at the bottom of the screen stays for a much shorter time than other minigames, and the large textdraw similar to a /showmessage does not show up at all, thus lessening the awareness of the races and lowering potential enrollment.

**Comment by RussellLVP** [comment]
The messages disappear only for the player who just started or signed up for the race. They'll remain visible for everybody else.

While this is a known issue, fixing it would require too much work. I'm closing this since it's not worth the hassle.
