### ISSUE TITLE
/p id handofgod and broken commands

### ISSUE THREAD

**Issue by LVPJoe** [LVPlayground/playground#197]
After having /p id handofgod done to you, as the victim of the command, it breaks the /p subset, /forward, and probably other commands I didn't test.

**Comment by ghost** [comment]
To clarify, this has been an issue for at least a year - I remember it being a problem as soon as I became crew...though it never dawned on me to report it for some reason. Just wanted to add this so our developers know this isn't relevant to a recent commit. 

I believe the idea behind this was to prevent people using commands to evade death when being thrown in the air for a _driveby punishment_. If a player chooses to punish another player for DB and throw them in the air, it's not fair for the punished player to use /inf (for example) as a workaround for the inevitable death. Perhaps the behaviour was replicated to the handofgod command, I'm not too sure.

The idea then being, the player will die, and commands will become available.

I suspect you were testing this on another crew member (or vice-versa)?

**Comment by LVPJoe** [comment]
I observed it when a temp admin was testing commands on me to familiarize themselves with their affects on the user. I then confirmed it by using the command on myself two more times. This is a serious bug as it forced you to logout, and then back on to be able to perform any administrative functions, which could cause you to miss a hacker/etc should somebody do this to you while you're AFK.

**Comment by ghost** [comment]
I seem to remember a simple /fix [id] did the trick for me to restore normal command access. 

But you're right nevertheless, it should be fixed so that administrators are excluded from this behaviour.

**Comment by mblokker** [comment]
LVPJoe, could you specify if you died from the handofgod event?

Looking through the code reveals no special cases for administrators. The disabled command functionality is reset upon death, spawn and fix. There's really nothing more I can do to improve this, other than allowing crew to have cmd availability during the fall.

**Comment by LVPJoe** [comment]
I don't believe I did die, but I believe the solution would be to allow crew to have cmd availability at all times as you mentioned.
