### ISSUE TITLE
Open up Caligula Casino Basement

### ISSUE THREAD

**Issue by LVPJay** [LVPlayground/playground#209]
The basement in Caligula's casino is locked and it would be nice to make it available to aid when playing HAS.

It's the door located in the screenshot attached.
![sa-mp-002](https://cloud.githubusercontent.com/assets/19611398/15805466/77784f8a-2b23-11e6-89ee-1c5e659b9cd0.png)

In order to remove it, I found this forum post: http://forum.sa-mp.com/showthread.php?t=595484

This just needs implementing and testing

**Comment by xhoogland** [comment]
Seems to be done per 91dead583c84857065c4af7e38eaf1349ff53fe1 a long time ago, thanks! :+)
