### ISSUE TITLE
False autobans after killtime

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#21]
http://trac.sa-mp.nl/lvp/ticket/1353

Beaner:

> Players get auto-banned after a killtime ends if they receive the killtime weapon (such as a rocket or minigun) and then pause their game until the killtime ends.
> 
> If a player remains paused the whole time (before the start & after the end of the killtime), nothing happens.
> 
> This has been tested thoroughly in version 12.6.1.

striker:

> started killtime like 5 times, few times rocket then minigun and no one got banned. Two players were paused, one came back right after it was over no ban.

cake:

> Maybe this will fix it: ​http://trac.sa-mp.nl/lvp/changeset/4877/LVP

Beaner:

> This happened again. I'm not sure whether the players were active or paused.
> 
> **Edit**: Since the pause manager doesn't exist now, I don't think the original description of this ticket is relevant anymore. How about white-listing weapons such as rocket launchers, heat seekers, miniguns, molotovs, etc. during kill-times?

**Comment by ghost** [comment]
I haven't seen (or heard of) false auto bans from Killtime for quite some time -- certainly not this year, at least. 

Has anyone else observed this problem recently?

**Comment by ghost** [comment]
Closing this out as I've not seen this happen for a long time.
