### ISSUE TITLE
Red Barrels: Find and shoot

### ISSUE THREAD

**Issue by LVPJay** [LVPlayground/playground#210]
### **Requirements**

As a response to the popularity behind the SprayTag feature, a new feature should be developed: Red Barrels
https://www.youtube.com/watch?v=6MQay6UIJDc

This will open up the possibility for a player to spawn vehicles on the fly similar to /inf, however the vehicles available will update as the player sprays more barrels:

10 Barrels: Cycle bike
20 Barrels: PCJ-600
30 Barrels: Alpha
40 Barrels: ZR-350
50 Barrels: Super GT
60 Barrels: Cheetah
70 Barrels: Turismo
80 Barrels: Hotring Racer
90 Barrels: Any of the above
100 Barrels: Any of the above and access to LVP Radio on foot
### **Technical Implementation**

[To be scoped out - will update with findings]

**Comment by ghost** [comment]
Nice Suggestion I think Players love this Suggetions 
So Add this to LVP is Good idea 
Nice,Jay

Night$Killer
