### ISSUE TITLE
FightClub Issuse (Come Back Again !)

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#211]
Hi !
3 Players in one Duels That not acceptable 
Duel : 
[H]Bestt vs [BB]QUIPT
and [BB]NightFury There too
i can't explain Just ScreenShot :

![sa-mp-064](https://cloud.githubusercontent.com/assets/19735645/15828000/25015b04-2bfd-11e6-9c9e-a9fb771b1df4.png)
![sa-mp-067](https://cloud.githubusercontent.com/assets/19735645/15828001/25099602-2bfd-11e6-9890-801c9627d668.png)
![sa-mp-071](https://cloud.githubusercontent.com/assets/19735645/15828002/250d2bc8-2bfd-11e6-97ed-715f2bc7e7b8.png)
![sa-mp-072](https://cloud.githubusercontent.com/assets/19735645/15828003/251aa154-2bfd-11e6-8406-a9c669c4916a.png)
![sa-mp-073](https://cloud.githubusercontent.com/assets/19735645/15828005/25218d34-2bfd-11e6-84c5-84c091fe62c9.png)
![sa-mp-074](https://cloud.githubusercontent.com/assets/19735645/15828004/25201850-2bfd-11e6-9689-aae489ed4463.png)

**Comment by LVPJoe** [comment]
Hi Yassine,
This was a mistake by NightFury, as he accidentally TPed to QUIPT not knowing he was in a fight. As your screenshots show, as soon as he realized, he ran to the side and got out of the way. Sorry for the inconvenience, but this is not a bug.

**Comment by ghost** [comment]
np, Good , This is better than be a Bug
