### ISSUE TITLE
/report didn't appear in-game, only on IRC

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#216]
I just noticed something a bit odd:

**IRC:**

> [15:47] <%Nowani> [20] The[.]King: wena lkazi lakhar
> [15:47] <%Nuwani> [13] **\* FatherSaab left the game (leaving).
> [15:47] _%Nuwani:%#lvp.echo_ **\* Report [K4L]BuLLe7 (Id:39): Player: HunterZolomon (Id:12) - Reason: BAN HIM ALREADY HE KEEPS TELPEORTING TO ME WITHOUT /TP AND HAS AIMBOT
> [15:48] <%Nawani> [21] Madlaggz(A): HOUSEM

**In-game:**

![sa-mp-011](https://cloud.githubusercontent.com/assets/15123289/16178023/c1bf1af2-3635-11e6-8b17-7a1d93e28d8d.png)

As you can see, the report by [K4L]BuLLe7 is missing and didn't show up in-game. I was logged in with my normal George account, everything else seemed fine.

Is it possible that this is related to https://github.com/LVPlayground/playground/commit/4cb7a197db1b934b04514f659dd788cce9737c57?

**Comment by mblokker** [comment]
This is related to JS not (yet) having the capability to split every 144 chars before calling SendClientMessage.

**Comment by RussellLVP** [comment]
@xhoogland is this fixed?

**Comment by RussellLVP** [comment]
I'm going to assume it is. Closing.

**Comment by xhoogland** [comment]
The Message-method afaik still needs a fix for this.

**Comment by RussellLVP** [comment]
Can you clarify what that means? What is the Message method?

**Comment by xhoogland** [comment]
Message is a method ff the Player-entity in the javascript. cake explained that a pawnInvoke of SendClientMessage does not use cake's implementation in pawn and thus still has a limit.

**Comment by RussellLVP** [comment]
Correct. What does that have to do with this issue?

**Comment by xhoogland** [comment]
Good question indeed, I assumed it was longer than 144 characters, but it isn't!

[00:12:03] Xanland !len Report [K4L]BuLLe7 (Id:39): Player: HunterZolomon (Id:12) - Reason: BAN HIM ALREADY HE KEEPS TELPEORTING TO ME WITHOUT /TP AND HAS AIMBOT
[00:12:03] Saber \* Length: 137

**Comment by RussellLVP** [comment]
Please file a new issue if that's significant. Closing.

**Comment by xhoogland** [comment]
Will be fixed if we fix #338.

**Comment by xhoogland** [comment]
We have a final answer regarding length. Too long messages via a command are still possible and need to be thought out! Perhaps manual wrapping since we know what the output should be...

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
