### ISSUE TITLE
Bug with the punish system for drive-by kills

### ISSUE THREAD

**Issue by Lash** [LVPlayground/playground#218]
Sometimes when I drive-by/heli kill someone then the person that got killed throws me in the air I survive the fall and I loose my weapons and alos cannot use commands.

**Comment by RussellLVP** [comment]
I think this could only happen when you fall in the water? In what other situation would you survive a four-hundred unit fall?

I've added a change where the health of the person falling is set to 1 prior to the fall, which should reduce their survival chances further.

**Comment by Lash** [comment]
The fall does not affect the players health at all, it stays full and you lose your weapons at the point you are teleported in to the air.

**Comment by LVPYassine** [comment]
Russell Check this https://github.com/LVPlayground/playground/pull/233 :D

**Comment by LVPYassine** [comment]
[New] Check This Russell https://github.com/LVPlayground/playground/pull/235 

I Think that bug fixed with it

**Comment by LVPYassine** [comment]
mblokker this about Teleport abuse
You can join the server now ?

**Comment by mrnategeek** [comment]
Does the scripters dont know how to program stuff??? Here I creating a website with Jade and Less even Mustache that complies to HTML and CSS

**Comment by mblokker** [comment]
That's weird. Do you use crash-fix Lash?

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
