### ISSUE TITLE
New Gang System Bug 

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#220]
Hello Guys !

Some Members in Th gang Not be Showed in Gang members list check ScreenShot : 

Monster and Smash in the gang But not showed in the list

![sa-mp-057](https://cloud.githubusercontent.com/assets/19735645/16591277/9f4cff4c-42ca-11e6-9f6d-ea6aa31b5e66.png)

Thanks,
[H]Night$Killer

**Comment by RussellLVP** [comment]
Does this still happen? The database tells me that there's three members in your gang: [TR]Death$tar, HooDie and [TR]Un1DENT1F1ED.

**Comment by ghost** [comment]
> Thedatabase tells me that there's three members in your gang: [TR]Death$tar, HooDie and     [TR]Un1DENT1F1ED.

those [TR]Death$tar, [TR]Un1DENT1F1ED not in gang
just HooDie But he is kicked now :D 

>  Notice : we have 15 Members in the gang

**Comment by xhoogland** [comment]
Are you still experiencing this issue?

**Comment by ghost** [comment]
Yes
