### ISSUE TITLE
HayStack in World 0

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#221]
Hello Guys !!

I noticed some Bug in World 0 like Ship tag in Haystack !! ?? that include The Bot

check  Screenshot :

![sa-mp-058](https://cloud.githubusercontent.com/assets/19735645/16617825/77fcf022-4375-11e6-96f8-cf764007cd9b.png)
![sa-mp-059](https://cloud.githubusercontent.com/assets/19735645/16617826/7800a942-4375-11e6-9d23-403e514e08db.png)

Thanks,
Night$Killer

**Comment by RussellLVP** [comment]
I have no idea why that text would be there. Does it always happen?

**Comment by jadegraaf** [comment]
I'm fairly sure the location of the floating text is 0,0,0 in GTA's coordinate system, probably has something to do with it.

**Comment by mblokker** [comment]
Yes. this is a common issue. I have no clue why this happens, other than what oostcoast shared. Also, /fixservices seems to fix this.

**Comment by ghost** [comment]
> I have no idea why that text would be there. Does it always happen?

Yes is All time there join if u want see it But in /world 0

> Notice: The Bot is There too but invisible u see the radar ?

Thanks ;)
