### ISSUE TITLE
PM multiline color

### ISSUE THREAD

**Issue by LVPJoe** [LVPlayground/playground#223]
When a PM is too long to be displayed on one line, the second line displays in yellow like the beginning of the pm where the name is, rather than the white that it should to show continuity of the message.

**Comment by LVPYassine** [comment]
i think 1 line is better than 2 lines Open a Poll in LVP Dev-Forum for see the player reactions

Thanks,
Yassine

**Comment by RussellLVP** [comment]
Is this wrapping new? I don't recall SA-MP ever doing this before. In either case, this should be easy- will fix.
