### ISSUE TITLE
Tow 12 Location

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#229]
Hello 
i noticed tow 12 location not work 

i already Fix it in https://github.com/LVPlayground/playground/pull/228

**Comment by RussellLVP** [comment]
What is `/tow 12`? I don't think it exists.

/cc @xhoogland

**Comment by xhoogland** [comment]
Dunno, as @oostcoast explained in another issue/pr we have 12 taxi/tow-locations (13 for /t). They are from 0 to 11, which means 11+1 locations. I think somehow @LVPYassine got confused with that?

**Comment by RussellLVP** [comment]
We now have a `/tow 12` thanks to @LVPYassine. Closing this.
