### ISSUE TITLE
Implement a new Gang System 

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#23]
Gang System Features:
http://trac.sa-mp.nl/lvp/ticket/1262

**Gang System Features:**
- Minimal 3 gang members is needed and a 3 minute timer. 
  - Could increase the time if it's less than 3 gang members. 
- Light gang turfs colour.
  - Players can have a clear view on the road/map. 
- Gang colour table?
  - Table with lots of colours :? 
- Respect points for taking a turf.
  - Introduce another currency. 
- Gang turf expires.
  - Gangs will have to maintain activity to keep turfs. 
- Gang achievements.
- Persistent Gangs.
- Gang bank.
  - With limit :? 
- Health icon dropped (5-10HP).
  - For defending your turf after killing your enemies. 
- Commands:/gang [create, colour, bank, rename, skin, delete, leave, join, info, kick]. 

**Unfinished Features:**

```
Implement support for bank accounts for gangs: http://trac.sa-mp.nl/lvp/ticket/934
Implement support for persistent gangs in the gamemode: http://trac.sa-mp.nl/lvp/ticket/935
Icons for Gang Leader, Gang Manager and Gang Member: http://trac.sa-mp.nl/lvp/ticket/1013
```

**Comment by RussellLVP** [comment]
I'm superseding this by the following issue, since it contains a bunch more information.

https://github.com/LVPlayground/playground/issues/68
