### ISSUE TITLE
Implement a new Fight Club System

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#24]
by cake

 As part of the ongoing deathmatch rewriting, this should have a throrough cleanup. Right now it's not user friendly to invite someone for a match, the options are just too much. Pre-formatted sets of weapons/location/fight-type + dialog windows could help a lot.

That's why the FC is going to be rewritten. This project is split up in several smaller tickets, all connected to the same milestone. Please make suggestions in the correct tickets. If no ticket is suitable for your input, post it here.

**Fight Club System Features:**
- Implement support for PvP and GvG fights.
  - http://trac.sa-mp.nl/lvp/ticket/1409
- Implement a scoreboard listing recent FC results.
  - http://trac.sa-mp.nl/lvp/ticket/1406
- Create +/- 3 FC locations. 
  - http://trac.sa-mp.nl/lvp/ticket/1407
- Effect during a FC fight. 
  - http://trac.sa-mp.nl/lvp/ticket/1408 / http://img15.imageshack.us/img15/7159/kg0z.jpg
- Spectate handler to create an user-friendly environment. 
  -  http://trac.sa-mp.nl/lvp/ticket/1413
- Save players Kills/deaths.
  - At the moment, this resets every time the fight ends or after re-connection.

**Comment by ghost** [comment]
Given that Trac is of course unavailable now, those links are all dead. 

From the point of view of our regular players, I think most of them seem to like the FC as it is right now. I see this feature being used a lot - by admins and players alike. I'm aware of 3 issues right now:
- The warehouse location essentially gives players godmode: https://github.com/LVPlayground/playground/issues/133
- Stats reset, as already mentioned
- Players watching a fightclub match can be teleported to: https://github.com/LVPlayground/playground/issues/137

IMHO, these issues should be fixed first - and next up we should look at pre-defined classes as mentioned.

**Comment by LVPJoe** [comment]
We're very unlikely to address this issue in the foreseeable future. A new issue will be filed if this changes; file a new issue if you feel strongly that this should be reconsidered.
