### ISSUE TITLE
Implement a /q filter

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#242]
/q jokes have been around forever, and they're still fairly common. 

<%Nowini> [16] _name removed_: type /q joke this commands gives you 200000
<%Nuwini> [15] _name removed_:  /q to get 100m
<%Nowoni:%#lvp.echo\* **\* _name removed_ (Id:9) has shown: type /q to get admin (red) to world: 0.

Those are just a few examples, all of which are from different players within the past 7 days. 

People use various methods to do this (i.e. /showmessage) so we should just block it from being used in all commands, in my opinion. 

The benefit is that we don't get new players falling for it (which some do) and involuntarily leaving the server. The disadvantages? I can't really think of any.

An error message such as "Sorry, we don't allow /q messages" or "Error: Quit jokes are not allowed" might be suitable.

**Comment by LVPYassine** [comment]
Fixed and Tested in BETA ! Check this  https://github.com/LVPlayground/playground/pull/243

**Comment by ghost** [comment]
Check this 

Fix Show Message abuse 
https://github.com/LVPlayground/playground/pull/249/commits/9c35b882d1de635947eeb4a2b39860e815102395

added Anti - /q jokes

https://github.com/LVPlayground/playground/pull/246/commits/5dfa8251f20101d2c8fb1a2112f6f01e6950d827

**Comment by ghost** [comment]
Thank you for contributing the /q patch @LVPYassine - as it's working properly I'll go and ahead and close this issue out :)

As for 9c35b88, I do see that Russell has replied, we'll continue to help you out with that PR :)
