### ISSUE TITLE
Implement a /topcash command

### ISSUE THREAD

**Issue by HuracanLVP** [LVPlayground/playground#247]
Function of the command would be to show the current (online only) richest players on the server, would serve as a form of competition since the economical changes.

**Comment by LVPYassine** [comment]
Not need we already have TAB showing this 

money = score

and at the website players online showing

riches to newbies

Yassine

**Comment by HuracanLVP** [comment]
Yassine man, why you chatting shit here for? You approved of the feature in-game, and what harm does it cause? If anything, it encourages competition amongst regulars and keeps people always wanting to be the BEST. Even if those people aren't good at DMing, perhaps they could excel elsewhere, like me, I can't fight for shit but I'm rich asf so it doesn't matter, just allow it please :))

**Comment by RussellLVP** [comment]
The score board displayed on `<tab>` does not include the money in somebody's bank account. I believe that @HuracanLVP wants this command to display both.

Since this is completely trivial to implement once money management moves to JavaScript, I'm completely OK with adding this. It's literally ten lines of code or so for us.

Yassine, please be aware of our Code of Conduct:

https://github.com/LVPlayground/playground/blob/master/CODE_OF_CONDUCT.md

We will always consider all suggestions in a positive way.

**Comment by HuracanLVP** [comment]
so Russell, you will be making a commit and adding this? :>

**Comment by RussellLVP** [comment]
Yes, but not today. This will require some more work, and I don't want to move even more of my focus away from the house system.

For context, we use a certain mechanism for server-sided money that makes money cheating impossible. This entire mechanism should move from one place in our code to another to make it more maintainable in the long-term. When it has been moved, adding this command is simple.

**Comment by HuracanLVP** [comment]
What is the command manager? Is that to do with houses? 
Thanks.

**Comment by RussellLVP** [comment]
Sorry, I mean house system. I have rectified my message.

**Comment by HuracanLVP** [comment]
Ok thanks Russell!

**Comment by ghost** [comment]
i don't break any rules in COC :)

i just says what i think :)

**Comment by xhoogland** [comment]
Although this is not really the place to discuss that, you certainly did. In the CoC we ask you to always be positive in comments to keep the community healthy and happy.

By saying "Not need" you immediately reject his proposal which is totally not positive.

@HuracanLVP: Perhaps an idea to make a top 3 out of it? In case of afk'ing players you can focus on the first non-afk player. ;P

**Comment by HuracanLVP** [comment]
xhoogland, decent suggestion however I guess this would make a simple 10 line code in fact longer. I'm hoping we can keep it simple and just show who is the richest, a combination of wallet and bank cash. With this, maybe, later there will be a chance to offer rewards and such for richest players and other stats which may come from statistical analysis.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
