### ISSUE TITLE
Implement a Anti-afk abuse :)

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#248]
Some Players Abuse afk for earn hours :) 

and that not acceptable so i suggest to add anti-afk abuse with timer 10 mins 

MAX AFK == 10 mins :]

Thanks

Yassine

**Comment by xhoogland** [comment]
Did you perhaps already went in-game to buy 1 property, stand on the ship for 1 hour and checked your statistics after that? :+

**Comment by ghost** [comment]
Yeah xD

Ask Reanna She pro on this

**Comment by mblokker** [comment]
Hi Yassine, thank you for your suggestion.

We already have a penalty system in place to avoid 'AFK abuse', you can find it here: https://github.com/LVPlayground/playground/blob/656a90ebfa1d03b9997969ccdf0b1c92ad522894/pawn/Entities/Players/PlayerIdlePenalty.pwn

If you have bugs to report about this feature, we will gladly read them in your next ticket, together with information about how to reproduce the bug(s) and such.

May I ask you that your suggestions should include some more information concerning the suggested feature? In this case, it would be good to know whether the person being AFK has his game minimized or not, and what you exactly mean with 'MAX AFK == 10 mins :]'. After 10 mins someone needs to be kicked? Or do we deduct the remaining AFK-hours from their session time? Remarks like 'Yeah xD - Ask Reanna She pro on this' are not useful at all.

Regards,
cake
