### ISSUE TITLE
Website adjustments. 

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#25]
1. ​https://sa-mp.nl/online/index.html
   In the left hand column, there's some text which reads 'Advertisement'. Though, there's no advertisement (tried Chrome and Firefox, with no plugins enabled). When looking at the source, I see: . It may be like that on purpose, though it looks a little strange. If we choose to remove it, it can be be replaced by the LVP Chrome Extension widget which appears on other pages, e.g: ​https://sa-mp.nl/about/index.html . Here is a screenshot: ​http://i.imgur.com/4YqLV2k.png
2. We don't mention all of the VIP benefits on: ​https://sa-mp.nl/about/donations.html . According to the Nuwani2 Documentation in the crew forum, VIPs with Voice also have !getid, !getname, !regular and !vip. Whilst I'm not sure these four commands will increase the likeliness of someone donating, I can't see any reason for not mentioning them.
3. Profile settings does not have any content. This option is available when logged in at sa-mp.nl and then clicking on 'Profile settings'. Screenshot: ​http://i.imgur.com/OuH22NK.png
4. ​https://sa-mp.nl/about/colorlist.html
   VIPs/Crew can use /my color in-game nowadays to permanently set their color. If I re-call correctly, permanent color changes used to be manual (as in, a crew member had to do them). The colors listed on that page are also outdated. 
5. Differentiate between inactive and active crew.
   - Extra field in the database?
     http://sa-mp.nl/players/staff-members.html (full crew list) -> http://sa-mp.nl/about/staff.html. (active members).
   - Replace the full crew list on that page with this https://sa-mp.nl/about/staff.html and move the full list some place else on the website?

**Comment by ghost** [comment]
Note:
As for nr.2, make sure the new vip command "/set time" is also listed under the donation page once this is implemented. 
Don't have access to web so can't mess around see if I can add them.

**Comment by ghost** [comment]
1, 2: complete

3: I'm not sure about this one, perhaps looking at the errors logs on the web server will shed some light.

4: I propose that we remove this page. The colour list is outdated and whilst we could potentially update it, I don't see the point in doing so. VIPs/Crew can easily use the /my color command ingame to save a colour of their choice permanently.

5: I propose we make a start on updating staff.html (e.g. removing Kase, MacSto, as they're now Veterans, Beaner and striker as they're now Former Crew)

**Comment by xhoogland** [comment]
dgrp or RussellLVP, would it be possible to get some hook or access to the LVP website-source? That way, everyone of us can fix issues on it.

**Comment by ghost** [comment]
3) I've hidden the links to this page, as it never worked to begin with, according to Russell

4) Once again, hidden the links to this page, but retained direct access (https://sa-mp.nl/about/colorlist.html) for historical purposes.

5) After a discussion with Russell, he raised the valid point that former crew and management/veterans retain their rights on IRC, In-game, etc. As such, we may as well keep this section of the website as it is. 

Closing this out, but by all means, if anyone disagrees or has further suggestions, feel free to re-open this case.
