### ISSUE TITLE
Casino Bug

### ISSUE THREAD

**Issue by HolsjeLVP** [LVPlayground/playground#250]
When you win your bet you will get your winning, e.g. 5000 every second.
(Same goes for losing)

Makes people get them 2bill in the new economy quick :o: 

Steps to reproduce:
1. Get into a casino.
2. Make a bet at the spinning wheel

**Comment by mblokker** [comment]
Thanks Holsje, people were actively abusing this.

**Comment by mblokker** [comment]
After: https://github.com/LVPlayground/playground/commit/74a268dde7fd3ac5c082c7b75684f0d09055a587, when the casino withdraws or gives money, my cash is reset to the amount I had before withdrawal or payout.

**Comment by mblokker** [comment]
Seems to be fixed in beta.
