### ISSUE TITLE
Reactions Test

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#251]
after the new economy system i think Dev's forgot change this

**\* First player to type BUNQDKTB wins $10.000!

but what i noticed players earn just 5 K

**Comment by xhoogland** [comment]
Woops, seems like we missed something indeed! :O According to a commit from the 10th of august https://github.com/LVPlayground/playground/commit/e27207cf3f7921ef15cb2d703f99ca045b9aafcc it is fixed, although I am not sure it this is live yet. We are using the live reload-feature a lot which doesn't support pawn and some specific javascript-features.

It should probably be live with a next restart, thank you!
