### ISSUE TITLE
Spawn Money Bug

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#255]
The default spawnmoney amount is $10,000 as of the recent Economy update.

I was testing a few things out as a guest, and I was informed that my spawnmoney was $100,000 as per /my spawnmoney. However, when I spawned, I did in-fact have $10,000. I tried doing /kill, same result. As such it seems that the output of /my spawnmoney is wrong.

Another issue is that it's possible to use /my spawnmoney to set amounts that you don't even have. I was able to use /my spawnmoney 10000000 and receive confirmation that it had been changed. Fortunately the bug isn't too serious as I didn't get that amount after killing myself. 
![untitled](https://cloud.githubusercontent.com/assets/15123289/17836366/a17c00ec-6787-11e6-92ee-ff30ceba79e1.png)

**Comment by mblokker** [comment]
Wrong button :)
