### ISSUE TITLE
Audio Stream Messages

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#256]
Whenever entering a vehicle or going to a location where there's a radio (i.e the ship, ammu-nation), you'll be presented with an Audio stream message assuming you have the /radio setting enabled. In my eyes, it doesn't really add any value - it's just text for the sake of text.

![untitled](https://cloud.githubusercontent.com/assets/15123289/17837504/ede9c8ae-67ac-11e6-8c4b-8133fdd9382d.png)

What do people think about removing it?

**Comment by mblokker** [comment]
I believe it's meant for people who want to know the URL in order to listen to LVP Radio using 3rd party software.

There is a /audiomsg command that should turn this off.

**Comment by xhoogland** [comment]
To make this even worse: It seems like we do not produce this code and SA-MP sends it by itself.
Kinda sucks imo!

**Comment by RussellLVP** [comment]
Yeah, we can't fix this.
