### ISSUE TITLE
Jailing upon reconnect

### ISSUE THREAD

**Issue by mblokker** [LVPlayground/playground#258]
Apparently this is broken. If a player is jailed, and he disconnects with remaining jail time, upon reconnection he is not jailed. However, the jail time is still listed under /jailed.

Thanks to ssundee for the report.

**Comment by xhoogland** [comment]
For the assignee: Please also check for mutes, in my opinion this should also be remembered.

**Comment by mblokker** [comment]
Can't reproduce.
