### ISSUE TITLE
Finish the Forum Theme. 

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#26]
The Forum theme needs to be finished so it can be used. This project is on hold for quite sometime now and would be a great improvement.

**Forum Features:**
- 32x32 icons of Facebook/Twitter/Youtube channel

**Known Bugs:**
- The user box at the top of the page shows overlapping text and images when using Safari/Firefox on desktop or iOS.
  - http://i62.tinypic.com/hve7pd.png
- The countdown/bullet code etc is jumbled together.
  - http://i61.tinypic.com/15whq1y.png

**Comment by ghost** [comment]
Now that we've migrated to MyBB, the old integration is void (although we can of course use it as a styling base). What do people think? Should we integrate the forum with our website, or keep it as it is?

**Comment by TFarish** [comment]
We'll lose resolution if it's embedded and has the triple column layout. The layout already isn't really mobile friendly so making it embedded into the website wouldn't help this.. It would be easier if you only had one account mind for both the forum and the game that way people would have to make a game account and then they would get a forum account.

**Comment by debuggest3** [comment]
Agreed @ one account. Now that we have more stable forum software, we can have a look at this.

Regarding this issue, I'm closing this as we will be tweaking the current forum theme as we go along. If there are issues with the current theme, please report them in a new issue. Thank you.
