### ISSUE TITLE
Bugged markers

### ISSUE THREAD

**Issue by xhoogland** [LVPlayground/playground#260]
Note1 = For all markers: please reset the camera of the player, else this causes some weirdness on several places.

Bug 1a: marker SPECIAL1 is weird looking from N to Z
Bug 1b: Do we even want this marker
Bug 1c: Perhaps keep this world 0
Bug 2: Marker SPECIAL2 seems useless
Bug 3: SPECIAL3 is ok, /bugged it though due to placed back at wrong side (note1)
Bug 4: SPECIAL4 seems a copy of SPECIAL3
Bug 5: AMMUN1 /bugged (note1)

**Comment by TotalEpicFailure** [comment]
Bug 6: No red marker in food places (Cluckin' Bell, Burger Shot, etc.), meaning no food items can be bought.
Bug 7: When entering interiors, players cannot talk to one another due to differing /worlds.

**Comment by xhoogland** [comment]
perhaps extra forward at return-marker CASINO2

**Comment by TotalEpicFailure** [comment]
"WUZIBET" marker is slightly higher than normal, resulting in small "jump landing" animation. Applies to both entry and return.

--Also, what is the deal with the interior of "TSDINER"? Just an empty space.-- @xhoogland This is your reminder to fix this particular issue (placing large object near the door) and to find the old Login Room ;+

**Comment by xhoogland** [comment]
It seems like the casino's don't work completely at all either. :X
Thanks @TotalEpicFailure for noticing!

Another interesting thingie we can add: A marker for the SF Police Station! Rockstar simply forgot this at the release. ;P

**Comment by xhoogland** [comment]
For all the FDREST1-interiors, can we please move the marker to the stairs. I do need to make stuff solid though. :+
148 was my last, I will continue tomorrow.

**Comment by TotalEpicFailure** [comment]
@xhoogland The marker that normally appears in LV Main Bank for players to upgrade accounts is now missing. Figured it belonged here.

**Comment by xhoogland** [comment]
Bug 1 to 5: Those seem to be handled.
Bug 6: I am not sure what to do with those 2, I think it requires some work. @RussellLVP?
Bug 7: This is already fixed by @RussellLVP.
WUZIBET: Since this is going to be a house, this marker could (n)ever become active. In case we are going to use it we have this ticket to remind us. :)
PAPER (planning dep/main bank/upgrade account): The red marker INSIDE the building has left the building, players don't see it.
TSDINER: 681 -455 -25 to fix.

For the old loginroom: 940.922, -18.307, 1000.18

**Comment by xhoogland** [comment]
DRIVES2 marker inside missing when you are going inside the LS drive school. Originally you can walk into it and walk to the marker in the back to enter the learning area.

Soon I'll do a commit to correct some changes in rotation!

**Comment by xhoogland** [comment]
@RussellLVP, could you perhaps take a look into the problems with properties/property-icons and markers/pick-ups (main bank) not showing up in interiors?

**Comment by mblokker** [comment]
Is this ticket done?

**Comment by xhoogland** [comment]
Did you check the  main bank-marker? :)

Edit: Yes you did! <3
