### ISSUE TITLE
Weaponry in Minigames

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#261]
Upon signing up for any minigame (haven't tried with every single one, but it seems very easy to duplicate), a player can walk into Ammu-Nation, go to the weapon menu, and wait until they are teleported into the game to buy whatever weapon they desire.

**Comment by xhoogland** [comment]
Self-note: https://github.com/LVPlayground/playground/commit/4e03a5473d54e7351ff6d48ea7a210865c87fa0a

**Comment by RussellLVP** [comment]
@xhoogland Are you planning to work on this? Tentatively assigning.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
