### ISSUE TITLE
Spawning vehicles inside the LV stadium.

### ISSUE THREAD

**Issue by BigShem** [LVPlayground/playground#263]
Hello there, I was randomly cruising with some players, We stopped near to the LV stadium and I decided to cruise inside the arena, after getting in, I couldn't spawn any vehicles, it says I need to be in /world 0, when I used the /world 0 command it says that I have to use it outside the interior. Maybe we can move the two stadium interiors to /world 0?

-The two interiors from the outside : http://imgur.com/a/GR0N7

-First interior : http://imgur.com/a/u41Qp

-Second interior : http://imgur.com/a/K8qDR

**Comment by RussellLVP** [comment]
This has been fixed with the following changes:

https://github.com/LVPlayground/playground/commit/2d68d8da02436b1820791410ee95b1fd482fffab
https://github.com/LVPlayground/playground/commit/d1eb174bcffa10d2282d9e49b206b5392582d1d6

Thank you for your report, Shem! :)
