### ISSUE TITLE
Basketball minigame.

### ISSUE THREAD

**Issue by BigShem** [LVPlayground/playground#264]
I had the idea of some cool basketball minigame, like the one in story mode, so I googled it and I found this : https://www.youtube.com/watch?v=bQOE16s1wkk or again this : https://www.youtube.com/watch?v=qzk04bHQPP0 . I know it looks hard to script, I just wanted to know if we can't simply transfer the minigame from story mode to samp and try to fix it for 2 players or 4 players matches, it doesn't need to be a whole match just some 2pts and 3pts, and maybe we could have a list ranking players who scored most points. It would be cool to 1 vs 1 someone in most points scored in basket ball.

**Comment by mblokker** [comment]
While this is a great idea (I love it!), this is currently out of our league due to focus on Houses and Gangs.
