### ISSUE TITLE
Players should receive a refund when selling their house

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#268]
When selling their house to the bank, players should receive a percentage-based refund based on the current value of the house.

I'm not sure what this percentage should be. I'm erring to a number between 50% and 75% to make it easier for people to move their house, but since we intend this to be a money sink we might want to start off more conservatively than that.

**Comment by LVPJoe** [comment]
Refund % increase over time, start at 35% then 5% for every week perhaps, to cap at 70%?

**Comment by RussellLVP** [comment]
Yeah, I like that. Discourages people from switching houses too often.
