### ISSUE TITLE
Introduce First Join Experience  

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#27]
One of the issues LVP faces, in my opinion, is that players join, and leave too quickly. The reason, I believe, is because they don't understand the many features we have to offer.

To demonstrate, I joined as a guest, clicked the accept/ok button that's presented when first joining (which displays registration benefits) and here's a screenshot of what I see: ​http://i.imgur.com/YaraKsf.jpg

Here's my thoughts, assuming I'm brand new to SA:MP and LVP:
-  I'm alive, my player is on the map
-  What should I do now?
-  I'll run around for a bit until I find a car
-   I'll get in the car, drive around
-   Someone comes along, shoots me, I die
-   I'm back to where I was when I joined, back on my feet
-   Someone comes along, shoots me, I die
-   Not sure what to do now, so I'll quit 

LVP has tonnes of excellent features.
- Races / deathmatch.
- Minigames / jumps. 
- Properties / Derbies. 

Whilst some of them are a bit broken (which I'm doing my best to identify and report in tickets) we need to get players to better connect with those features, because once they do, they will likely be hooked. I know I was (and still am!).

**The fix, in my opinion, is to better promote our offering.**

As soon as guests (and maybe logged in players too) join and accept the registration dialog, I propose that the in-game chat is wiped (the equivalent to the admin command /clear) and replaced with something like this:

​http://i.imgur.com/k2RzqEt.jpg

Clearly, that art-work is not the best, though it does at least give players a prompt and place to start. Right now, there's not really anything like that. I've seen other servers use very similar formats (e.g. clear the chat when joining, display a text like the above).

**Comment by ghost** [comment]
by Russell

I like the idea of introducing a First Join Experience, but I would do so using dialogs of some kind. The crux is that we need to be concise in what we describe, and give them some concrete things to do.

**Comment by ghost** [comment]
by striker

 The idea is great because we lack of promoting our features and services. It's a must to inform players about our features and services in a decent colour that automatically grabs their attention. It would be a plus next to that "First Join Experience". Or just have them go through dialogs(/help) which I think is kind of too much.

You can do this by using a similar system like Gunther's messages. Or check the players activity, if players enters a vehicle, the players will automatically receives a message that inform them about races/jumps/derbies. If the player is shooting people, inform them about /dms (miniguns, rockets) and so on. At least every 5 minutes or so.

However I think, seeing how most of the players moved to RP servers, our features are quite normal. We limit their ways to make money and plus the player may not like exporting vehicles or play minigames for a little bit of money. So I believe to give players less chances of quitting we should introduce also more features like you have tons in the singleplayer. I be happy to make a ticket if you guys would like me to go into details.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
