### ISSUE TITLE
A "reset weapons" command for players

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#276]
A few players tend to prefer having only the spawn-weapons they themselves purchase at Ammu-Nation in lieu of the ones automatically given to them by the server. I'm proposing, instead of them requesting a reset from admins, we give them access to a command that does exactly that. 

I've been informed that there used to be a command that did this, "/dropweapons" (or something similar). If it was removed for a good reason, then close me! :+

**Comment by BigShem** [comment]
It would be cool to have a /dropweapons to actually drop the weapons and others can take it. So gang members can share bullets too.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
