### ISSUE TITLE
Implement an in-game Registration System

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#28]
https://forum.sa-mp.nl/index.php?topic=33805.0

by Matthias

**LVP never had an in-game registration, the reason why is because we want people to have a valid email address linked to their account. This email address is used for disputes, password resets, import announcements, etc. We're looking to changing this now. We hope this will lower the barrier for new players on LVP.**

So, we're looking for a way to allow in-game registration while still have users with a validated email address. This is where you come in. We've come up with some ideas of ourselves:
- Players can only deposit a certain amount of money before they have to validate their email address.
-  Players can only log in x times before they have to validate their email address.
-  Have some sort of information message on the screen that becomes increasingly annoying as long as they haven't validated their email address.
-  Players need to validate their email address before they become a regular.

**Comment by LVPJoe** [comment]
We're very unlikely to address this issue in the foreseeable future. A new issue will be filed if this changes; file a new issue if you feel strongly that this should be reconsidered.
