### ISSUE TITLE
Gangbase 2.0

### ISSUE THREAD

**Issue by mblokker** [LVPlayground/playground#282]
A moving ship, in the waters around LV.

**Comment by TotalEpicFailure** [comment]
DETAILS TO COME?! :laughing:

**Comment by xhoogland** [comment]
Having ideas for the new ship, will be doing stuff on that after finishing killtime in javascript. ;)

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
