### ISSUE TITLE
Move communication features to JavaScript

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#283]
We have various smaller features that enable players to communicate with each other which should be implemented in JavaScript. Doing so would make them more maintainable, and would allow us to employ more advanced algorithms in, for example, spam detection.
- [ ] Administrator chat (@_message_)
- [ ] Regular chat (#_message_)
- [X] Gang chat (_!message_)
- [ ] A basic spam filter (replacing the [SpamTracker](https://github.com/LVPlayground/playground/blob/master/pawn/Features/Communication/SpamTracker.pwn))
- [ ] Private messages (replacing the [PrivateMessagingManager](https://github.com/LVPlayground/playground/blob/master/pawn/Features/Gameplay/Communication/PrivateMessagingManager.pwn))
- [ ] Telephone system (replacing the [CallManager](https://github.com/LVPlayground/playground/blob/master/pawn/Features/Gameplay/Communication/CallManager.pwn))
- [ ] The ability to mute players (replacing the [MuteManager](https://github.com/LVPlayground/playground/blob/master/pawn/Features/Gameplay/Commands/Mute/MuteManager.pwn))

Most of these should be fairly straightforward to implement, and are good starter bugs. In some cases (notably the `/call` command) we should ask ourselves if we want to keep it.

**Comment by ghost** [comment]
A suggestion I think will be helpful as well: https://github.com/LVPlayground/playground/issues/136

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
