### ISSUE TITLE
Merchant vehicle price

### ISSUE THREAD

**Issue by Lash** [LVPlayground/playground#284]
So I believe the merchant vehicle delivery should pay more as it is around 1k for a delivery. Compared to exporting vehicles which pays up to 18k per vehicle.

**Comment by TotalEpicFailure** [comment]
Or, rather, should we lower the export income to allow for the change in economy? (I am in agreement with Lash, though, in that they should be fairly similar in payout.)

**Comment by RussellLVP** [comment]
The merchant feature is _really_ unpopular, so increasing the reward makes a lot of sense. It's also harder than exporting a vehicle, since the distances tend to be larger.

For reference, the money awarded for exporting a vehicle is between $6,767 and $18,240.
