### ISSUE TITLE
/my is case sensitive

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#290]
/my commands are case sensitive. I.e. they only work with lowercase.

/p, on the other hand, and every other command I've tried, works with both upper and lowercase.

Could this be adjusted so that /my works with upper and lowercase?

**Comment by RussellLVP** [comment]
Actually, I think that you'll find that commands such as `/p [id] messagelevel` are case sensitive too. The reason for this is that our command processor works based on hashes of the sub-command, as opposed to conventional string matching.

Nonetheless, it should be fairly easy to fix this for both `/p` and `/my`, so let me give that a shot.
