### ISSUE TITLE
/watch and helicopters!

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#291]
So it seems to me that helicopters do not agree with spectating. Shortly after take-off (or randomly if the player is already flying when you happen to /watch them), I find each and every time my game freezes up requiring a forced process end.

I am uncertain what the cause could be, but this is definitely worth looking into.

**Comment by mblokker** [comment]
This has never happend to me before, so I would not know what to look for. Besides, chances are high this is related to your client/PC setup. You could try this: https://github.com/Whitetigerswt/gtasa_crashfix/releases/tag/v2.4
