### ISSUE TITLE
Debt forgiveness through lame-kill redemption

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#292]
Because of how confusing this report will be if I decide to use a paragraph to explain, I'll instead use the steps...
1. Player A borrows money from the bank
2. Player A waits until their money is in the negative (X)
3. Player A commits a drive-by/heli-kill/lame-kill on Player B
4. Player B decides to punish Player A by stealing their money
5. Player A has their negative cash set to $0 and Player B has their funds subtracted by X.

**Comment by TotalEpicFailure** [comment]
https://imgur.com/a/x18g1

**Comment by mblokker** [comment]
Wow, this is actually something I'd abuse! Damnit TEF!
