### ISSUE TITLE
Interior bug abuse messages

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#293]
First, let me say that I do like this message system; however, the following happened simply because someone was throwing grenades within the interior of an Ammu-Nation...

> [1:41:46p] _%Nowoni:%#lvp.echo_ **\* Possible interior bug abuser: LwveMike (Id:22) damaged Sorinutzuk (Id:).
> [1:41:47p] _%Nuwuni:%#lvp.echo_ **\* Possible interior bug abuser: LwveMike (Id:22) damaged Sorinutzuk (Id:).
> [1:41:53p] _%Nowoni:%#lvp.echo_ **\* Possible interior bug abuser: LwveMike (Id:22) damaged Sorinutzuk (Id:).
> [1:41:57p] _%Nuweni:%#lvp.echo_ **\* Possible interior bug abuser: LwveMike (Id:22) damaged Sorinutzuk (Id:).
1. Is it at all possible to fix how the second player never has an ID attached?
2. Is it possible to fix how the messages show up when someone throws a grenade inside? (Note: This message does not pop open when bullets are fired, suggesting something particular about explosions.)

**Comment by RussellLVP** [comment]
I fixed (1).

I don't understand what you mean by (2). This message is only issued when a player reports having taken damage as a consequence of an explosion, which grenades are part of. What would you change in the message?
