### ISSUE TITLE
Weapons within interiors

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#294]
Years ago, weapons were simply disabled when a player went inside. I believe it'd be worthwhile to bring back this implementation, or perhaps a temporary "freeze" on the player when a shot is fired (whichever is easier). Why? Because spraying/grenades can force a player from an interior to an exterior, allowing them to be murdered in horrendous, cold-blooded fashion.

**Comment by TotalEpicFailure** [comment]
Alternatively...

> [11:02:41a] < cake > turn the weapon into a dildo!
> [11:03:13a] <[BB]Diablo> with a tef message
> [11:03:17a] <[BB]Diablo> saying have fun

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
