### ISSUE TITLE
Enable players to break in to a house

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#299]
We could give players 3 chances to guess a random two-digit code, like a lock. If they guess correctly we allow them to enter a house they otherwise wouldn't have access to.

Then they're inside. What follows?

**Comment by TotalEpicFailure** [comment]
Could there be security systems at play here as well? There are tickets for items and pickups that could be lying about for the "what follows" in a reward sense, but what if a really paranoid player wanted to protect themselves from such a break-in?

**Comment by BigShem** [comment]
Maybe an "alarm" that would alert the clan mates and friends of the victim so they can come and deffend his house if they want to?
