### ISSUE TITLE
/house goto — limitations, restrictions, and notifications

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#300]
Some concerns and possible solutions:
1. `/house goto` should have a time limit for use, in much the same way `/tp` does currently.
2. There should also be a form of payment required to use the command—perhaps similar to the `/taxi` fares? Maybe discounted?
3. Finally, and most importantly, there should be an admin notice when players use this command so that crew can keep track of when it is being utilized (prevention of abuse, cheating, etc.).

**Comment by RussellLVP** [comment]
All done, modulo the payment. We'll revisit that in due course.
