### ISSUE TITLE
House money safe

### ISSUE THREAD

**Issue by Lash** [LVPlayground/playground#302]
How about we enable players to put money inside their houses, since the bank allows up to 2bil and you can put like half a bilion in your house.

**Comment by RussellLVP** [comment]
Thank you for the suggestion! This actually has been suggested multiple times now, but I do wonder what the added value is over just storing it in your bank account? Getting two billion dollars is actually really hard these days.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
