### ISSUE TITLE
Houses Suggestions

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#303]
Hello

i just want to suggest :

-Add a Message (like memo) in the house
-set pos in skin request class in the pv house (means he choose skin in he house) 
-Add a 3D Label in The PV Cars
-add the health and Armour and weapons in the house
-create some houses for VIP's (somethings not normally like VIP House but a private one )

-enable to VIP's to create any Private Car and save it in House (For Reg Players infernus)

-add a houses for admins (Mansion or smth)

-add a cmd for kick player from the house without kill him (+Admin)

That all !!

Thanks

Yassine

**Comment by mblokker** [comment]
Your ticket contains a lot of suggestions we already have tickets for. Would you mind editing your ticket?

**Comment by ghost** [comment]
like ?

**Comment by mblokker** [comment]
Well, start with all the tickets that are labelled 'houses': https://github.com/LVPlayground/playground/issues?q=is%3Aopen+is%3Aissue+label%3Ahouses
