### ISSUE TITLE
Gangs Zones 1.0

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#304]
Hello !!

i suggest to create a cmds for clans be able to create the zones for them that will be fun 

that will give u 

some Fights for zones a WARS a lots of wars for claim the zone etc 
the players love this And that will be goid for LVP bcs i think no one in 0.3.7 use a gang zones yet

**Comment by RussellLVP** [comment]
Hi Yassine,

Please have a look through the [existing issues](https://github.com/LVPlayground/playground/issues), because this [has been tracked](https://github.com/LVPlayground/playground/issues/279) already.

Thanks,
Russell
