### ISSUE TITLE
Stunts Zones 1.0

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#305]
Hello !!

i suggest to create some objects in Las Venturas Airport in a virtuel World ofc and close the Entry's with a big ball 

and do a cmd for the player join the stunt zone like 

/stuntz = Teleport player + Disarm + God Mod + Infernus God Mod

Thanks 

Yassine

**Comment by mblokker** [comment]
We have something exactly like this: jumps

**Comment by LVPYassine** [comment]
Jump Bored i said a New Stunts Map
