### ISSUE TITLE
Clan Wars 1.0

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#307]
Hello !! 

i suggest to add a Minigame When clans be able to play fair without (fetch and refil
...) and add some places for spec's (players can watch the CW) that all in a virtuel World ofc

Thanks 

Yassine

**Comment by leaty** [comment]
I've built this type of "minigame" before (long ago) for my old clan server (tHO). It worked exceptionally well.

Two types exist:
Practice Clanwar (pcw)
Clanwar (cw) - stores statistics on wins to a leaderboard for all clans.

Different modes also exist:
The first mode is - first team to kill a specified amount (respawn ON).
The other is just basically the last team standing.

Weaponsets are choosable of course and it had multiple locations with invisible boundaries, such as the big baseball field. I believe if I remember correctly that it also had a watch function where you can toggle between all players.

If any dev on LVP wants some of that source code for LVP just message me on IRC.

**Comment by ghost** [comment]
Hi leaty 

You can just fork this gamemode using You github acc and edit it add the clan war minigame 
and create a pull request

Notice : this gamemode is very Complied

Thanks

LikeMrYassine :D

**Comment by leaty** [comment]
I would but I don't have time to work on LVP myself.

**Comment by ghost** [comment]
hmm

**Comment by ghost** [comment]
send me link of pastebin in this email --> saplayground@Gmail.com

**Comment by ghost** [comment]
i will create a pull request :)

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
