### ISSUE TITLE
Stunts Zones 1.0

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#308]
Hello !!

i suggest to create some objects in Las Venturas Airport in a virtuel World ofc and close the Entry's with a big ball

and do a cmd for the player join the stunt zone like

/stuntz = Teleport player + Disarm + God Mod + Infernus God Mod

***Notice : Jumps Bored i think no one still use it

Thanks

Yassine

**Comment by mblokker** [comment]
Duplicate of https://github.com/LVPlayground/playground/issues/305

**Comment by LVPYassine** [comment]
mblokker Please Read CoC
