### ISSUE TITLE
/me formatting in #LVP.Echo

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#310]
It seems that the _/me [text]_ command available to players in-game isn't formatting properly in #LVP.Echo (though I should note, it works flawlessly in-game).

**Example:** 
<%Nowoni> [me]13 Lashzilla reporting out.

I tried !reloadformat, wondering if it may have been related to a recent commit, however that didn't help unfortunately.

**Comment by RussellLVP** [comment]
OMG @mblokker Y DID U BREAK DIS 4bb2ecd

Anyhow simple fix :) Thanks for the report!
