### ISSUE TITLE
Ghost Vehicle Bug

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#311]
If you're sitting as a passenger in a vehicle and use one of the unlockable vehicle commands (i.e. /inf, /sul, /nrg, etc) you'll be given your chosen vehicle and can drive it, but other players won't see anyone in the driver's seat. 

For example I can type /nrg whilst being a passenger, and it will look like the NRG has no driver. 

I hope this makes sense - if not I'd be happy to demonstrate in-game.

**Comment by mblokker** [comment]
http://wiki.sa-mp.com/wiki/PutPlayerInVehicle

**Comment by RussellLVP** [comment]
This will be fixed now that vehicles are controlled by JavaScript. Please open a new issue if it persists after the LVP 10.3 release.
