### ISSUE TITLE
Lower the bank limits

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#313]
We somehow still have players with two billion dollars on their accounts. This maps to about 40 billion dollars prior to the economic changes, which is absolutely ridiculous.

The amount of money a player is able to store shouldn't be much higher than the most expensive house. Maybe twice. So we should consider lowing the limit to $500M for now. WDYT?

**Comment by TotalEpicFailure** [comment]
$500M seems fair, seconded. In conjunction with the house safe possibilities, this is more than enough.

**Comment by mblokker** [comment]
Agreed.
