### ISSUE TITLE
House auctions

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#314]
When a player hasn't been on Las Venturas Playground for a certain amount of time, we should free their house up for auction.

Any player is able to put in a bid, as long as it's higher than a minimum amount (40% of new value?). Other players are able to make bids as well. 24 hours after a bid stands, the house will be sold.

This probably should only affect the _location_, not the _house_— we'll want to retain the ability to re-associate somebody's house with a new location after they return from an extended leave.

Credits to FateTrip for this fantastic idea!

**Comment by HopperLVP** [comment]
Yes Great Idea , Btw If Someone Win The auction then The money will be Transfer to the Players Account who have that house . And One more Question If He WIN that Auction The House will automatically The Players to win or He need to pay some extra money for that house .

**Comment by RussellLVP** [comment]
Yes, the auction's gain will go to the player who's losing their house in full. (Providing their bank account allows.)

The auction's winner will get the location with the same interior, but stripped of the old owner's customizations. As such, we need to enable "viewings" whilst an auction is in progress.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
