### ISSUE TITLE
Should we create a trailer park just outside of LV?

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#315]
I'd love to get opinions about this one.

Consider https://sa-mp.nl/tools/visualize-map/

Much of the land within Las Venturas will be too expensive for new players. However, in the stretch of desert just west of the city, we could build a trailer park with a bunch of locations. Joe's spreadsheet tells me that houses in that area will start at $502,683, as opposed to $25,660,007 for locations within LV itself.

@xhoogland previously had a more sophisticated idea about creating an apartment complex with all sorts of bells, whistles and custom pricing. This would be a significant simplification of that idea, so I'd especially like to get his opinion.

**Comment by TotalEpicFailure** [comment]
I love it, personally. I think it really brings together the idea of a "first step" that @xhoogland had in mind while also maintaining a "work smarter, not harder" mentality.

**Comment by xhoogland** [comment]
👍
