### ISSUE TITLE
BagofCash ISSUES

### ISSUE THREAD

**Issue by HopperLVP** [LVPlayground/playground#316]
Good Afternoon ,
                             Hello , Today This Bagofcash ISSUES Came To my notice and many Other Players Too
Because Of New House System interior Are Bugged , So We Can Remove the Bagofcash Place in interior Location eg: Learn To Drive , Ocean 11 etc  .

**Comment by RussellLVP** [comment]
Didn't @mblokker fix this? Should be fairly easy.

**Comment by mblokker** [comment]
Yup: https://github.com/LVPlayground/playground/commit/917d951a45509cb6c454972f4122da908e3f80de

**Comment by xhoogland** [comment]
Partially though, since afaik there are still a few locations in house-interiors. Not all are accessible at this moment.

**Comment by debuggest3** [comment]
Which ones?

**Comment by mblokker** [comment]
That's because the fix ain't live yet?

**Comment by xhoogland** [comment]
Example I have quickly is one of the burglar house-interior. There is one in it which is not reachable.
