### ISSUE TITLE
Annouces Race

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#317]
Hey i just wanna disable the races annonces temp for The Event 

for evading the annoying drom new players 

i can do it ? i will create a PR soon if management agree

**Comment by RussellLVP** [comment]
1. Which race announcements? The ones asking players to sign up?
2. What do you mean by _The Event_?
3. Why do we want to avoid new players joining races?

Since we disabled vehicle collisions in races, is this really a problem at all?

**Comment by ghost** [comment]
1. Yes This one
2. check the forum (LVP Race Champion)
3. for races be fair bettwen challengers

**Comment by RussellLVP** [comment]
Why do races stop being fair if new people join? As I said, we disabled vehicle collisions so the number of participants has zero effect on the difficulty.

**Comment by TotalEpicFailure** [comment]
Yassine, we already have teams set and it'll be easy to tell who wins what--if another, non-competing member joins, why not just move to whoever won second place? There are easier solutions than coding a temporary disabling of race announces, in my opinion.

**Comment by ghost** [comment]
just disable it Temp after the event re-Enable it

**Comment by RussellLVP** [comment]
If this is sufficiently important for your event then I'm open to disabling them for a day. However, then I do want you to explain **exactly** what you perceive the benefit of this to be.

**Comment by ghost** [comment]
i will post the dates of the event

**Comment by ghost** [comment]
and i just suggest to add a command for this

**Comment by RussellLVP** [comment]
(Note that your justification is still missing.)

**Comment by ghost** [comment]
i just wanna disable it in event days for challengers play fair and noth to annoying them

**Comment by RussellLVP** [comment]
Yes, but Yassine, _why_ is it unfair and annoying?

**Comment by ghost** [comment]
becauser players in The Race want to be  Head vs Head not play with a player not in Event

**Comment by ghost** [comment]
it's unfair because can the new player crash or hit the car of the challenger etc

**Comment by RussellLVP** [comment]
That's where the misunderstanding lies: they _cannot_ crash or hit each other. We've disabled vehicle collisions, so this is not a problem. Right?

**Comment by ghost** [comment]
Yes i think is not

**Comment by RussellLVP** [comment]
Are we OK keeping the messages, then?

**Comment by ghost** [comment]
if u looking keep the message it's good so np keep it :)

**Comment by mblokker** [comment]
Great! Thanks both!
