### ISSUE TITLE
/borrow < 500.000 does not let you borrow more

### ISSUE THREAD

**Issue by xhoogland** [LVPlayground/playground#323]
Somehow there is a bug in /borrow that it doesn't see the amount you borrowed correctly.

If you borrow less than the max, afaik 500.000, then the system sees it that you borrowed that amount instead of what you actually borrow. In that case you can't rent anymore then you already have.

Luckily you still pay the rent over what you actually borrowed. :)

**Comment by mblokker** [comment]
I have a hard time understanding what's wrong. How can I reproduce this?

**Comment by xhoogland** [comment]
/borrow 10.000
/borrow 20.000 and find out that you can't borrow anymore since according to the system you already have borrowed 500.000
