### ISSUE TITLE
/my spawnmoney restrictions

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#324]
Currently, players can set their spawn money between $10,000 and $1,000,000. Why not allow $0 as an option? I remember my own setting used to be $0, and it still is—just without actually working. 

![gta_sa 2016-09-19 06-49-49-17](https://cloud.githubusercontent.com/assets/21077320/18629692/546fa564-7e35-11e6-972e-af167503de96.png)

**Comment by mblokker** [comment]
It has to do with the logic of spawnmoney: every player gets $10.000 free money upon spawning. If you set a custom value of, let's say, $30.000, then $20.000 is taken from your bank and $10.000 is given for free. We can allow values below $10.000, but that actually requires more work than I want to put into this.

My suggestion: set it at $10.000 and enjoy the free money :)
