### ISSUE TITLE
Revisit spawn money?

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#325]
As a suggestion, and with the information given to me in my previous issue (#324), I would like to bring up revisiting the free $10,000 (spawn money) currently given to every player. I feel as though, while a great idea for unregistered players (for fun, wiggle room, etc.), it is not as necessary for registered players. For our economy, this seems counterproductive, and further, could easily turn into abuse (churning of death and banking). I feel it is worth considering strengthening the economy by making spawn money take any specified amount out of a player's bank (including my earlier suggestion of allowing $0 as an entry).

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
