### ISSUE TITLE
Allow v-allow to be given to any player

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#326]
At the moment, if an admin wants to give a player vallow, this message pops up: "Only VIPs should be granted/limited admin vehicle access." I understand that this is a privilege for VIPs, but there should be a possibility of allowing some fun to be had with a regular/friend/pet iguana. If anything, perhaps adding it to `/lvp access` for ease?

Thoughts?

**Comment by RussellLVP** [comment]
`/lvp access` is entirely set up for usage with commands, not arbitrary features. I do think it mkes sense, so we'll have to reconsider that.

**Comment by TotalEpicFailure** [comment]
While I understand your point with regard to the purpose of `/lvp access` (my apologies, I should have realized it was purely commands on my own), were you agreeing with me regarding v-allow permissions in your second sentence?

**Comment by RussellLVP** [comment]
We've removed `vallow` for now. Please file a new issue if this turns out to be a problem.
