### ISSUE TITLE
Always allow players to spawn a number of vehicles

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#330]
Rather than saving this as a feature for players who have collected all spray tags, let's enable basic vehicle spawning for all players.

Proposal:
1. We repurpose the `/v` command entirely.
   - `/v` displays a dialog with the vehicles available for spawning, and how often the player has spawned them. (Ordered in descending order by spawn count.)
   - `/v [id/name]` creates the vehicle immediately, assuming the player can access it.
   - `/v save` continues to be available for administrators, to store it to the database.
   - `/v destroy`, `/v respawn` and so on too.
2. The selection of vehicles increases gradually.
   - Guests can access ±10 bad vehicles. Think Landstalker.
   - Registered players can access ±50 vehicles.
   - Regular players can access ±100 vehicles.
   - More special vehicles will be added at 10, 25, 50 and a 65 spray tags.
   - VIPs may get access to a few other special vehicles, e.g. the RC vehicles.
3. The time-out between vehicle spawns decreases gradually.
   - Guests can spawn a vehicle every 5 minutes.
   - Registered players can spawn a vehicle every 3 minutes.
   - VIPs can spawn a vehicle every 2 minutes.

Does this sound reasonable?

**Comment by HolsjeLVP** [comment]
I would like to suggest that the player does not spawn ON the vehicle.

This so that players still have to actually enter the vehicle like any regular vehicle to prevent abuse

**Comment by RussellLVP** [comment]
That's super annoying. I use `/nrg` all the time to quickly get away.

Instead, let's just hook it up to the same heuristics we use to determine whether someone can teleport, enter interiors, enter houses and so on?

**Comment by HolsjeLVP** [comment]
I do exactly the same, and I love it.
However I can imagine DMers would much prefer the player not to get away that easily. 

It could be a VIP/Regular feature to spawn directly on the vehicle (As we expect VIPs and regulars to know the rules)

**Comment by TotalEpicFailure** [comment]
The point Russell made regarding linking the feature to anti-abuse measures already in place makes perfect sense to me. I love and support this entire idea!

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
