### ISSUE TITLE
Virtual Worlds: An Expansion

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#337]
With overwhelming positivity surrounding the topic on the forum (https://forum.sa-mp.nl/showthread.php?tid=33432), I am creating this ticket in hopes of allowing for customization and saving of virtual worlds. This will include...
1. Allow individual players and gangs to purchase and save virtual worlds
2. Allow certain commands (teleportation, weapons, spawn locations, health, etc.) to be used by the world owner, and for the world owner to set who can use these commands
3. Allow objects to be placed within these worlds to allow for customization and fun
4. Allow for a way to protect or customize entry into the world (a friends list, password, anyone, etc.)—perhaps, in lieu of a number, using `/world [custom word/name]`?
5. To avoid the isolation feeling: An option for the world chat or main chat to be the primary method of speaking—perhaps we bring back `;` (or a different character!) and instead of chatting with regulars, you talk to whichever is the opposite of the main setting?

This boils down the topic to the important bits. Now, I'm certain more thoughts will arise as time progresses, but the above provides a wonderful baseline.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
