### ISSUE TITLE
player.sendMessage doesn't send when msg > 144 chars

### ISSUE THREAD

**Issue by xhoogland** [LVPlayground/playground#338]
@mblokker Fixed this in our pawn-code, but this isn't fixed in our javascript due to the "re"define. This causes messages to not appear when they are longer then 144 characters.

We should wordwrap (like php.net/wordwrap) in javascript and split it up.

**Comment by RussellLVP** [comment]
Why is this a priority? I'm inclined to say the opposite - we should reject such messages instead.

**Comment by xhoogland** [comment]
Well, rejecting is not a solution either. ShowPlayerBox's, popped up in my head, are not always convenient either. The other problem we have is that colors, afaik, do count for the length of 144. Which could make our messages kinda short.

The one last thing I am not sure about is the current place of our messages. Do we actually know players do read them and not missing them. Events where you participate in indirectly should be clearly known and announced.

**Comment by RussellLVP** [comment]
Please explain why you think that rejecting such messages it not a solution. If the message exceeds 144 characters, with or without inline colours, then it's too long.

`ShowPlayerBox` has little to do with this issue, right? Let's focus on `SendClientMessage` and co..

**Comment by RussellLVP** [comment]
I'm going to close this. Please re-open if you feel strongly.

**Comment by xhoogland** [comment]
@RussellLVP
Okay, at least we need consistency between Pawn-code and Js-code regarding sending a message to a player. Right now there is a difference, which should, one way or another, be resolved.

There are definitely cases in which the input would be longer than the output. The question is: what should we do in those cases? Doing what we do now is different in both code-bases. Pawn, due to cake's implementation, splits it up and javascript just shows nothing.

Seeing you like to stick to 144 chars, which is not bad since the communication towards IRC has also some limit, would mean we would need to:
a) Get rid of cake's implementation
or
b) Change cake's implementation into logging every message which we create so we know which messages which would need a change. In javascript this should be taken care of indirectly via tests.

In both cases we need to, imo, notify the player about the message being too long.

**Comment by xhoogland** [comment]
@RussellLVP's opinion is to get rid of the wrapper. I've implemented option B in https://github.com/LVPlayground/playground/commit/6150f2acaeb19f6a0b00d951f96f23bf27b012c2 but left the wrapping temporarily intact! 

Anyhow, in future uses of `SendClientMessage` we should take the limit into account. :)
