### ISSUE TITLE
Auto Ban

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#341]
Hello !!

i just noticed a lots of players get banned by auto ban ( mlti weaps )

**Comment by TotalEpicFailure** [comment]
Not to sound dismissive, Yassine, but what exactly is the bug or suggestion here? Would you kindly elaborate?

**Comment by ghost** [comment]
TEF i means to disable it on LVP 30.1 and re build another one :) and release 30.3

**Comment by TotalEpicFailure** [comment]
Again, could you explain your reasoning?

**Comment by ghost** [comment]
i mean a lots of players get banned by auto ban for no reason and i suggest to re-work that auto ban or fix it

**Comment by debuggest3** [comment]
What makes you think that players are getting wrongfully auto-banned?

**Comment by ghost** [comment]
i lives it :D i get banned one time for muti weapons in joining brief case minigame

**Comment by debuggest3** [comment]
Just because you got banned wrongfully once does not mean the complete system is flawed :)

**Comment by ghost** [comment]
not just me :D DisDark and some guys like Snow Man Snickers Im not first one ;)

**Comment by RussellLVP** [comment]
Let's close this, since there's nothing really actionable here. Fixing this requires much closer integration with the rest of our systems, which isn't available right now.
