### ISSUE TITLE
"Jetpack" ! 

### ISSUE THREAD

**Issue by HopperLVP** [LVPlayground/playground#345]
Hello @GeorgeLVP  @RussellLVP  ,
                                                         As George said in-game that we are working on new feature " /v " . So I am here to know players must also get right to spawn a " Jetpack" with " /jp " command .  Or Not Players So VIP Players can be acesse to this cmd .  

```
                                                                    Thanks . 
```

**Comment by ghost** [comment]
Players can spawn a Jetpack with the /jetpack command assuming one of the following is true:
- An administrator grants that particular player access to use the command (we can grant or revoke it on a per player basis)
- An administrator grants everyone access to use the command

I'm a bit confused on what you're asking in particular. Are you requesting that the functionality is permanently enabled?

**Comment by RussellLVP** [comment]
Yes. That's exactly what he's asking for. I don't think I'm in favor.

**Comment by ghost** [comment]
Likewise. I think we open ourselves up to various problems, along with taking some of the fun out of the game (i.e. getting to hard to reach props with ease). I think we're best to keep it as a "special" feature like it is right now.
