### ISSUE TITLE
/v <model> deletion

### ISSUE THREAD

**Issue by LVPJoe** [LVPlayground/playground#347]
Based on the code, it seems that this function is intended to replace the first car you spawned, provided nobody is in it when you hit car eleven spawned as management, second when twelfth spawned, etc. I observed on the staging server that on the spawn on car 11, all prior 10 cars disappeared instantly. Observed twice over two sessions with different vehicles.

**Comment by LVPJoe** [comment]
As a follow-up, when you create the twelfth car, the eleventh disappears also. Seems once you break 10 it allows no more than one.

**Comment by RussellLVP** [comment]
Fixed by https://github.com/LVPlayground/playground/commit/38d0881d36371fd6bb9a2d22d669cc25e5fa4129, thanks!
