### ISSUE TITLE
Wrongly assumed to be in the VIP room after a minigame

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#349]
You can start /minigames example /minigun, When you win or /leave the game. you will be out of VIP room. BUT you cant do any commands now
because it says you are inside VIP room still. Even in ship will say u in vip room.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
