### ISSUE TITLE
Car Bomb New Spawned cars

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#351]
Arm Detonation Bomb in the Inferno close to the Ship. Make it restart being close to the ship. the bomb wont dissapear from the car now until i detonate it. People that go to save their money die in fact.

**Comment by RussellLVP** [comment]
This is the same issue as #360. Thank you for the report!

**Comment by RussellLVP** [comment]
Fixed by https://github.com/LVPlayground/playground/commit/a9239b7
