### ISSUE TITLE
/tow issues

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#353]
/tow while Bombing cars. will teleport u with the car, if u go out of the car u can try arm bombing a bike. if u finish the arm bomb in the first car. u will get teleport to outside the bomb shop.

**Comment by RussellLVP** [comment]
I'm not entirely sure what this means. Could you try to rephrase the issue as steps to follow?

**Comment by HaloLVP** [comment]
Enter Bomb Shop, While Menu is there, use /tow. will send you outside bomb shop but with the bomb menu still on. then you can try leaving the car, going a bike and bomb the bike, or just finish the menu, and teleport back to the bomb exit place.

**Comment by RussellLVP** [comment]
Perfect, that was fixed!
