### ISSUE TITLE
Spawning Cars inside VIP Room

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#357]
the command /inf works inside VIP room. you can /tow outside with the car but you will get the error "get out of vip first" before use any command like "/taxi" etc

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
