### ISSUE TITLE
Website / Forum Slowness

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#36]
Every so often, the website and forum become very slow to load and I eventually have to just abandon the request and try again in 5-10 minutes, after which time, everything loads very fast again. I don't know exactly how the website is built, but it may be worth checking MySQL's slow query log and/or the SQL error logs themselves -- since I can only assume this is something related to the DB server. 

I've heard from a couple people who've tried to access our site and thought it was down/offline as it failed to load, so naturally if this is something we can fix, it would be very beneficial. 

This doesn't appear to be on any specific day of the week, or at any specific time -- it's random. I've been able to re-produce it on my PC and Phone, using both my ISPs resolvers and those of Google (8.8.8.8/8.8.4.4), so I'm not sure that it's specific to my connection.

**Comment by ghost** [comment]
I haven't experienced this problem for quite some time, closing this out.

**Comment by RussellLVP** [comment]
There still are known issues with MySQL. Re-opening.

**Comment by debuggest3** [comment]
What issues are you seeing Russell?

**Comment by xhoogland** [comment]
We've recently updated MySQL and switched the forumsoftware to MyBB.

May I suggest to close this issue after 7 days if there aren't any complains anymore about the noted problems?

**Comment by ghost** [comment]
I agree, @Xanland 

FWIW: I've not seen any problems with performance since the recent series of upgrades, everything has been loading as crisp as one would expect :)

**Comment by debuggest3** [comment]
Please keep this open until Russell confirms the issues have been solved.

**Comment by RussellLVP** [comment]
I haven't seen slowness recently. Let's close it!
