### ISSUE TITLE
Ephemeral vehicles should have personalised number plates and NOS

### ISSUE THREAD

**Issue by DeerHunterLVP** [LVPlayground/playground#361]
Those /inf and other cars now spawn without nitros and our names on number plates.

**Comment by RussellLVP** [comment]
Personalized vehicle plates have returned with LVP 30.6. Nitro may take a little bit longer. I'm also thinking of making this a VIP feature. WDYT?

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
