### ISSUE TITLE
/cmds --> Main

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#37]
Firstly:
Under /cmds --> Main, the first option is @ (message). I don't personally see a need for this. It's a bit misleading and isn't really a command as such. The first 'proper' command is /help and one of the options is "How to contact LVP and the Staff of LVP" which I think is good enough. Could we perhaps look at removing "@ (message)"?

Secondly:
Is there a need to list /leave? This command is used to get out of minigames or mapzones and we should only be listing said command in minigames or mapzones, in my opinion, rather than under /cmds. 

![untitled](https://cloud.githubusercontent.com/assets/15123289/10753718/d4aa7e82-7c8a-11e5-903d-58c2bd0a8062.png)

![untitled](https://cloud.githubusercontent.com/assets/15123289/10752931/4950828c-7c85-11e5-923c-692d52710afd.png)

**Comment by ghost** [comment]
maybe for Contact to Staff members a new Colum ?

**Comment by ghost** [comment]
@HopperLVP 

The stage in which I personally would like to get to (note: personally) is to cleanup all the /cmds (e.g. removal of @ (message), /leave, etc) and implement a line of text at the very bottom with something like "Use @ to contact crew", which will be visible pretty much everywhere under /help and /rules

Why? Because I feel like we're under performing when it comes to properly promoting our feature-set. If we make the process of contacting crew members _crystal-clear_, then we're more likely to see "newbies" stick around and turn into "regulars". 

I've joined SA:MP servers in the past which seemed ludicrously complex. We need to make using our server and its features as easy as possible. 

Again, this is just how I personally feel. I don't know what will come of it. I'm still new to Github and learning the basics of Pawn, but maybe I can try and work on this soon :)

In the mean time, thanks for joining up here on Github, and please do continue to contribute and share your ideas -- we need feedback :)

**Comment by RussellLVP** [comment]
Fixed :)
