### ISSUE TITLE
Exporting spawned vehicles

### ISSUE THREAD

**Issue by JTrolin** [LVPlayground/playground#381]
This was reported to me by another player, [PRO]Malik(A).

When the exportable vehicles include vehicles that are spawnable by having 100 tags (Infernus, Elegy, Sultan for exampe), you can simply spawn and export those cars instantly. This is very abusable to gain export stats and money.

I haven't had the correct export list to confirm this yet. But it should be simple enough to reproduce once you get the correct list.

**Comment by xhoogland** [comment]
With this commit the export should now be more strict: https://github.com/LVPlayground/playground/commit/088dda82b667c3d8fe7fdac60807c8725307550e
