### ISSUE TITLE
Disable teleportation during fights

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#384]
Teleportation commands (`/(c)tp`) should be blocked if either the player being teleported to or the player teleporting inflicts/absorbs damage within (10) seconds. 

VIPs should be granted double the time after fighting—perhaps, instead of taking away the feature entirely, disabling their own ability to teleport if their `/my teleport` is off?

**Comment by TotalEpicFailure** [comment]
With regard to the last suggestion of disabling teleportation for VIPs if their setting is off: perhaps incorporating the friends list for houses into this feature (when off, disabling teleportation unless it is to/from these individuals)?

**Comment by RussellLVP** [comment]
Merging with #749.
