### ISSUE TITLE
/me - flood limit

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#386]
When typing and trying to repeat yourself over and over again, you'll get caught by the spam tracker: https://github.com/LVPlayground/playground/blob/master/pawn/Resources/Callbacks/OnPlayer/OnPlayerText.pwn#L60

This functionality works as expected.

However, players can run /me with no flood limit at all. Can we hook this command up to the spam tracker too?

**Comment by TotalEpicFailure** [comment]
This also applies to gang chat.
