### ISSUE TITLE
Fixing /nrg and /inf

### ISSUE THREAD

**Issue by r2dsleep** [LVPlayground/playground#392]
Since a lot of players are abusing /nrg and /inf command to escape fights or anything else. I think you should make a thing that doesn't allow you to use /nrg or /inf for 20 seconds after shooting at someone or getting shot.

**Comment by ghost** [comment]
Hello !

indeed , after disabling the timer , players start abusing this cmds, what u suggest exacly ?

doing a timer 20 sec or something like that ?

for me i suggest to do a timer for normal players and disable the timer for VIP :/

Thanks 
Yassine

**Comment by r2dsleep** [comment]
I just want from them to enable that you cant use /nrg or /inf for 20 seconds after shooting someone or being shot.

**Comment by RussellLVP** [comment]
Yes, we absolutely need to do this. Thank you for the report.

@LVPYassine, I don't think we should allow people to pay (which effectively is what VIP comes down to) for more ability to abuse. We can give VIPs benefits in other areas that keep the game fair.
