### ISSUE TITLE
Cheater warning

### ISSUE THREAD

**Issue by r2dsleep** [LVPlayground/playground#393]
I was thinking to myself if this is even possible, but if it is, it would be much more easier to detect cheaters on LVP. Basically, if developers are able to make a script that allows admin to see if a certain player is hitting suspicious keyboard buttons constantly. For example, if "Insert" button allows certain player to toggle the aimbot or health hack, admins will be able to see "Player12 has used the Insert button", or maybe CTRL, Home, or such buttons that sobeit or any other multihack programs are using.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

To your suggestion, we don't have access to such detailed player keystrokes (good for privacy!), so won't be able to do this.
