### ISSUE TITLE
Improve reaction tests!

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#394]
Let's improve them!
- Add some division into the math and longer character strains into repeat the characters (perhaps 8 to 12 characters) to add some variety with the current two models
- Also, a "jumble" of sorts wherein you have to find the hidden word?
- Finally, some random trivia (related to GTA, LVP in particular, or internationally well-known real life "fun facts")?

**Comment by r2dsleep** [comment]
I agree with the third one. 
For example: Whats the most famous strip club in Los Santos - Pig Pen
