### ISSUE TITLE
Purchasing armour pickups doesn't give you...armour pickups

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#395]
Steps to re-produce:

1) Enter your house
2) Execute _/house settings_
3) Select _Pickup settings_
4) Purchase an _Armour pickup_

Your money will be taken, you'll get confirmation that your purchase was successful, but the Armour is no where to be seen...

Health pickups seem to work flawlessly. 

My house interior is number 10.

**Comment by r2dsleep** [comment]
Same happened to me. This needs to be fixed, I forgot to report the bug.
