### ISSUE TITLE
Support /v eject [player ID]

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#396]
Allow crew members to use `/v eject [ID]` in order to eject a player from a vehicle. For vehicles with doors (i.e., not motorcycles, lawn mowers, golf carts, etc.), we could add an explosion, shoot off the door, and push the player a bit forward/sideways.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
