### ISSUE TITLE
Inform admins using /watch when a Jetpack was given to them

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#399]
Can we add a notice when /watch'ing someone if an admin gave a player a jetpack? Preferably something bold that stands out so that it's not overlooked (E.g. "This player was given a Jetpack by George"). An admin may mistake such scenarios for people using cheats as it stands.

**Comment by TotalEpicFailure** [comment]
While administrators can easily check `/lvp access` for exceptions, perhaps making said exceptions more obvious while spectating is worthwhile to consider. Further, could this be applied elsewhere (i.e., `/fly`, `/boost`, etc.), possibly in the form of a list after an administrator uses `/watch`? ("Player_A has been granted access to the following commands by Fail.Admin: X, Y, Z"?)

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
