### ISSUE TITLE
Armor pickup doesn't spawn

### ISSUE THREAD

**Issue by HolsjeLVP** [LVPlayground/playground#401]
At _ProToTyPe_'s house his armor pickup does not spawn.

http://puu.sh/rSMj4/78f4d1eb6c.jpg
^Only a health pickup

http://puu.sh/rSMmh/4f8f6e98bb.jpg
^Both enabled.

I tried removing both pickups, and adding both again. This did not work.

**Comment by xhoogland** [comment]
Duplicate with #395. ;)

Thanks for reporting!
