### ISSUE TITLE
Some sort of lines on player's skins

### ISSUE THREAD

**Issue by Lash** [LVPlayground/playground#405]
As you can see in the picture and the title is pretty simple

https://s15.postimg.org/8wkxg51d7/lines.jpg

Sorry I am bad at explaining things!

**Comment by ghost** [comment]
That link seems to be visible by you only, since when I visit it, I just get redirected to http://tinypic.com/

You may like to consider using imgur.com instead.

**Comment by Lash** [comment]
Fixing!

Update - done.

**Comment by ghost** [comment]
Can you reproduce this on other SA:MP servers?

Further, is it possible that a mod/plugin you have installed could be responsible?

**Comment by Lash** [comment]
Not seeing it on other servers. Haven't installed any mods other than what I've always used. And noticed this yesterday-night. It looks like it has something to do while spectating. I will see if other admins are seeing it aswell and check back here!

**Comment by Lash** [comment]
It seems that other admins are not seeing the lines/underscores like I am, so it must be a problem on my end then.

**Comment by RussellLVP** [comment]
Do you have playerinfo (`/my playerinfo`) enabled? It might be a left over from that somehow?

**Comment by Lash** [comment]
Yes, I believe thats it!

**Comment by xhoogland** [comment]
@Lash: You have any certain/definite conclusion about this problem being yours only or that we should take a look into this? :)

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
