### ISSUE TITLE
Make RC Barons count as a lame kill

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#406]
Add the lame kill's revenge menu to any player killed by an RC Baron.

By using the same logic as the Sea Sparrow/drive-by killings, we can easily see that permitting usage of the RC Baron without the revenge menu is inconsistent with unfair advantages over other players (VIPs included).

**Comment by RussellLVP** [comment]
Agreed. This is a trivial fix that we'll include for the next release.

**Comment by r2dsleep** [comment]
Or just make a thing that if you kill someone with RC Baron that it doesn't count in player stats as kill or death?

**Comment by RussellLVP** [comment]
Let's have further discussion on the forums. It seems opinions on this issue are a bit diverse, to say the least.
