### ISSUE TITLE
Have the KillTime weapon be a *spawn* weapon

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#407]
Suggestion: If a weapon is given for the KillTime event, that weapon should spawn with the players for the duration of the fun!

As a side thought, perhaps having an option where this would be the _only_ usable weapon?

**Comment by xhoogland** [comment]
At this moment I have rewritten killtime. In that new version there is no possibility to define a custom weapon, yet! For a first version I rather have it easy.
In the case I am going to add the possibility to define a custom weapon, I will definitely consider this.

**Comment by RussellLVP** [comment]
What is the status of the kill time rewrite?

**Comment by xhoogland** [comment]
Actually giving the prizemoney still needs to be done + writing of several unit tests.

**Comment by RussellLVP** [comment]
Ok. Let's assign this to you then.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
