### ISSUE TITLE
#LVP.echo is not catching all in-game activity

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#408]
From random messages and joining/leaving the server to various killings and command usage, certain activities are not being shown by the Nuwani sisters. What gets ignored and when is seemingly random, but (from my own observations) it has never ignored more than one piece of activity at a time.

As a brief example, earlier today an administrator had quit the server without it being shown on IRC that they had, forcing Saber to believe they were, in fact, still in-game. This poses obvious concerns with logging and reports.

**Comment by TotalEpicFailure** [comment]
This also applies to sending messages in-game. At times, even though a message is successfully sent to the in-game chat, it fails to show on IRC (making the speaker try again and thus repeating themselves to everyone else). 

I will admit that I am uncertain if this is an entirely different problem and should be its own ticket, however.

**Comment by xhoogland** [comment]
[09:09:03] \* Noweni (Noweni@gtanet-hqt.8ca.192.82.IP) has joined #lvp.echo
[09:09:03] \* Noweni (Noweni@gtanet-hqt.8ca.192.82.IP) Quit (Changing host)
[09:09:03] \* Noweni (Noweni@sa-mp.nl) has joined #lvp.echo
[09:09:03] \* LVP sets mode: +h Noweni

For a next time we can use: !reconnectbot <missing bot> should work. Someone kicked Noweni, hence we were missing some messages. ;)
