### ISSUE TITLE
Reaction tests should show as $5,000 on IRC

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#409]
Surely this is not a massively high priority ticket, but reaction tests give the winner $5,000—whereas our echo channel shows "$10.000" as the amount won:

_[10:09:03p] <%Nuweni> **\* First player to type KSLFP9LN wins $10.000!
[10:24:46p] <%Nawoni> **\* First player to solve (14-72) \* 2 wins $10.000!_

**Comment by RussellLVP** [comment]
@xhoogland could you please take a look?
