### ISSUE TITLE
cakepack is no longer working

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#41]
The /cakepack command is no longer working. It just shows the usual command not found textdraw that you'd see with a non-existent command. This was working fine up until LVP 24.2/3.

**Comment by ghost** [comment]
I know bro it for Admin or Mod

When I was Temp-Mod I was just trying to do it 

That Command not found!

**Comment by RussellLVP** [comment]
What is /cakepack? @mblokker

**Comment by mblokker** [comment]
/cakepack (and /takepack) is a command that is part of my personal filterscript 'cake.pwn'. It gives administrators the opportunity to give players jetpacks (or take them).

I guess that the filterscript isn't loaded into the server.

**Comment by ghost** [comment]
Load it :100:

**Comment by RussellLVP** [comment]
https://github.com/LVPlayground/server/commit/bdad2274515ee9a304e49625a18e3272b97e6dbc
