### ISSUE TITLE
Purchasing premier accounts bug

### ISSUE THREAD

**Issue by Lash** [LVPlayground/playground#411]
So a friend of mine wanned to upgrade his bank account to permier he had around 5mil on his normal acc and the bank asks for 150mil. So is this the actuall price for the premier account? Or is it supose to be less due to economy changes.

Pic: https://i.imgsafe.org/3296768c67.jpg

**Comment by Lash** [comment]
OHHH WAIT. Will premir accounts be remove completely? I just remembered!

**Comment by RussellLVP** [comment]
Yeah, we will remove Premier Accounts altogether. Until then, however, it makes sense to keep this text in sync with what we're actually doing, so I've made that change.

Thanks for the report! :)
