### ISSUE TITLE
Tuned vehicles are not synchronized to others

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#420]
This is best described in the below image (courtesy of zeXo_)...

![yjuula2](https://cloud.githubusercontent.com/assets/21077320/20066195/bc67e472-a4de-11e6-9976-ecc2b57f1fed.png)

The Euros above was modded by me to be pink and have golden rims, but its appearance to me does not match its appearance to others. This was repeated with an Elegy modded at Wheel Arch Angels (http://i.imgur.com/60Jc7Hv.jpg is my own, versus Finisha's https://s17.postimg.org/pcx8wnddb/TEF.png)

Could this be looked into?

**Comment by RussellLVP** [comment]
We'll address this as part of #700
