### ISSUE TITLE
 /ignore not working :/

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#424]
check screen shoot vv
![sa-mp-092](https://cloud.githubusercontent.com/assets/19735645/20217649/bc4a0d0c-a818-11e6-8cff-73427213f4f3.png)
![sa-mp-093](https://cloud.githubusercontent.com/assets/19735645/20217650/bc4e678a-a818-11e6-9d57-7ea1fb914dfa.png)

i used /ignore but is not working :O

**Comment by RussellLVP** [comment]
Thank you for the report. I have no idea why this isn't working. The code seems fine (03a46dee). Does the `/ignored` commands show them as ignored?

**Comment by ghost** [comment]
Yes it's Show them as ignored but they still able to send PM message to me 

and me too can do that
