### ISSUE TITLE
Minigames Dual Bug

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#427]
Since Deathmatching minigames and race minigames are considered diferent, you can join both minigames. Example /rocket then /race 1. You will get out of boundaries starting the race, and when the /rocket ppl leave the minigame, you will be stuck in the Rocket zone boundaries, even if teleport back to ship, you will be out of boundaries in main world going back to Rocket zone.

BTW sorry for the inactive time, was testing a bit FiveReborn mod. Back to work..

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
