### ISSUE TITLE
Some kind of slide bug that allows you to shoot after getting killed

### ISSUE THREAD

**Issue by DeerHunterLVP** [LVPlayground/playground#429]
This usually happens in minigames such as /ww /random

Sometimes after getting killed, we still can take a shot and kill the guy that previously killed us, or whoever is around. Like zombie kill, ofcourse in player's screen it appears that we are dead, lying on the ground. 
But from our perspective we are still standing there and got 2-3 seconds to take the shot.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
