### ISSUE TITLE
Christmas decorations

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#430]
It'd be cool to have the Christmas decorations back around now, or in a week or so.

Also, free temporary VIP to registered players again might be nice.

Further, did we enable [Gift Hunting](https://github.com/LVPlayground/playground/blob/master/pawn/config.pwn#L106) last year? I don't see any records of this in the history - again, this would be fun :)

**Comment by TotalEpicFailure** [comment]
I remember presents from years ago! It would be lovely to see their return. Further, is snow considered a "decoration"? ☺

**Comment by XilentLVP** [comment]
Gift Hunting is a good idea.
@TotalEpicFailure The snow would be nice but will be awesome if we'll have a command to enable/disable the snow.

**Comment by LVPYassine** [comment]
enable the features then why waiting :p

**Comment by RussellLVP** [comment]
Done in a0fd800.
