### ISSUE TITLE
Check online-table bug and corresponding event propagation

### ISSUE THREAD

**Issue by xhoogland** [LVPlayground/playground#431]
Check online-table bug and corresponding event propagation

**Comment by RussellLVP** [comment]
What does this mean?

**Comment by xhoogland** [comment]
If a player tries to play with a registered nickname, (s)he can play as guest. In that case you get another nick given by the gamemode.

In that case the OnPlayerGuestLogin is fired, but it seems like the online-table does not recognize the new name.

**Comment by xhoogland** [comment]
Crap, only fixed the propagation towards javascript-part.
