### ISSUE TITLE
Chat monitoring

### ISSUE THREAD

**Issue by DeerHunterLVP** [LVPlayground/playground#433]
While being in other worlds/participating minigames, admins aren't  receiving any messages from other worlds, which is often needed.

**Comment by ghost** [comment]
I believe _/my allchat_ will do what you're looking for - can you try it out and let us know? :)

**Comment by RussellLVP** [comment]
I just tested this, and the `allchat` option still seems to work fine :) Thanks for the report, better safe than sorry!
