### ISSUE TITLE
Gunther's ship label displays on other NPC

### ISSUE THREAD

**Issue by HolsjeLVP** [LVPlayground/playground#435]
http://i67.tinypic.com/2ly1xqu.png

The label is sometimes attached to other NPCs different from Gunther on the ship.

**Comment by TotalEpicFailure** [comment]
Most noticeably, this label is always on another NPC that can be seen walking around underneath the massive haystack.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
