### ISSUE TITLE
I am Think of New Command / in /my section

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#44]
When we Play Drift Race Ex: /race 35 etc etc

I can't get my Drift point  ?

So u i am Thinking to Add /my drift Point  

means [i played one race and i get 500 point And in second race i got 200 so 500 + 200 = 700 Drift point ?

Hope u like this

**Comment by ghost** [comment]
The race system is currently being converted from Pawn to JavaScript with many improvements anticipated. I'm going to close this out until these changes are live.

**Comment by RussellLVP** [comment]
The race system will definitely add the infrastructure, but it won't expose the value. This bug is about exposing the value, thus it adds value.

Re-opening. We can do this quite trivially once the new race system is done :).

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
