### ISSUE TITLE
show ts in servermessage

### ISSUE THREAD

**Issue by HolsjeLVP** [LVPlayground/playground#444]
https://github.com/LVPlayground/playground/blob/961476aedb14dd53f83379d0996d954337d77322/pawn/Interface/functions.pwn#L378

Can we like add TS to that to try and get more people on TS as a community

**Comment by TotalEpicFailure** [comment]
Is this as simple as adding `"ts"` and changing the next line's `8` to `9`? I don't want to just change it personally for fear of messing up something else on that page, but I support adding this message into Gunther's arsenal!

**Comment by xhoogland** [comment]
Add indeed the text you use at /show at that line and +1 to both the nr 8 in that function/method. ;) If you are not sure, just do a pull request.

The easiest way is to click the pencil on https://github.com/LVPlayground/playground/blob/master/pawn/Interface/functions.pwn and click the pull request-radiobutton after writing your title and message at the bottom of that page.

**Comment by xhoogland** [comment]
Fixed by Russell already since https://github.com/LVPlayground/playground/commit/b685f9b40995265ba1bbdb29d8ef30ed208ad08c and https://github.com/LVPlayground/playground/commit/e0e01c93774867db6e71899a6fdf80b0c0bcffdc!
