### ISSUE TITLE
/v color

### ISSUE THREAD

**Issue by BigShem** [LVPlayground/playground#446]
I've been waiting for it to get fixed but looks like no one did, /v color should be back it's really useful and gets us the permition to change the colors of vehicles like the cop cruiser and helicopters...

**Comment by TotalEpicFailure** [comment]
At time of reopening, `/v color` is not a usable command.

**Comment by xhoogland** [comment]
That's due to a previously failed release. Will be added in the fixed
upcoming release.

**Comment by xhoogland** [comment]
Done!
