### ISSUE TITLE
Map teleportation always enabled

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#449]
Whenever a player is given temporary administrator rights, and they enable `maptp`, they have it until it is reset. Why not automatically reset this particular setting when they leave the server?

**Comment by xhoogland** [comment]
This should indeed be reset when taking temp admin or at leaving the server.

**Comment by HolsjeLVP** [comment]
Same is for teleport.

**Comment by xhoogland** [comment]
Made a new issue for this: https://github.com/LVPlayground/playground/issues/453
