### ISSUE TITLE
Gunther Peace Message on normal Players

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#454]
in first place no idea why Gunther got disconected from server but Peace message shouldnt appear in players even if that is the case. Permanent Message on ID 17 seems.
He reconnected as ID 13, so now things are messed up tho.

![sa-mp-008](https://cloud.githubusercontent.com/assets/22722462/22768310/9bad450c-ee57-11e6-8e03-7a1b2032625e.png)

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
