### ISSUE TITLE
Killtime adjustment

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#46]
Today I started a /killtime. I then came to notice in the killboard that a player was killing the same person repeatedly. I spectated the player in question, and they were in the Rivershell minigame. I can only assume the other player was AFK without being minimized/esc'd and so kills were racking up very fast (spawnkilling). 

I would like to see the killtime system modified so that it only applies to world 0. I haven't tested this, though I assume that players in minigames do not get notified when a killtime starts, and so I don't feel it's right that they should be part of it.

Thoughts?

**Comment by xhoogland** [comment]
Silence is agreeing, right? :+

Anyhow, let's make killtime only possible in (the standard) world 0!
