### ISSUE TITLE
Bring the Vehicle Modifier Menu Outside the Garage

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#461]
Detonate inside a garage or tune shop is working, Detonating yourself will let u go outside the garage and outside cars with the Modifier Menu.

Garages for tuning should be like safe zones to prevent vehicle detonations.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
