### ISSUE TITLE
Force your enemy to leave the game /fight /races

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#463]
Fight invite to someone, and when u put all the rules and put the ID of your enemy, Before he accepts just /race 1 or any race, u will be teleported while fighting in the fight club, your enemy will be alone in the fight and u will be out of boundaries in the race.

**Comment by HaloLVP** [comment]
Kind of duplicate #474
Just different results

**Comment by RussellLVP** [comment]
Races have since been fixed, thank you!
