### ISSUE TITLE
Get ur House settings outside, and use own music

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#464]
Join any /race, when you are inside the race /house goto, and go to ur house, Server will notice you left the car and respawn you, but now with Your character bugged for good.
Get ya own streams :3 

![sa-mp-010](https://cloud.githubusercontent.com/assets/22722462/22774662/7f7bf1ea-ee7e-11e6-8a64-003df840f4d2.png)

**Comment by RussellLVP** [comment]
This has since been fixed. Thank you for the report!
