### ISSUE TITLE
/race menu working in interiors

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#465]
/race menu needs exception as /minigames menu have right now when you are in interior.

**Comment by HaloLVP** [comment]
Also /race menu working inside Garage modifiers.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
