### ISSUE TITLE
/watch while being in tune shops

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#466]
Will get admins screen bugged, and black screen when getting to other car, forcing them to relog at the end.
Of course admins shouldnt do that inside tune shops, but anti dummy is never bad :3 ppl get temp admins some times.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
