### ISSUE TITLE
Starting Minigames issues

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#469]
If you start any kind of minigame, before the minigame teleports you to the game zone if you go to any interior, when the minigame teleports you, you will be bugged not able to see the map, in grey zone, until you /leave the minigame, it should add the exception like the /taxi do, that when you go interior and the taxi go to pick you up it says "taxi couldnt find you", minigame should auto cancel when getting to interior.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
