### ISSUE TITLE
avoid Headshots bug abuse

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#471]
right now there is a bug going on with the headshots, and ppl need to relog to get headshots, this is happening soo frecuently, 2 many times in just a simple gang war, until that is reviewed headshots system from sniper should be removed.
it is getting abused and seems like some ppl know how to reproduce it.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
