### ISSUE TITLE
/house buy bug

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#473]
While you are buying a house, you can start a /race 1, then leave the race. You will be back to selection, but this time if you cancel the selection, you will be ported to the Last House/Mansion you were looking for, but you wont be able to exit as there is no portal in door to go out. Pretty amazing tho :3

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
