### ISSUE TITLE
Troll the Fightclub v2

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#474]
Invite someone to fight club and do /race 3, some seconds after fight club in LV starts u will be ported to /race, then after the enemy relog or u leave the race car, u will be in the Fight Club under Boundaries that u cant escape, and be able to intercept anyone that start dueling there. Sorry Hoody :3 

![sa-mp-014](https://cloud.githubusercontent.com/assets/22722462/22846925/643b464a-efc0-11e6-8199-0de308670126.png)

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
