### ISSUE TITLE
Become Omnipresent, Shot enemies they cant shot you.

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#476]
Steps:
/race 1
Leave and Enter Car.
Back to Main World
Use Deagle to point any direction.
Change weapons of desire.
Shots will pass through you.
Can survive Nukes and Handofgod.

Disadvantages:
Cant Survive Spray can.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
