### ISSUE TITLE
/v minor issues

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#478]
you are allowed to do /v while diving (/dive), wich will cause u to die. Would be good to add the exception as when u /taxi while diving, (Cant get you up from there) for something like (cant spawn a vehicle up there)

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
