### ISSUE TITLE
Armor And Health Pickup bug

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#479]
When you remove them temporary for any rare ocasion, if you want to put them again, you will have to buy them again. 
Don't think  that is working as supposed to, at least not for the same house, for other house that would be ok to pay for different pickups.

**Comment by xhoogland** [comment]
As far as I know we nowhere mention you can remove them temporarily. We just ask if you want to add or remove it.

Perhaps you don't want it anymore and get rid of it, in such a case it is logical to repay when you want to add them. Else we would perhaps said something about hiding if you ask me.

**Comment by HaloLVP** [comment]
Pretty valid point, just suggestion that the Hide option would be better in a future.
Closing the ticket tho :3
