### ISSUE TITLE
Remove the moderator rank

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#48]
We removed the moderator rank [back in 2007](https://forum.sa-mp.nl/index.php?topic=2707.msg31388#msg31388), but never quite finished removing it from the code. Now it turns out that we have three moderators again.

Rights given to moderators are inconsistent and undocumented. Many features may more or less work, but important contra-features will not, i.e. being able to ban a player, but not able to unban them again.

Let's promote the [three moderators](https://sa-mp.nl/players/staff-members/1/position/asc.html) to administrators - remember that any rights are granted based on trust anyway, and remove the level from being usable completely.

/cc @GrannyLVP

**Comment by SanderRutten** [comment]
If it makes life easier, and less complex stuff, go ahead :)
