### ISSUE TITLE
Liberty City Property Bug

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#480]
When you stand in the property for at least 5 seconds or longer, there is a random red error what will be shown at u every 1 second.

![sa-mp-021](https://cloud.githubusercontent.com/assets/22722462/22864853/426dbbf4-f12f-11e6-900b-0e018eb41abc.png)

**Comment by RussellLVP** [comment]
This happens because of how SA-MP handles pickups, there's not too much we can do to fix this, and people will rarely end up in LC anyway. Thanks for the report!
