### ISSUE TITLE
Cant lock own personal vehicles?

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#481]
/lock is a funtion for public vehicles, and of course u cant /lock vehicles that u dont own, but it should be able to lock your OWN vehicles. So people dont steal them from you right when you are in them.

![sa-mp-022](https://cloud.githubusercontent.com/assets/22722462/22870223/eba6f324-f17b-11e6-91c5-977beef28140.png)

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
