### ISSUE TITLE
/watch minor issues

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#482]
if you are in your personal house and you do /watch to someone, when u /stopwatch, you wont see the portal in the door of your house to go outside it will dissapear, but still be able to force going out doing /t 0 or /stp to someone.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
