### ISSUE TITLE
Auto kill players that enter your car.

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#484]
When the player take the door of your vehicle and the animation to enter in it, /jump 1, will launch them to the air like /handofgod, and will kill them. Tested Twice, works flawless.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
