### ISSUE TITLE
How to get Immortal, this time not stuck.

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#485]
Steps:
Ramp some car to the ship
Get in the vehicle as passenger to prevent it dissapearing
/jump 1
Now you are immortal but inside the /jump zone wich is useless
/house goto Go to your house
Exit the house, now you are immortal in main world
Get Weapons from dead players.
Profit?

**Comment by HaloLVP** [comment]
Bonus:
Able to do /vr /flip As driver or passenger in mainworld

![sa-mp-030](https://cloud.githubusercontent.com/assets/22722462/23066724/61054e26-f4f2-11e6-8465-286cd017cfe4.png)

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
