### ISSUE TITLE
Can do /race 1 while /fight watching

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#486]
After the race start, leave the car, and u will be there where people are dueling.
The Troll Fightclub V2 bug is different as this one because doesnt need the /fight watch to invade the club.

This one is easier

![sa-mp-026](https://cloud.githubusercontent.com/assets/22722462/23002520/951becd8-f3c1-11e6-8f6c-c8fd2a077a42.png)

**Comment by RussellLVP** [comment]
Fixed.
