### ISSUE TITLE
Get the money of Crush vehicles, without crushing them.

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#487]
If you go with the car to the crush area, and do /race 1, you will be ported to the race then /leave, when u come back you will be out of the vehicle also receive the money of crushing, and the car wont dissapear.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
