### ISSUE TITLE
Crush vehicles without limits. Free moneyz

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#488]
there are 2 vehicles close to the crush zone, you if u crash them 1 by 1 changing turns, first limo, then brown car, then limo, then brown car, you will be earning the 2k unlimited times (boring of course) but not supposed to work that way.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.

**Comment by HaloLVP** [comment]
Ah no problem, if any day u guys move to rage mp for gtav notice me so i can test out too, im avaible sometimes for helping out

Enviado desde mi iPhone

El 28 abr 2020, a las 22:55, RussellLVP <notifications@github.com> escribió:

﻿

We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.
