### ISSUE TITLE
Gang chat and mute

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#489]
/mute supposed to mute players and make them unable to communicate with others players for tamp/perm, but the muted players can evad that with talking in gang chat.

**Comment by HaloLVP** [comment]
Normally talks in gang chats can be more offensive than in normal chat, the mute just prevent public people to see what you want to say, but gang members are supposed to be "something close as family" and if he is trash talking gang chat /gang kick is always an option.

**Comment by ghost** [comment]
you right, but mute block the comminucate commands too like /me or somthing like that that means it's must block gang chat too

**Comment by mblokker** [comment]
No, because /me is public, gang chat isn't.
