### ISSUE TITLE
Problems with recent registered accounts.

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#491]
For some reason the server doesnt get the recent registered accounts, causing new players to loose interest, already someone activated account and it even shows in !players that he is registered, yet in server when he gets to the game, it doesnt ask him to log, just to play as unregistered.

**Comment by RussellLVP** [comment]
Xanland, did you reproduce this? Looking at the database, 23 people registered yesterday, 11 of whom validated their accounts, and five of whom logged in to their accounts.

**Comment by xhoogland** [comment]
FreakinsPL, afaik activated. Registered yesterday, just spawns and no dialog.
swat12, dunno if activated but same story as above.

**Comment by HaloLVP** [comment]
What about 24humaam
He said he validated i joined with his name, still seems unregistered.

**Comment by debuggest3** [comment]
24humaam, FreakinsPL and swat12's accounts have all **not** been activated, that's why they cannot login. They should look in their email accounts again to see if they have an activation mail (maybe in the spam folder) and click on the link inside.

**Comment by HaloLVP** [comment]
Weird because FreakinsPL were saying he received the: this account is already active you cant activate it again or something like that.
