### ISSUE TITLE
Unregistered* players shouldnt be able to /buy properties

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#494]
Reason?
They can buy the properties yet they wont earn money from it. Because the money goes directly to Non-existant Bank account, they cant /withdraw /bank or anything like that.

**Comment by HaloLVP** [comment]
Misslead Tittle, correcting: Unregistered players*

**Comment by xhoogland** [comment]
In my opinion we should, in this case, just give them the money as cash. :)

**Comment by HaloLVP** [comment]
that would be the best way to fix the bug.

**Comment by TheTrolololo** [comment]
you can get money from properties even tho you are unregistered. you just need to go to main bank and type /accounts earnings off. though would be better if that wouldnt be nessecery to visit main bank every time
