### ISSUE TITLE
Money trick with /borrow

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#495]
As  unregistered players can borrow too. They can /borrow 500,000 and send to a friend, RELOG and Borrow-Send 500,000 to a friend again. 
Repit for Higher Profit?

**Comment by ghost** [comment]
Whilst you're correct in saying this, I'm wondering what (if anything) should be done. We want to give players the flexibility they deserve by making commands such as /borrow available. This requires 1) A friend to do this with and B) A lot of boredom. Most people aren't going to want to relog over and over again just to make some money.
