### ISSUE TITLE
Le Fun suggestion

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#497]
Instead of /ban (kicking from server) those hackers, there should be an option of Send them to virtual World (1337) for 3,7,15,30 days. 
Where they can fight against other (banned) hackers and stay ingame lmao. Cutting the IRC/ingame chat connection with world (1337) Wont harm anyone and could be fun :3 Jailing legit players when they break rules for 2 minutes into hacker world ayyyy lmao xD

Cons: hackers commin with new names to join world 0. isnt possible to assign ip to a virtual world

**Comment by ghost** [comment]
lmao the best idea ever xD

that will be awesome

**Comment by TotalEpicFailure** [comment]
I'm closing this issue as administrators already have this ability with the `/world` command.

**Comment by LVPYassine** [comment]
you didn't even understand, please re read it
