### ISSUE TITLE
Increase regular ban lenght

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#498]
(3 Days to 7 Days automatically)

Right now the automatic lenght is 3 days.
Kicking a hacker before the ban just to ban for more days is complicated as the ammount of hackers increase every day.

i suggest the regular lenght to be 7 days.
there are regular players that get banned for other reasons, but those can be dealt manually, they are less than hackers.

Of course we are trying to keep an community alive(high numbers in server) thats why the new rules were made about ban.
But right now is going the opposite, Hackers that come every 3 days ruin the game experience of legit players when admins are offline sleeping or bussy, those that rage quit getting killed by hackers every second never come back, at least high percent of new players.

Suggested to some admins and they agree with this terms. 1 week will keep things more clean.

Thanks for your time :3

**Comment by TotalEpicFailure** [comment]
I am closing this issue due to the fact that crew members can easily change the length of time either in-game (via this very command) or on IRC after the fact.
