### ISSUE TITLE
Tax achievement

### ISSUE THREAD

**Issue by Batata45** [LVPlayground/playground#504]
While in game and looking at the achievements, I noticed the tax achievements and wondered if they had been lowered since the previous economy nerf thing back in summer 2016.

I browsed the commits a bit and didn't notice a change to them. Maybe this would be a good idea to lower them a bit since money has basically been divided by ten (I don't remember)

**Comment by RussellLVP** [comment]
I'm closing this in favour of the broader issue about achievements, which have recently been revised.
