### ISSUE TITLE
IRC commands required for NuwaniJS to take over

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#510]
## NuwaniJS
Given the inherent instability of Nuwani, as well as the dependency on additional bots such as Sonium, Saber, Boteend and others to have a good breadth of commands, a project was started to rewrite our IRC bots in JavaScript. Documentation is available here:

https://github.com/LVPlayground/playground/tree/master/javascript/features/nuwani

In order for the new system to replace the existing ones, we want a decent level of feature parity. Note that we don't want to launch a perfect product: this will be iterated upon, so certain commands may be pushed to beyond the first version.

### Command required for v1
- [x] !addalias
- [x] !addnote
- [x] !admin
- [x] !aliases
- [x] !announce
- [x] !ban
- [x] !ban ip
- [x] !ban range
- [x] !ban serial
- [x] !changename _(previously !changenick)_
- [x] !changepass
- [x] !getid
- [x] !getname 
- [x] !getvalue
- [x] !history _(previously !nickhistory)_
- [x] !ipinfo
- [x] !isbanned
- [x] !kick
- [x] !lastbans
- [x] !msg
- [x] !players
- [x] !pm
- [x] !removealias
- [x] !say
- [x] !serialinfo
- [x] !setvalue
- [x] !supported
- [x] !unban
- [x] !vip
- [x] !why

### Commands to consider implementing after v1
- [ ] !givetempadmin
- [ ] !jail
- [ ] !taketempadmin
- [ ] !mute
- [ ] !unjail
- [ ] !unmute

### Commands which will be removed
- [x] !givevip

**Comment by RussellLVP** [comment]
I have updated the list with the commands we're planning to install for the first version of Nuwani JS. Documentation for administrators is available here:

https://github.com/LVPlayground/playground/blob/master/javascript/features/nuwani/ADMINISTRATORS.md

**Comment by BeanerLVP** [comment]
I'd like to suggest a !clear command under 'commands to consider after v1', similar to the /clear command in-game, to clear the in-game chat via IRC in case of server advertisements or extreme profanity.

**Comment by RussellLVP** [comment]
I'm declaring victory. Please file new issues for individual commands that are needed.
