### ISSUE TITLE
Modify & add some crew notices regarding houses

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#511]
1. Looking up logs when complaints/issues arise is quite difficult with the message format being this:

>  FOUL (Id:9) has purchased a house for $19,908,351.

I propose a change such as:

>   (Id:9) FOUL has purchased a house for $19,908,351. (House Id: 233)

Where the player ID is mentioned before the nickname and the house ID is mentioned at the end. It makes it easier for crew members to look up house transaction logs using nicknames of players, because IDs are always different each session. For instance, I can't find logs of (R2D)Fallen's house purchases because the ID is in between.

2. Keeping point 1 in mind, add crew notices for when someone:

- names their house (along with the exact name)

> (ID: 1) Fallen has set House (ID: X)'s name to "Full name".
> (ID: 1) Fallen has modified House (House Name) (House ID: X)'s name to "Full name".

- adds/edits their welcome message (along with the message)

>  (ID: 1) Fallen has set House (House Name) (House ID: X)'s welcome message to "Full message".
>  (ID: 1) Fallen has modified House (House Name) (House ID: X)'s welcome message to "Full message".
> (ID: 1) Fallen has deleted House (House Name) (House ID: X)'s welcome message: "Message here".

- and similarly, notices for all other available house settings such as the radio stream, parking slots, entrance color, etc. Having all these logs in #lvp.echo will be very useful to detect abuse or deal with complaints in the future.

Currently, house names are displayed only when they're sold:

>   Lmao (ID: 10) has sold the Lmao's house house (Id:1,929).

I propose changing the format to

>   (ID: 10) Lmao has sold the "Lmao's house" house (ID: 1929) for $100,000.

**Comment by SophiaLVP** [comment]
Certainly

**Comment by OttoRocket-LVP** [comment]
I've added your suggestions. (However kept it as **Lmao (ID: 10)** as that is to my opinion better readable).

I didn't add all possible house configurations; only he ones you mentioned. We should have #271 implemented before we add more logging so administrators can decide to turn off the messages to avoid spam.

Edit: Swapped ID and Name in order to look into the logs easier as discussed.
