### ISSUE TITLE
Armour pickup

### ISSUE THREAD

**Issue by XilentLVP** [LVPlayground/playground#513]
A player tried to add helath & armour pickups to this house. He bought them both but only health pickup was added in the house, there was a problem with the armour pickup. He tried again and the same problem with the armour pickup, it was nowhere.

**Comment by OttoRocket-LVP** [comment]
Could you please provide the interior(s) where this happens?

**Comment by XilentLVP** [comment]
![4FA4B820-1174-4DE3-964C-8F1D068B431E](https://user-images.githubusercontent.com/15145881/80261120-3756bd00-8692-11ea-8701-3ec72d5d257f.jpeg)
This one. (TheMonster’s house)
I’ll tell Ricky to add another one if he knows

**Comment by Specifer** [comment]
My house which has the interior Mansion too has this problem . I intact rebought the armour . The position of armour just appeared and when off quicky idk why. It's not like the last.problem with , instead of . . But Idk what is that problem exactly ?
