### ISSUE TITLE
A /guide command for temporary administrators

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#518]
Similar to the /weapons command, which [opens up a dialog](https://i.imgur.com/IP8FKs8.png) with all weapon names & IDs, I'd like to propose a /guide command for some quick key points. It goes without saying that our crew members are responsible for training people properly when they decide to grant them temporary rights, but some things are ignored and/or forgotten sometimes.

This command can act as a quick guide and answer some questions regardless of the presence of permanent crew members. As of now, this is the content I've come up with:

> As a temporary administrator, there are some key points you should keep in mind:
> 
> 1. Be nice, be respectful, and more importantly, stay calm in all situations. 
> 2. Useful commands: /p, /mute, /jail, /kick, /ban, /fix, /watch, /stopwatch, /weapons, /vr, /cruise.
> 3. The default ban length is 3 days. Utilize verbal warnings, /mute, /jail, and /kick before banning people for minor offenses such as ship-nading, interior-nading, or swearing.
> 4. Always test for health hacks using /p handofgod and /fix. If they don't work on de-synced players, use /reconnect. DO NOT ban based on /p burn and /p nuke alone.
> 5. Recording & submitting video evidence of suspected hacking in case of regular/registered players is mandatory. The crew shall review it and take appropriate actions.
> 7. Use /crew [message] to send messages to the LVP Crew IRC channel, if you require any assistance.
> 
> Please visit https://administrator.guide/ for a general overview.
> Remember, this is only a game — don't take things personally. Stay unbiased at all times.
> 
> Thank you for volunteering to assist the Las Venturas Playground crew. We sincerely appreciate your efforts!

Point 4 is critical and needs to be included, in my opinion. I have watched countless players getting falsely banned due to it.

If this command is implemented, I'd also like it to be made known in the message displayed when a player receives temporary rights. So, we change:

`You have been granted temporary administrator rights`  

to something like

`You are now a temporary administrator. Kindly read the contents of /guide`

**Comment by Specifer** [comment]
I'm a newbie and i don't know anything about JS . But Im sure i can help with this .
At playground\pawn\Elements\AdministratorCommands.pwn 
Replace line 

- [ ] SendClientMessage(subjectId, Color::Success, "You have been granted temporary administrator rights");


With , 

- [ ]  SendClientMessage(subjectId, Color::Success, "You are now a temporary administrator. Kindly read the contents of /guide");


At commands.js in playground\javascript\features\commands\commands.js 
Add line 

- [ ] 

commandManager.registerCommand('guide', InfoDialogCommand.create('data/commands/guide.json'));

At playground\data\commands 
Add file guide.json 

[guide.zip](https://github.com/LVPlayground/playground/files/4543648/guide.zip)

Lastly I don't know anything about scripting , I am just beginning to learn . If I was wrong anywhere please correct it . plus if you want to make it temp admin only command please do so

Regards , 
Specifer

**Comment by Specifer** [comment]
Is this good or ....?

**Comment by SophiaLVP** [comment]
@BeanerLVP , can you post this guide on the LVP forum?
> As a temporary administrator, there are some key points you should keep in mind:
> > 
> > 1. Be nice, be respectful, and more importantly, stay calm in all situations.
> > 2. Useful commands: /p, /mute, /jail, /kick, /ban, /fix, /watch, /stopwatch, /weapons, /vr, /cruise.
> > 3. The default ban length is 3 days. Utilize verbal warnings, /mute, /jail, and /kick before banning people for minor offenses such as ship-nading, interior-nading, or swearing.
> > 4. Always test for health hacks using /p handofgod and /fix. If they don't work on de-synced players, use /reconnect. DO NOT ban based on /p burn and /p nuke alone.
> > 5. Recording & submitting video evidence of suspected hacking in case of regular/registered players is mandatory. The crew shall review it and take appropriate actions.
> > 6. Use /crew [message] to send messages to the LVP Crew IRC channel, if you require any assistance.
> > 
> > Please visit https://administrator.guide/ for a general overview.
> > Remember, this is only a game — don't take things personally. Stay unbiased at all times.
> > Thank you for volunteering to assist the Las Venturas Playground crew. We sincerely appreciate your efforts!

**Comment by BeanerLVP** [comment]
> 
> 
> @BeanerLVP , can you post this guide on the LVP forum?

Not until we've finalized its content. Even if it doesn't get implemented in-game, I'll have to discuss the content for a forum guide with the crew.

**Comment by SophiaLVP** [comment]
Definitely as you like. I will be waiting.

**Comment by Specifer** [comment]
Guys I need reply if my files are good and doesn't need restrictions only for admins ?

> I'm a newbie and i don't know anything about JS . But Im sure i can help with this .
> At playground\pawn\Elements\AdministratorCommands.pwn
> Replace line
> 
> * [ ]  SendClientMessage(subjectId, Color::Success, "You have been granted temporary administrator rights");
> 
> With ,
> 
> * [ ]   SendClientMessage(subjectId, Color::Success, "You are now a temporary administrator. Kindly read the contents of /guide");
> 
> At commands.js in playground\javascript\features\commands\commands.js
> Add line
> 
> * [ ]
> 
> commandManager.registerCommand('guide', InfoDialogCommand.create('data/commands/guide.json'));
> 
> At playground\data\commands
> Add file guide.json
> 
> [guide.zip](https://github.com/LVPlayground/playground/files/4543648/guide.zip)
> 
> Lastly I don't know anything about scripting , I am just beginning to learn . If I was wrong anywhere please correct it . plus if you want to make it temp admin only command please do so
> 
> Regards ,
> Specifer

Guys I need to know if this works good and ready to be implemented ??

**Comment by Specifer** [comment]
@BeanerLVP , This is really a good call mate  . I hope it gets replaced either with or without admin restrictions . I think there will not be down call for this issue .
Plus admin only restriction is not needed since players won't know the command even exists .

**Comment by BeanerLVP** [comment]
Since no other crew members have proposed further changes, let's proceed with this content:

> As a temporary administrator, there are some key points you should keep in mind:
> 
> 1. Be nice, be respectful, and more importantly, stay calm in all situations.
> 2. Useful commands: /watch, /stopwatch, /p, /fix, /mute, /jail, /kick, /ban, /v, /vr, /flip, /cruise, /weapons.
> 3. Utilize verbal warnings, /mute, /jail, and /kick more often over /ban. Remember, GTA is all about chaos and breaking the rules.
> 4. Avoid banning for minor offenses such as ship-nading, interior-nading, fake timeouts, command abusing in fights, and swearing, when not done excessively.
> 5. Always test for health hacks using /p handofgod and /fix. If they don't work on de-synced players, use /reconnect. Do not ban based on the outcomes of /p burn and /p nuke alone.
> 6. Recording & submitting video evidence in case of suspected aimbot, no-recoil, dmg.cs, and other cheats of such nature is mandatory. The crew shall review it and take appropriate actions.
> 7. Use /crew [message] to send messages to the LVP Crew IRC channel if you require assistance. Always feel free to reach out to us.
> 
> Please visit https://administrator.guide/ for a general overview.
> Remember, this is only a game — don't take things personally. Stay unbiased at all times.
> 
> Thank you for volunteering to assist the Las Venturas Playground crew. We sincerely appreciate your efforts!

**Comment by RussellLVP** [comment]
This was implemented for LVP 48. Thanks Specifer!
