### ISSUE TITLE
/my spawnmoney issues

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#52]
Issue 1:
I have my spawnmoney set to the maximum, $10,000,000, as demonstrated in this screenshot: http://i.imgur.com/HHVbhU6.png . I'm unable to change it, however. Executing "/my spawnmoney 1000" for example will just return "The amount must be between $250 and $10,000,000" as demonstrated here: http://i.imgur.com/NrjHoQ2.png . This happens with any amount, and I was able to confirm it with another player.

Issue 2:
/my spawnmoney does not appear to deduct the chosen amount from your bank account. My bank balance is the maximum, 2 billion dollars, and after killing myself numerous times, the bank balance remained at 2 billion dollars.

**Comment by RussellLVP** [comment]
(1) Is correct, but the message is wrong. The minimum amount of spawn money is $175,000 (wtf?) which will be granted to players for free.

(2) The money is not deducted from your bank account because you have administrator rights.
