### ISSUE TITLE
Remove or replace the admin yellow color from the gang color list

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#520]
I think it'd be appropriate to reserve that color only for administrators. Replacing it with something else to prevent players from picking it in the future & resetting the current selection would be helpful.

Obviously, this is low priority, but I'd just like to file this issue for future reference.

**Comment by RussellLVP** [comment]
That color _is_ reserved to administrators: it will not show up in the colour picker unless the person opening the picker is an administrator themselves.

**Comment by OttoRocket-LVP** [comment]
It does also show for temporary admins. And saves if a temporary admin takes the color.

**Comment by RussellLVP** [comment]
Per [administrator guidelines](https://administrator.guide/), it wouldn't be fair if they did that, in the same way that it wouldn't be fair if an Administrator did that for non-admin-only gangs. Seems to me like this is already captured by our policies, and does not need technical changes?
