### ISSUE TITLE
AutoBan New animations 

### ISSUE THREAD

**Issue by Specifer** [LVPlayground/playground#525]
Alright I thought if we could add some lines if the server detects animations other than it has , then it must respond with a ban on that player . I think this must be a easier one to script , right . Because players who use hacks use animations which is not in our server data . It might be a way to keep away constant hackers .

**Comment by RussellLVP** [comment]
I don't know what this means. `GetPlayerAnimationIndex` for unexpected values?

**Comment by Specifer** [comment]
So I assume there is no way to detect other animations apart from what this server has ?

**Comment by Specifer** [comment]
I see this is not unsolvable at the moment and I'll try to share it if I find this kind of feature . Untill then I'll close this issue .
