### ISSUE TITLE
/set gravity not working for admins

### ISSUE THREAD

**Issue by Specifer** [LVPlayground/playground#526]
I noticed that /set gravity was ignored and didn't even respond with command not found for admins and temp's.  But it seems it works for managers ? It was not working both in staging and real server 's .

**Comment by RussellLVP** [comment]
`/set gravity` is only available for Management members.

https://github.com/LVPlayground/playground/blob/master/pawn/Elements/AdministratorCommands.pwn#L305

**Comment by Specifer** [comment]
Ok I'm closing this issue .
