### ISSUE TITLE
Muted people can still talk in gang chat.

### ISSUE THREAD

**Issue by OttoRocket-LVP** [LVPlayground/playground#527]
When people are muted they can still speak in the gang chat.

This results that our only (last) option for spammers is to ban them where a (long) mute would be enough.

As added option it would be nice if we could completely mute people (including admin chat, or limit it to e.g. 1 message per minute). Some people tend to get angry over this stupid game and simply just need to calm down.

**Comment by RussellLVP** [comment]
This has been fixed with the new communication system.
