### ISSUE TITLE
Improvements for /my allchat

### ISSUE THREAD

**Issue by RickyLVP** [LVPlayground/playground#53]
When a crew member enables allchat (/my allchat on), the players chatting on other worlds are shown like they are talking in main world. It is hard to identify who is in other world and in which world.

If we get world ids before the player's name [e.g. (World:69)(ID:1)Ricky92: bla bla bla OR 
(W:69)(ID:1)Ricky92: bla bla bla], that can tell crew members in which world and what players are talking.

Some players get bugged in minigames and tells about it in the chat (cauz most of them dont know there is @ to contact crew), we can know whats happening with them in which minigame.

**Comment by ghost** [comment]
hmm Good Idea

**Comment by GodeyLVP** [comment]
It's easy.
On `OnPlayerText`
`"(World:%i)", GetPlayerVirtualWorld(playerid),`

-Godey
