### ISSUE TITLE
Adding the option to store money into a gang bank.

### ISSUE THREAD

**Issue by OttoRocket-LVP** [LVPlayground/playground#540]
It would be nice if there would be a bank for a gang that can be shared with the entire gang.

This way the gang can make money together and spend it on weapons, gang encryption, (future gang zone items?) etc.

It also adds the risk of a gang member stealing all the money, what is interesting too in a game like GTA.

**Comment by SophiaLVP** [comment]
How about making a restriction that gang member can withdraw amount no more than 100k, 200k for manager and no restriction for leader as he/she leads the gang?

**Comment by Specifer** [comment]
Ottorocket I seriously think this is a good idea . But we need to face practicalities though . Like lot of players have 2 billion dollars in their account and they can easily withdraw all of it . Putting a restriction on gang account won't matter then . They probably won't use it . But if we consider we need to limit players amount of withdrawal per 5 minutes . Like 25 million is the maximum that can be withdrawn then gang account comes in play . From gang account players can withdraw 100 million at once where the limit of money that it can hold depends upon the the number of managers .
More managers more it has capacity to hold money . Let's see if this is good we will think more ideas for the future enhancement.

**Comment by RickyLVP** [comment]
This used to be a thing back then. Since everyone has 2 billion in their banks, I wonder if bringing it back would change anything.

**Comment by BeanerLVP** [comment]
If I recall correctly, there was an attempt to tweak the economy to make things a little harder for players, but all those efforts were undone due to certain properties having high earnings and whatnot. Almost everyone has more money than they know what to do with, or can easily fill up their personal banks to max capacity with ~15-30 hours of  game play.

In my opinion, this doesn't really contribute anything new to the game play experience. I feel gang members would probably enjoy DM-related features like gang turfs again.

**Comment by OttoRocket-LVP** [comment]
I've seen servers having a gang bank and it showed me the following fun aspects:

- A gang had invited a player to the gang. The player stole all the money and left the gang.
- Another gang would have some of the players online all day to be making money for the gang. Then at the evening the fights would come; They could buy certain perks during those fights with the money they've been gathering the day.

Another spin of thought is:
We could make it impossible for players to store money into the gang bank. (To have no impact of our curren economy) and instead:
- They earn money for each rival gang kill they make.
- They earn money for controlling (future) gang zones.
- They earn money for buying a gang related property. (e.g. gang base)

The money they can spent on certain things:
- Limited amounts of persistent spawn weapons for a limited time.
- Spawn certain (exclusive) vehicles for the money.
- Get a rocketlauncher/minigun with limited ammo? (Not really sure about that one)
- Buy some goodies to tune there gangzones.
- Buy some cosmetic items for the gang.
- Buy a DM arena for the gang to train at.

**Comment by SophiaLVP** [comment]
> Another spin of thought is:
> We could make it impossible for players to store money into the gang bank. (To have no impact of our curren economy) and instead:
> 
> * They earn money for each rival gang kill they make.
> * They earn money for controlling (future) gang zones.
> * They earn money for buying a gang related property. (e.g. gang base)
> 
> The money they can spent on certain things:
> 
> * Limited amounts of persistent spawn weapons for a limited time.
> * Spawn certain (exclusive) vehicles for the money.
> * Get a rocketlauncher/minigun with limited ammo? (Not really sure about that one)
> * Buy some goodies to tune there gangzones.
> * Buy some cosmetic items for the gang.
> * Buy a DM arena for the gang to train at.

This seems amazing and promising real fun and challenge. I agree with quoted points only

**Comment by RussellLVP** [comment]
We now have a gang bank :) I love Holsje's suggestions - let's figure out more way to have gangs spend it.
