### ISSUE TITLE
JavaScript vehicles

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#552]
From what I understand, the merchant vehicle is randomly selected. Today I came across one that was on a roof, which is impossible to drive off:

![Untitled](https://user-images.githubusercontent.com/65047759/81453198-cf6ba080-9180-11ea-9c4b-25a67843ef8f.png)

I figured I would delete use /v delete to get rid of it, since there is no benefit in this vehicle being up here. It turns out it's not a vehicle managed by JavaScript, so it seems that won't work.

I'm more so curious about how a vehicle ends up in a state where it is _not_ considered to be managed by JavaScript, and if there's a possibility of converting existing vehicles over to JavaScript to allow such issues to be taken care of by in-game admins in future.

**Comment by RussellLVP** [comment]
Pawn, basically :) This should've been fixed now. Thanks for the report!
