### ISSUE TITLE
Incorrect price displayed on IRC when selling properties

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#562]
If you buy a property, the correct price is shown on IRC, like so:

 *** George (Id:4) has bought the 24/7 property for $4,500.

If you then go to `/sell all`, IRC always show $0, i.e:

 *** Luce (Id:1) has sold all their properties for $0.
 *** George (Id:4) has sold all their properties for $0

In-game, everything is normal:

![image](https://user-images.githubusercontent.com/65047759/81613354-3afa7b80-93d6-11ea-9076-cc87188387f4.png)

**Comment by RussellLVP** [comment]
This has been fixed indeed :) Thank you for the report!
