### ISSUE TITLE
Property incomes stop stacking about reaching the bank's limit

### ISSUE THREAD

**Issue by DeerHunterLVP** [LVPlayground/playground#565]
- Once the players have their bank accounts full (Or about to be full; in other words, if the amount of money we receive from properties is higher than amount of money required to replenish our bank acc's) , they won't receive any more earnings from properties. 

- We get notification that money is still being added to our bank accounts, which is not the case. Then money has to be stored manually by typing the correct amount, and once we reach the balance limit, we'll stop receiving any. 

- Before we would keep receiving cash once our banks were full.

**Comment by RussellLVP** [comment]
This has happened 160 times in the past 4 days, good catch. Will fix.
