### ISSUE TITLE
Easing certain restrictions on !supported, !getvalue, and !setvalue

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#567]
According to the new NuwaniJS documentation, !supported, !getvalue, and !setvalue are management commands. In the previous versions of Nuwani, administrators also had the ability to use these commands, but with certain fields being restricted only to management members. 

My suggestion is to ease some restrictions by allowing administrators (@) read/write access to the following fields:

- custom_color
- death_message (to be able to reset inappropriate messages)
- jailed
- last_ip
- money_bank (to refund lost money due to server restarts, wrongful kicks/bans, etc)
- money_bank_type
- money_bounty
- money_cash
- money_debt
- money_spawn
- preferred_radio_channel (maybe, maybe not - doesn't really matter)
- skin_id

Also, if the level of the user executing !supported is administrator (@), display only the aforementioned fields — ones that they can view and edit.

Other than that, let's continue restricting the remaining fields, as I see no reason for administrators to edit other account information like:

`stats_carbombs,  stats_drivebys,  stats_exports,  stats_fc_deaths, stats_fc_kills, stats_heli_kills,  stats_minigame, stats_packages, stats_reaction, online_time, death_count, kill_count, is_developer, is_vip, last_seen, level, validated.`

Website profiles and /getstats are always available for the purpose of viewing statistics.

Managers can continue handling account related tasks like stats resets & merges, VIP access, etc.

**Comment by SophiaLVP** [comment]
I will not jump in this discussion with my views as I know nothing about them but if you are registering this issue, it might need some eyes to look at so I agree with Beaner
