### ISSUE TITLE
Doing /kill while in a minigame will make you glitched. (weapon-config.inc)

### ISSUE THREAD

**Issue by OttoRocket-LVP** [LVPlayground/playground#568]
When you do /kill while in for example /race 1 you'll become glitced to no fix but a relog.

Your health will stay at 0, you will respawn however. Using /fix or anything will not fix this situation.

**Comment by Specifer** [comment]
I can't /kill myself in a Minigame (Main Server) . And i tried it in staging (as an admin ) and it doesn't work ?

**Comment by OttoRocket-LVP** [comment]
I went into /race 1 for this to work.

**Comment by RussellLVP** [comment]
We probably won't enable server-side damage now that we've got lag shot too, so tentatively closing the issue.
