### ISSUE TITLE
A new !help command with certain aliases

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#569]
This is what I observed in #lvp.echo yesterday:

> LVP_968 (Mibbit@gtanet-vf4.ire.217.46.IP) has joined #lvp.echo
<LVP_968> !cmds
<LVP_968> !cmd
<LVP_968> !players
<Nuwani> Online players (2): [CP]Freakins, dididada
<LVP_968> !cmds 
<LVP_968> !admins
<LVP_968> !admin
<Nuwani> Error: Sorry, this command is only available to administrators.
<LVP_968> !stats
<LVP_968> !say
<Nuwani> Error: Sorry, this command is only available to administrators.

A !help command with aliases like !commands, !cmds, and !cmd would be useful for users unfamiliar with IRC or our other commands. The output can include a list of Nuwani commands available to regular players and VIPs:

`Available IRC commands: !getid, !getname, !msg, !players, !pm, !vip, !discord`
`To register an account, visit: www.sa-mp.nl`
`Nicknames, passwords, and aliases can be managed in-game with the /account command.`

**Comment by Specifer** [comment]
@BeanerLVP , I have a doubt there . What does !discord do ?

**Comment by BeanerLVP** [comment]
> @BeanerLVP , I have a doubt there . What does !discord do ?

Displays a link to our discord server:
<+NuwaniJS> LVP Discord: https://discord.sa-mp.nl/

**Comment by RussellLVP** [comment]
@Specifer has implemented this - thank you! Closing.

**Comment by BeanerLVP** [comment]
@Specifer - thank you for implementing this! :)

Can you also add the following aliases for !help:
_!commands, !cmds, !cmd, !info_
