### ISSUE TITLE
Feature adddition in an /account

### ISSUE THREAD

**Issue by SophiaLVP** [LVPlayground/playground#570]
I have been observing lately and something clicked in my mind. We can see our aliases and everything. It would be nice to have a source in /account within alias section where our original nickname to be seen. In addition, I am not familiar with the management features but this can certainly help in recovering the lost accounts if a player forgets his/her nickname (or accidentally/intentionally removes all aliases from his account and all his/her leads put to an end). It happened with myself not so long ago so I thought it can contribute fair role towards administration faculty

**Comment by RussellLVP** [comment]
I guess we could have an _Information_ section in the `/account` command, but I'm not sure what else we would surface there.

On a bit of a tangent, something else to consider is showing players their most recent IP addresses in `/account`, so they can see if someone else might've _hacked_ them.

**Comment by Specifer** [comment]
Author , could you please explain what you're proposing in this issue to have it running ?

**Comment by SophiaLVP** [comment]
I think everything is explained in there.

**Comment by Specifer** [comment]
what feature do you need in account , Already administrative faculty as !aliases to track all the aliases and could you please explain what do you want as a feature ? (even if everything is explained there , care to be more specific ) Forgot nickname , then you would have to ask crew help and 
>help in recovering the lost accounts if a player forgets his/her nickname (or accidentally/intentionally removes all aliases from his account and all his/her leads put to an end )

How ?

We already can use IP for tracking accounts , what more do we need ?

**Comment by SophiaLVP** [comment]
What about the main nickname all aliases are co-related with? For instance, consider this scenerio. You were long gone for like 4-5 years and suddenly you return back in to the game. You enter with one linked alias (keep in mind that you forgot your original nickname. All you remember is an alias). Later on you want to know your original nickname so that you can join with that. Okay you look into /account but still it doesn't show your nickname. It's a dead end (That's not a scarcasm so please not to consider it one). Now managers have more things to look at and many of them are real busy, /account can add a feature both for regular and VIP players to see their current nickname along with aliases. Is it understandable now?
And about manager's feature, I think they know what I am trying to accomplish here with this enhancement ticket.

**Comment by Specifer** [comment]
!players (oneofthealias) gives details of the main alias . Just saying managers can say what they want about this ticket . 
![Screenshot_20200515_134531_com irccloud android](https://user-images.githubusercontent.com/64122067/82027943-92d50300-96b2-11ea-990a-dd55ca29c371.jpg)
[Screenshot_20200515_134531_com irccloud android](https://user-images.githubusercontent.com/64122067/82027841-7a64e880-96b2-11ea-9420-403ee9c351f6.jpg)

**Comment by RussellLVP** [comment]
I think this'd make a worthwhile addition, let's stick it on the list for LVP 45. I just have to figure out the best way to surface it in `/account`. Ideas welcome.

**Comment by SophiaLVP** [comment]
I have thought of some design. Allow me to share it with you.
Account box with options as follow:
1. View account information: A player can track and view his/her current nickname, current aliases, registered date and recent session entries.
2. Ban and kick details: Just as same as we have right now.
3. Manage account settings: A player can manage his account nickname(rename option) password and aliases. Some more game settings to be added so that panel doesn't feel empty and getting rid of using commands again and again to enable them. That's up to you Russell. I don't exactly know what kind of settings can become a part of in this option.
4. Account status: Shows the current status of the account as a regular or VIP. If a player is not a VIP then an extra note displays which inform players about donating for VIP and ensuring exclusive VIP features. 

What do you think of this?

**Comment by RussellLVP** [comment]
Thank you for the suggestions!

I've added a "view account information" dialog that contains the following information:

- Username
- E-mail address
- Date of registration
- Level
- Karma
- Number of sessions

In addition, for VIPs and people who've donated, it will further display:

- VIP status
- Total donation amount

These two fields will only be accessible by the player themselves, and by Management, but not by administrators looking at other people's details.

I think that's enough to mark this issue as fixed. Thank you for the suggestion!
