### ISSUE TITLE
Reduce the interval between nickname changes

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#572]
Currently, both VIPs and regular players are required to wait 30 days between nickname changes.

Suggestions:

- VIPs may change their nicknames every 7 days.
- Regular players may change their nicknames every 14 days.

Crew members can always override this if necessary.

**Comment by SophiaLVP** [comment]
7 days for VIP members will be too short time now and personally I don't like it

**Comment by RussellLVP** [comment]
I agree with Sophia - this is why we've got aliases, which they can already amend every seven days.

I'd be OK reducing the interval to once every 14 or 21 days however. Would that work?

**Comment by BeanerLVP** [comment]
> 
> 
> I agree with Sophia - this is why we've got aliases, which they can already amend every seven days.
> 
> I'd be OK reducing the interval to once every 14 or 21 days however. Would that work?

Sure, 14 or 21 seem alright.
Do we have a limit on the number of active aliases VIPs can have?

**Comment by Specifer** [comment]
Yes it's 2 aliases .
