### ISSUE TITLE
Increase the earnings ( bounties / minigames / exports / merchant )

### ISSUE THREAD

**Issue by DeerHunterLVP** [LVPlayground/playground#577]
* Players that are on killing spree aren't worth killing considering the very low amount of bounty prize being put on their head. I suggest this amount of money should be increasing mutually with the wanted level. 

For example, for killing a player who has a killing spree of 20, you'd receive only 6k. Thats extremely low.

* Some minigames such as robbery take a looong time before coming to an end. I suggest that players should be rewarded better after winning one. Imo all the rewards from winning minigames should be increased. Nothing drastical, so that players can't recognise this opportunity as money farm, but a slight improvement would be welcome.

* Amount of money received both from exporting and merchant's mini-mission could also welcome an update.

**Comment by SophiaLVP** [comment]
I propose an addition of $1000 each kill in a kill spree. If a player reaches on a spree of 20, 20 * 1000 = $20000 should be the prize for ending the killing spree of that player. With high sprees, a high amount of cash reward should be ensured

**Comment by Specifer** [comment]
Let's hear the authorities words on this . They will collect some good data and decide well and after that we can have a discussion about that.

**Comment by Specifer** [comment]
Shall we close this issue?
