### ISSUE TITLE
Minigames being bugged

### ISSUE THREAD

**Issue by AzKiller** [LVPlayground/playground#578]
There seems to be an issue with some of the minigames like /ww or /sawnoff, players do not loose health when they get hit (even if you hear the hitmarker sound)

Same issue with /fight

Could be related to the vw's ?

Cheers,

AzKiller.

**Comment by Specifer** [comment]
Yeah,Az and me did some important discovery 
1.Punch Damage Takes place.
2. this problem persists in all virtual worlds.
3. Weapons don't do damage at all.

**Comment by AzKiller** [comment]
Update : Players cannot get damage with weapons in all other worlds except /world 0, however damage can be dealt while punching other players in /world 1->99 (same goes for minigames such as /ww & /sawnoff

**Comment by Specifer** [comment]
Edit: Punch , Grenade and Spraycan do damage as well .

**Comment by SophiaLVP** [comment]
All weapons work fine and damage is made on a player driving any kind of vehicle. On the opposite end, a drive-by can deal damage on foot player easily.

**Comment by RussellLVP** [comment]
Should be fixed with the following commit, which I'll restart the server for in a second:
https://github.com/LVPlayground/playground/commit/d74c05a40b4c3710321def083635e7d7d0df3cab

Thank you for reporting this, and for the thorough research!!
