### ISSUE TITLE
Back button for /lvp settings

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#579]
Now that there are significantly more features under /lvp settings, can we have a 'Back' button to make it easier to navigate different options and categories? Having to cancel -> use /lvp settings -> select option/category each time is quite annoying.

Please implement this if it's not too much work!

**Comment by RussellLVP** [comment]
This is quite hard unfortunately. Use of `/lvp settings` should be quite rare, so I don't think this is the best use of our time. Please re-open if you disagree!

**Comment by BeanerLVP** [comment]
It's minor, but definitely not worth spending any significant time on, considering there's so much else to do.
