### ISSUE TITLE
Mansion interior doesn't have armour 

### ISSUE THREAD

**Issue by Specifer** [LVPlayground/playground#583]
![Screenshot (169)](https://user-images.githubusercontent.com/64122067/82113425-9aa8ac00-9773-11ea-8216-88f47358f918.png)
I actually checked the files and there is no problem with xyz axes like in last issue #513  , So i Rebought the armour pickup and it first appeared in the right place and instantly disappeared .

**Comment by Specifer** [comment]
Could this be related to maximum no of samp pickups ?

**Comment by Specifer** [comment]
In staging it works fine probably

**Comment by Specifer** [comment]
@RussellLVP , Shall I close this . Is this due to pickup streamer ?

**Comment by RussellLVP** [comment]
This probably has been fixed, let's mark it as such.
