### ISSUE TITLE
Sniper damage bug

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#584]
If I recall correctly, ever since the headshot feature for snipers was released, there's been a bug where players sometimes stop taking any damage from snipers. I have no idea what triggers this. Asking players to reconnect is the only way to have it fixed, but most of them tend to take advantage of it and abuse the bug.

I often see several reports about this on a daily basis. Can something be done?

**Comment by RussellLVP** [comment]
Server-sided damage will help here, but I can't find anything in the script that would cause and/or influence this. We never block damage, rather, we only apply more for headshots, thus they cannot be related.

Let's close this in favour of further investigation of server-sided damage.
