### ISSUE TITLE
Cash wont transfer between gaming sessions

### ISSUE THREAD

**Issue by DeerHunterLVP** [LVPlayground/playground#587]
- We usually spawn in the server with 0 cash in our hands, that's the main issue. This appears often, both after logging in, and dying/respawning. Doesn't happen all the time, but quite often.

- If we logout with some amount of money in our hands, next time we join the server this money will be gone. Before these stats would be saved and on login we would receive the same amount of money we logged out with.

**Comment by SophiaLVP** [comment]
I haven't considered it yet. Do all players have this problem or just you?

**Comment by DeerHunterLVP** [comment]
> I haven't considered it yet. Do all players have this problem or just you?

Yes, everyone faces the same problem.

**Comment by SophiaLVP** [comment]
I have noticed that /my spawnmoney is disabled for everyone. Is this the reason we all are spawning with $0 cash?
