### ISSUE TITLE
Hit sync bugs

### ISSUE THREAD

**Issue by OttoRocket-LVP** [LVPlayground/playground#590]
We found the following bugs during a test run:

- No godmode on ship.
- Health pickups don't work
- After a minigame is concluded you'll spawn with the health you had in the minigame.
- /kill does not gave the kill to the last person who shot you anymore.
- After a minigame (e.g. /random) you'll respawn at the LV Golf area.
- Vending machines don't regenerate health.

**Comment by SophiaLVP** [comment]
Certainly. I am familiar with the bugs especially point 02, 03 and 05. But what's up with the vending machines? I have rarely seen one around though

**Comment by RussellLVP** [comment]
Thanks for testing! Like I said on the other issue, the likeliness of us enabling this is low, so let's tentatively close this issue.
