### ISSUE TITLE
Move from Passenger to Driver

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#591]
a command to move from passenger to driver just if the driver died or left the car, if is short command would be nice. 
Would improve some situations where the driver disconect or crash, and passengers just arent able to do anything.

Thanks for ur time!

**Comment by HaloLVP** [comment]
Remember to add a exceptions like Trains, as sometimes drivers arent in the train.

**Comment by Specifer** [comment]
Cool thing . What about this if vehicle health is less than 380 they can't change.  But greater than this can enable the command .
