### ISSUE TITLE
Restriction on /lvp settings

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#593]
In order to use /lvp settings, the user needs to be logged in with a registered account. As long as crew members use /modlogin to gain their regular access level with some _other_ undercover/unregistered/registered nickname, does it matter whether or not they're logged in to use this specific command?

If there's no particular reason, can we please get rid of this restriction?

**Comment by RussellLVP** [comment]
Using `/modlogin` publishes `OnPlayerLogin`, so this should _just work_. What error message do you get?

**Comment by SophiaLVP** [comment]
We need to carve out the things which are not working out when joined in game using /modlogin.
Did you test it yourself @BeanerLVP?

Edit: Ricky and I tested this issue and Beaner is right. /lvp settings, /lvp access, /announce, /mute, any /v command except /v <model>, /show are the commands which are not working with an unregistered nickname.

**Comment by BeanerLVP** [comment]
> Using `/modlogin` publishes `OnPlayerLogin`, so this should _just work_. What error message do you get?

`Error: Sorry, you must have a registered account in order to use this command.`

In addition to the commands Sophia listed, even /idlers doesn't work. Some crew commands do, some don't.

**Comment by Specifer** [comment]
This is better this way. Under-covers are just a temporary means of Administration, whether if situations arose, They should use any registered account to access these. I had tested them and as long as its a registered account + modlogged, It works fine. From the script side, I probably think its for the best and to avoid future bugs by making unregistered account access those. There is a lot of things not accessible like houses etc by unregistered modlogged ones, so if /lvp is supposed to be accessible, so does the houses too.
