### ISSUE TITLE
Implement !clear, !mute, !unmute, and !muteall for Nuwani

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#596]
Similar to the in-game functions, I request the following to be implemented in Nuwani:

1. **!clear** - To clear the main chat in case of server advertisements, highly inappropriate language or website links, spamming, etc.

2. **!mute [id / nickname] [duration]** - It'd be convenient for crew members to mute users via IRC if they happen to find something inappropriate being said in #lvp.echo. Also, now that mutes are independent of sessions, this could enable crew members in dealing with reports by muting users even when they're offline, so that they remain muted for the specified period the next time they're online.

3. **!unmute [id / nickname]**

4. **!muteall [on / off]** - Not very important, but since we now have that function in-game, I figure it could come in handy for important announcements like server restarts (informing people to sell their properties, bank their money, etc).
5. **!jail [id / nickname] [duration]** - I hate not being able to jail striker at login anymore. Help?!
 Just kidding, it's not really required on IRC. :)
I would, however, recommend making jail time independent of sessions (like mutes),

Side note: We also need !givetempadmin & !takeadmin along with notices, which I've already mentioned in issue #532.

**Comment by Specifer** [comment]
The !givetempadmin and !taketempadmin is available in v2 of NuwaniJS. I hope it is going to be implemented.

**Comment by RussellLVP** [comment]
Thank you for the report!

The !mute, !muted and !unmute commands have been implemented and will be available soon.

Regarding the other commands:

- **!clear**: I've not yet seen a need in the past ~8 weeks. Let's wait until we're certain we need it.
- **!muteall**: Use of blocking all communication is extremely rare. I've not yet seen a need either, particularly from IRC.
- **!jail**: Agreed, but this will depend on the jail system moving to JavaScript.
- **!givetempadmin** & co: Agreed, but here too there's some stuff that needs to migrate.
