### ISSUE TITLE
/mute and /unmute: syntax display errors

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#599]
The syntax for /mute and /unmute aren't displayed. Instead, the following error appears:
`Error: Sorry, no player could be found for "[null]".`

**Comment by Specifer** [comment]
there is this type of callback missing

if (Command->parameterCount(params) != 1) {
            SendClientMessage(playerId, Color::Information, "Usage: /mute ID minutes reason ");
            return 1;
        }

**Comment by OttoRocket-LVP** [comment]
What about picking the executing person as player_parameter if none is given.

So if you /mute without using an ID you'll just mute yourelf.

**Comment by SophiaLVP** [comment]
> What about picking the executing person as player_parameter if none is given.
> 
> So if you /mute without using an ID you'll just mute yourelf.

Isn't it a bit futile muting yourself?
