### ISSUE TITLE
Freezing on spawn

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#6]
http://trac.sa-mp.nl/lvp/ticket/1572

eF.Holsje:

> Now I'm currently ID 36 (Not sure if it's ID related though) I'm getting frozen every time I spawn. (I have to unfreeze myself)
> 
> I've noticed players and other crew members having the same issue.

Granny:

> Changes were made in r5108 to try and correct this. I don't believe this patch is live yet (as other commits on that same date, such as the raising of spawnmoney, are not yet live either).
> Whilst r5108 should mean that a normal /fix (rather than /p [id] unfreeze) will solve this, we still need to identify what causes this issue.

**Comment by ghost** [comment]
I haven't seen or heard of this problem for quite some time. Given the large number of commits recently, perhaps it's fixed now. I propose that we close this issue out for now and re-open it if occurs again.
