### ISSUE TITLE
Minor house related tweaks

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#600]
1. When an administrator teleports to another player's house, the notice displayed is:

> *** LVP_213 (Id:2) has teleported to **one of their houses**.

It doesn't display the house owner's name. Not really a big deal, but I felt I should point out the inaccuracy of it.

2. Minor annoyance: when the **/house goto** menu is opened, there are only [options](https://i.imgur.com/3MqlRx1.png) to go through all the pages or select a house. The cancel button only appears on the [last page](https://i.imgur.com/BK3eMFy.png), and ESC doesn't close the dialog either -- instead, it advances the page number. Having a cancel or back button on each page of the dialog would be useful. However, it's not at all a priority; not having a fix for it would be okay.

**Comment by SophiaLVP** [comment]
Absolutely. We do need a cancel button

**Comment by RussellLVP** [comment]
I have fixed the first suggestion, the message will now say:
```*** LVP_213 (Id:2) has teleported to "striker's beach resort", a house owned by striker.```

We cannot implement your second suggestion. All of this infrastructure is standardized across our code, so the only way for us to add a `Cancel` button everywhere is to drop the ability to paginate menus, which is not realistic and severely harms user experience elsewhere.

Note that you can use `Esc` or similar keyboard shortcuts to close the menu, too.
