### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by SophiaLVP** [LVPlayground/playground#603]
I am making this ticket on behalf of my fellow friend, Finisha.

1. A script for identifying fake car entry or script that can forbid fake car entry automatically (he mentioned something like blocking or freezing the player). 

2. Suggestion about new system (the one we have in staging server right now).He suggests this damage system to be implemented on main server but not until #590 gets resolved first.

3. Anti-cheat upgradation.

4. Proper data analysis for determining player's accuracy and detecting aimbot cases. I think he asks for a script which can process such tasks for administration faculty.

Ideas welcome

**Comment by RussellLVP** [comment]
To be clear, we're talking 8+ weeks of work here. While I very much agree with the sentiment behind these suggestions, it's important to be realistic about the work that's involved in implementing them.

**Comment by SophiaLVP** [comment]
If you start a little bit of work from now on, I hope that it can be completed before LVP 48 upgradation nearly around August. I know that's too much burden to bear but we do need it.

**Comment by RussellLVP** [comment]
I think we've sufficiently satisfied the requests in this ticket. Closing.
