### ISSUE TITLE
Additional auto-announcements via Gunther

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#604]
I'd like some /show commands to be implemented & added to Gunther's auto-announcement list.

1. /show minigames
> Be sure to explore our exciting minigames like /robbery, /brief, /rivershell, /waterfight, /random, /haystack, and /has!

2. /show derby
> Have you tried our derbies yet? Use /derby to sign up!

3. /show stunt
 Love stunting? Use /jump to explore our stunt zones!

4. Reduce the frequency of /show irc, /show discord, and /show report if necessary; and consider removing /show beg from the auto-announce list if you think it's fine to do so.

I feel some of these minigames aren't played very often, and now would be a good time to remind active players about these features as we have a variety of them interested in different forms of gameplay nowadays.

**Comment by Specifer** [comment]
@RussellLVP, Where is /show moved too. I'll take care of simple things.

**Comment by RussellLVP** [comment]
There was a comment by @Specifer here, where did that go?

Gunther's command list is located at the top of `javascript/features/communication_commands/communication_commands.js`. The actual messages are located in `data/show.json`.

**Comment by Specifer** [comment]
Ok Ty . I have located it 😃 . There seems to come an error from communication_test.js that expected value 1 but got 0 .
Edit: Seems to work fine now !

**Comment by Specifer** [comment]
Done solving this in PR !!

**Comment by SophiaLVP** [comment]
Good job specifer 👌

**Comment by RussellLVP** [comment]
This is done. Thank you @Specifer!
