### ISSUE TITLE
Substitutions under /lvp settings can't be deleted

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#606]
When an attempt to delete a substitution is made, the appropriate notice about its confirmation is displayed, but the entry doesn't actually get removed.

Deletion works fine with blocked words, though.

**Comment by OttoRocket-LVP** [comment]
This only happens if the word is also blocked.

A work around would be:

1. Remove the blocked wod.
2. Remove the substituted word.
3. re-add the blocked word.
