### ISSUE TITLE
False "Multiple weapon cheat detections" bans

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#61]
While I was Playing /rocket With my Friends ! 
When It got Done ! lego  Kicked/banned  Me 
<02%Nuwoni> 02[29] 03**\* Hopper left the game (kicked).

Please Hope The Bug must be fixed

**Comment by ghost** [comment]
This has been happening for quite some time I believe:

In Hopper's instance:

[14:50] <&Nuwani> [23-12-2015 15:49:53](ban by LVP): Multiple weapon cheat detections. (IP: _censored_)

**Comment by HopperLVP** [comment]
Censored ?

**Comment by RussellLVP** [comment]
I think https://github.com/LVPlayground/playground/commit/6a651198641fb458beba7525d0919e40ea4958a5 should fix it. Let me know if it didn't.

**Comment by ghost** [comment]
Thanks Russell, however I believe there may still be an issue with auto-bans.

Here's a few threads within the past 12 months where there looks to be similar, false bans: 

https://forum.sa-mp.nl/thread-33585.html
https://forum.sa-mp.nl/thread-33080.html
https://forum.sa-mp.nl/thread-32747.html
https://forum.sa-mp.nl/thread-32557.html

**Comment by ghost** [comment]
Another case of this happening yesterday:

< Sinned > So, I got banned by the auto-ban system for ''multiple weapon cheat detections'' while in a minigun duel. 
< Sinned > This isn't the first time it's happened and I'd appreciate it if you could unban me, please.

I am firmly of the belief that this is a programmatical error and not a case that the player actually did use cheats.

**Comment by xhoogland** [comment]
Do we have any recent examples?

**Comment by ghost** [comment]
We do, this happened last night:

> [11/01/2017 - 19:19:20] *%Nuwoni:%#lvp.echo* *** YoMatatan (Id:31) has /taxi'd to The Ship (#0).
> [11/01/2017 - 19:21:32] <%Nuweni> *** YoMatatan (Id:31) has been killed by Legeoner (Id:15): Sniper Rifle
>[11/01/2017 - 19:23:06] *%Nuwoni:%#lvp.echo* *** [CP]Holsje (Id:13) has started a #2 minute KillTime in the mainworld (WorldId:0).
> [11/01/2017 - 19:23:10] <%Nawani> *** AmmaRz (Id:28) has been killed by YoMatatan (Id:31)
> [11/01/2017 - 19:25:26] *%Nuwuni:%#lvp.echo* *** Banning YoMatatan (Id:31) for multiple weapon cheat detections.
> [11/01/2017 - 19:25:27] <%Nawoni> [31] *** YoMatatan left the game (kicked).

What interests me most is this line:

> [11/01/2017 - 19:23:10] <%Nawani> *** AmmaRz (Id:28) has been killed by YoMatatan (Id:31)

The weapon wasn't specified, like it would be normally. I also notice this for other players, but they didn't get auto banned:

> [11/01/2017 - 19:23:14] <%Nuwoni> *** [HM]Hoody (Id:14) has been killed by Thunder_God (Id:29)
> [11/01/2017 - 19:23:16] <%Noweni> *** (R2D)WooglitZa (Id:10) has been killed by AmmaRz (Id:28)
> 

I just tried to re-produce it by starting a 2 minute kill time like Holsje did (with no specific weapon) and I was unable to

**EDIT: It appears that the weapon doesn't get specified if the player uses a grenade to make the kill. But that doesn't seem to cause an autoban, as I just tested it.**

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
