### ISSUE TITLE
Death match games and /Race not being considered as minigame

### ISSUE THREAD

**Issue by Specifer** [LVPlayground/playground#622]
When someone does /race and /robbery or /ww , /waterfight and /race or etc . They get signed up for all. Last time I checked there was a return call with "you already sign-up for another minigame". So it seems the that dm games and /race doesn't come under minigames. But when I do /robbery, /waterfight it doesn't allow me .

Plus : in infodialog.pwn could anyone add case 2 for race command, it seems to be missing.

**Comment by RussellLVP** [comment]
Correct, that's because minigames are moving from Pawn to JavaScript, and the two are quite disjoint right now. With LVP 45 we introduced the new Games API, which will make this a lot easier.
