### ISSUE TITLE
Respawning in main world after death in /deathmatch

### ISSUE THREAD

**Issue by RickyLVP** [LVPlayground/playground#623]
The title says it all. When you enter a deathmatch, you spawn in another world but after you die, you respawn in the deathmatch area but in the main world where others can interfere.

**Comment by Specifer** [comment]
Wait what? 
>You respawn in the deathwatch area but in the main world where others can interfere 

Issue #380 is problematic, how can you say others interfere mate when compared to that?

**Comment by OttoRocket-LVP** [comment]
The following commit: https://github.com/LVPlayground/playground/commit/6c19579986fe0b9096f2fe6e78466c0e3dffa540 will "quickfix" this by delaying the world modification.

When this gets refactored to use the new Games API we should have a better fix.
