### ISSUE TITLE
!lastbans is verbose

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#624]
Only 5 recent bans are displayed via !lastbans on IRC, while 10 are displayed in-game.

`Jon_San (11.111.11.111, 2 hours ago by [CP]Humza)`

I recommend truncating the "by [name]" part and displaying at least 10 names via IRC. !why can always be used to check who banned the user.

**Comment by Specifer** [comment]
Beaner, from my opinion (which could be stupid:D), The more details the merrier.

**Comment by BeanerLVP** [comment]
> 
> 
> Beaner, from my opinion (which could be stupid:D), The more details the merrier.

More information is exactly what I'm asking for.

**Comment by RussellLVP** [comment]
Could you explain the situation in which this was an issue? I checked the recent usages of `!lastbans`, and all of them showed results from at least the past ~12 hours.

The Ban Portal contains all recent entries, with the ability to search, filter and sort:
https://sa-mp.nl/players/banlog.html

**Comment by BeanerLVP** [comment]
It hasn't really been an issue. You're right, a crew member available on IRC has other commands and the ban portal at their disposal.
