### ISSUE TITLE
https://donate.sa-mp.nl doesn't work

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#629]
[This](https://i.imgur.com/2yf11pA.png) is the information displayed under /donate.
Ideally, https://donate.sa-mp.nl should redirect to https://sa-mp.nl/about/donations.html

**Comment by RussellLVP** [comment]
Thank you, this has been fixed for LVP 46! We'll be using https://sa-mp.nl/donate from now on.
