### ISSUE TITLE
Modify the default access levels of certain commands

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#637]
I suggest modifying the default access level from "Management members" to "Administrators" for the following commands under /lvp access:

- /boost
- /fancy
- /flap
- /fly
- /kickflip

Don't see why they should be restricted. We change them each time the server restarts, anyway.

Additionally, since /isolate doesn't work as intended and isn't really required, we can probably get rid of it.

**Comment by RussellLVP** [comment]
Please do not make `/fly` available to administrators. It puts significant load on the server.

I'm not too worried about the other commands. How are administrators making sure that any use of these commands is done fairly in respect to players?

**Comment by OttoRocket-LVP** [comment]
I do use  /isolate from time to time on cheaters.

Isolating them and fixing them after will make them.. isolated.

**Comment by Specifer** [comment]
> How are administrators making sure that any use of these commands is done fairly with respect to players?

IMO Players can request not to use commands on them to admins IF used unfairly. If Still, they do, they have all the liberty to make a complaint on them, right?

**Comment by BeanerLVP** [comment]
> Please do not make `/fly` available to administrators. It puts significant load on the server.

Sure, I wasn't aware of that.

> I'm not too worried about the other commands. How are administrators making sure that any use of these commands is done fairly in respect to players?

While I cannot answer that directly, I think it's safe to say that these commands aren't being abused, judging from the lack of complaints on the forum. There are no reports about administrators misusing various other /p or /v commands, either, so I think it should be okay.

> I do use /isolate from time to time on cheaters. Isolating them and fixing them after will make them.. isolated.

Alright, let's keep it then. I wasn't aware of that workaround.
