### ISSUE TITLE
Using Exclusive Staff skins

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#647]
if you enter tha game as "Halo" or "Russell" or "Peter" wich they have restricted skins.
Players just have to do "Play" without logging, Server will give them a random unregistered nick,
then they just have to /my skin load. And the skin of the first user they joined game in this case "Russell" will be given to this person.
in my previous issue i uploaded a pic with Russel Skin, Sorry bro :3 

thanks for ur time!

**Comment by RussellLVP** [comment]
Not at all, please keep abusing me :)
