### ISSUE TITLE
Unregistered nicknames Achievements

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#648]
somehow the server save the achievements of unregistered nicks. if u manage to do the 200 tags in unregistered account, whoever enters with that random name given by LVP itself will be able to /nrg /infernus etc. 
Dont think this should be working like that, not like someone unregistered would do the 200 achievements.
Didnt test further would take time and painful but clearly something isnt right there.
![achievements 2](https://user-images.githubusercontent.com/22722462/83340819-f54a1800-a2dc-11ea-880f-0c36612f9bc9.png)

Thanks for your time.
got some other minor bugs im working with but most of them consist in unregistered chars. not so critical.

**Comment by RussellLVP** [comment]
This will be fixed in LVP 47, as we have rewritten the achievement system. Thank you for the report, good catch!

You say that "not like someone unregistered would do the 200 achievements", but mind that we've got Eagle_Force_One, who actually does this every single day. It's amazing.
