### ISSUE TITLE
in staging lots of cmds dont work

### ISSUE THREAD

**Issue by Specifer** [LVPlayground/playground#653]
In Staging, Only if I leave a single gap and enter, the command actually works or else it throws error. I think this might be because of the plugin yesterday Russell? Maybe ?

**Comment by RussellLVP** [comment]
Can you clarify please? What works, and what does not work?

**Comment by OttoRocket-LVP** [comment]
E.g. "/lvp" doesn't work ("/lvp " does).

In order to do "/lvp settings" you have to do "lvp__settings_" (add extra spaces).   (Where _ = space)
Same for "/nrg" using "/nrg " works.

"/taxi" does work.

**Comment by Specifer** [comment]
This might be stupid to conclude but javascript commands have error while pwn commands don't, because admisitratiorcommands.pwn and taxi.pwn?

**Comment by SophiaLVP** [comment]
I recently created an account on staging server. I can't login with the password I registered with.

**Comment by RussellLVP** [comment]
Thank you for the bug reports, and all the additional information! This has been fixed.

@SophiaLVP I have deleted your account, please feel free to use `/register` again.
