### ISSUE TITLE
House outside settings

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#655]
Similar to previous bug, but this time in ur "please wait loading data" u do /house goto and go to ur house. Server will take u out of ur house but u will still be able to hear ur house music outside house, and do things like /house settings.

![Please wait house](https://user-images.githubusercontent.com/22722462/83408913-b4085400-a413-11ea-83ed-c59806efdea6.png)

**Comment by RussellLVP** [comment]
This was fixed as part of LVP 47, thanks for your report!
