### ISSUE TITLE
/gang members

### ISSUE THREAD

**Issue by XilentLVP** [LVPlayground/playground#656]
I'm thinking about a new look for /gang members, because the actual one (https://imgur.com/a/rGEuXNC)  is a little bugged something like this:
https://imgur.com/a/39INY89

e.g.:
Nickname          Rank             Status
[CP]Holsje         Leader          Online
[CP]Humza       Manager       Offline
Xilent                Member       Online

**Comment by RussellLVP** [comment]
That's a great idea. Thank you for the suggestion!

**Comment by XilentLVP** [comment]
Also you can add ‘Last seen’ feature if you think it would be cool.

**Comment by RussellLVP** [comment]
Your wish... :) 

![dialog](https://user-images.githubusercontent.com/6798476/83440285-969bb000-a43c-11ea-9a58-e45f88401305.png)
