### ISSUE TITLE
Players can't register on the website

### ISSUE THREAD

**Issue by Holsje** [LVPlayground/playground#66]
When you try to register on the website it says "Your account could not be stored on the server, please try again later."

http://puu.sh/m87mG/445c570872.png

**Comment by ghost** [comment]
This is now resolved. Registered and activated my account with no issues:

Verify your Las Venturas Playground account
Your account has been activated, congratulations. You are now able to access the gameserver, register on the forums or login on the website. Please mind that it might take a while before your user account appears on our website, as the sync daemon has to pick it up. This usually won't take longer than five minutes however.
