### ISSUE TITLE
/mute

### ISSUE THREAD

**Issue by XilentLVP** [LVPlayground/playground#661]
When a player is muted it shows the message _***You have been muted by Xilent (Id:1) for 3 minutes._
But when the player is unmuted it shows no message. Let's implement a message when player is unmuted _***You're now unmuted._ or _***You're now unmuted.Please behave nice and read our /rules!_ and give an _*Admin notice: Xilent(Id:1) is now unmuted._
It shows an admin notice when an administrator unmute manually a player using /unmute but not when the mute time ends.

**Comment by Specifer** [comment]
Cool thought!

**Comment by SophiaLVP** [comment]
Yep!
