### ISSUE TITLE
/help - Contacting us text

### ISSUE THREAD

**Issue by XilentLVP** [LVPlayground/playground#662]
It's a minor thing. Let's update the text from /help ->  Contacting Us and add our discord server.
![WF1gm3f - Imgur](https://user-images.githubusercontent.com/15145881/83525307-77a92680-a4ed-11ea-8217-6e970653805d.png)

Discord: discord.sa-mp.nl

**Comment by OttoRocket-LVP** [comment]
Fixed by @Specifer in #664
