### ISSUE TITLE
Improve /help

### ISSUE THREAD

**Issue by XilentLVP** [LVPlayground/playground#663]
Let's add a new feature to /help named 'Account' with informations about account informations, how to change nickname, password,etc using our new command /account.

Edit: Add '/account' to '/commands(/cmds)' -> Main.

**Comment by OttoRocket-LVP** [comment]
Done by @Specifer and @XilentLVP in 2da50ee7e3cb8f13ed428ed28251e6f2b1250275 and b8736de2e9976fa70904d09210bd1bcdf16d8a71
