### ISSUE TITLE
/help - Banking

### ISSUE THREAD

**Issue by XilentLVP** [LVPlayground/playground#667]
In /help -> Banking we have information about bank '/account' which was removed. I see no point in keeping this text.
![dSApJRN - Imgur](https://user-images.githubusercontent.com/15145881/83548479-82bf7f00-a50c-11ea-9c71-a65973c2fac6.png)

**Comment by OttoRocket-LVP** [comment]
Fixed by @XilentLVP in b8736de2e9976fa70904d09210bd1bcdf16d8a71
