### ISSUE TITLE
/settings newsmsg off

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#67]
I'm not entirely sure if [/settings newsmsg off] does anything, and what exactly it classifies as "News". I've got this set to off (double checked that it is Off) and I still see "news-like" messages appearing. They include: property investments, minigame signups, people using /kill, etc. 

"NewsController->show(message);" seems to be the parameter controlling this.

I'm wondering if changes could be made so that such messages do not appear for users who have toggled the option off.

![untitled](https://cloud.githubusercontent.com/assets/15123289/12070380/c348661a-b068-11e5-9d92-c52b2acda7fa.png)

**Comment by BeanerLVP** [comment]
News messages are the announcements made by Gunther or administrators, such as /show beg, /show rules, etc.

**Comment by ghost** [comment]
I've just tested this../settings newsmsg off, waited for a bit and one of Gunther's /show messages appeared as normal. Whether that's because I'm logged in as a crew member, I'm not sure...

**Comment by BeanerLVP** [comment]
The command used to work. If I recall correctly, the messages were handled by Nuwani, and not the gamemode.

**Comment by xhoogland** [comment]
Afaik the newsmsg options are indeed the messages shown on the place Granny shows.

**Comment by jadegraaf** [comment]
I checked the source and /settings newsmsg on/off doesn't turn anything on or off. It changes g_ShowMessages[playerid][0] to true, which is in turn nowhere used. 

g_ShowMessages[playerid][1] on the other hand is used to filter /showmessage's and various minigame signup messages for the player and is changed through /settings show message on/off.

**Comment by xhoogland** [comment]
Started working after this after my comment, indeed the g_ShowMessages[playerid][0] had something to do with this. This was noted as todo in the newscontroller, but fixing that now in a better way. :)

**Comment by xhoogland** [comment]
Fixed with latest commits!
