### ISSUE TITLE
/show dm

### ISSUE THREAD

**Issue by XilentLVP** [LVPlayground/playground#671]
Since we have the new feature /deathmatch zones, not everyone knows about it I'm thinking about a new show command /show dm(deathmatch) to announce players the can fight in our deatchmatch zones. 
**_Love fighting? Train your skills and explore our deathmatch arenas using /deathmatch!_**

**Comment by RussellLVP** [comment]
Sure, sounds good :) Note that these messages exist in a JSON file in data/, they're super easy to add.
