### ISSUE TITLE
Implement a new gang system

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#68]
We need to completely overhaul the gang functionalities available on Las Venturas Playground. I have written a proposal on the following page - please feel free to leave feedback!\

https://github.com/LVPlayground/playground/wiki/Gangs

**Comment by GodeyLVP** [comment]
I think it would be better like
[MyGang]Godey (Shows which gang you are)
It's better than changing name and joining.

**Comment by ghost** [comment]
Can u do it  /gang change name [New name] ??

**Comment by RussellLVP** [comment]
The new gangs feature has been implemented.
