### ISSUE TITLE
(Certain) commands fail on ID 0

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#69]
/watch, /mute, /slap, /(s)tp...just a few commands I've tried, and they do not work if the player has ID 0. Interestingly enough, /locate 0 _did_ work.

I see two possible fixes:
- reserve ID 0, and make ID's 1 and upwards usable.
- fix the implementation of existing commands to work with 0

"The player with the given id is not connected to the server"

![untitled](https://cloud.githubusercontent.com/assets/15123289/12075982/18e6fd90-b18e-11e5-8bce-c37c8b9e9a7a.png)

It's worth noting that ID was indeed ingame at this time.

**Comment by jadegraaf** [comment]
Was there actually a player connected? ID 0 is usually occupied by a NPC, which could cause the error. In that case we need to clarify that fault condition.

**Comment by ghost** [comment]
@oostcoast - there was a player connected, yes. 

[19:55] <%Nowani> [0] **\* dog_meat joined the game.
[19:56] <%Nuwini> [0] **\* dog_meat has logged in.

**Comment by RussellLVP** [comment]
This puzzles me. It means that PlayerManager::findPlayerByIdOrPartialName() doesn't believe that the player with Id 0 is connected to the server, which would only occur if Player(0)::isConnected() returns `false`, which should never ever be the case if they're connected (even for NPCs).

I added a bunch of tests in https://github.com/LVPlayground/playground/commit/f2570493be9aebe5c4807d8a3872f198e1b974a3, but these all indicate that stuff is working as expected :/

**Comment by ghost** [comment]
I just did some additional testing:

 **\* Granny (Id:9) has been teleported to Eric_Soviet (Id:0), in world 0.

Teleported to ID 0 with no issues. I was also able to use other commands, such as /watch, again, with no issues.

I definitely was able to re-produce this a few days ago, as was [sLK]Slide when trying to teleport to ID 0.

A new build is live, everything looks fine right now. I'm happy to close this issue out for the time being, and of course re-open it if I spot it again. Unless anyone else would like to comment?

**Comment by ghost** [comment]
Been testing this quite a bit over the past week, no issues. Closing this as such.
