### ISSUE TITLE
A minor change in the /show irc message

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#699]
Instead of requiring users to visit https://sa-.mp.nl, click "Contact" and "Web IRC", I think it'd be better to simply change the message to something like "Join us on IRC: https://sa-mp.nl/chat".

I don't mean to nitpick; it's just something minor I noticed when I spent some time in-game earlier. Feel free to close this issue if any of you feel this change is pointless.

**Comment by RussellLVP** [comment]
Yup, agreed :) Thanks!
