### ISSUE TITLE
Lame kills

### ISSUE THREAD

**Issue by XilentLVP** [LVPlayground/playground#704]
Since we removed lame kills, do we still need this message?

_***Xilent has committed a driveby on Shem! Xilent has 'x' lame kills.**_

Thanks to Geroge for notifing about this.

**Comment by EPIC-striker** [comment]
If I understood correctly, only the lame part should be removed. 
The OnPlayerDeath message still has to display that  **player a** has committed a driveby on **player b**.

**Comment by OttoRocket-LVP** [comment]
The reason I hadn't removed it as it's still considered lame right?

It's a lame kill, you just don't get to punsih for it.
