### ISSUE TITLE
Improvements Part 2

### ISSUE THREAD

**Issue by SophiaLVP** [LVPlayground/playground#712]
1. Admins get notice of password change with a password. I think this should be changed:
From
>Sophia(id:02) has changed their password to "**********"

To
>Sophia(id:02) has changed their password

2. After purchasing a hint of barrel or spray tag, the cash in tab menu shows "1" even you still have a lot in your hand. Also due to it, player is unable to buy property with that cash in hand.

3. https://ibb.co/4dBbpT8 I don't know how this donation works but I do like to have some more information about it and adding a location marker will be nice.

**Comment by RussellLVP** [comment]
Hi Sophia,

Thank you for the report!

1. This is a joke, the shown password is automatically generated, and most certainly not what the player entered 😄 Please don't share this knowledge too widely.

1. This has been fixed already, thank you for the report!

1. We used to have a _tax agency_ on the server which took money from you. This is an evolution thereof: the money is very much disappearing into nowhere, just _to_ a randomly selected business that exist in the world of San Andreas.

Thanks,
Russell
