### ISSUE TITLE
/haystack problem

### ISSUE THREAD

**Issue by FreakinsPL** [LVPlayground/playground#716]
Problem: 
1)During /haystack minigame, signup players can use weapons in that minigame

2)Players who didn't signup for /haystack can teleport to the players who are in /haystack minigame.

/haystack is a some type of speed run minigame so this make no sense that players can use weapons and /tp.

Note: I tried this multiple times but same result

**Comment by OttoRocket-LVP** [comment]
Maybe we should disallow players to teleport to others if they're not in the same world?

I think we already disallow teleporting while in a minigame right?

**Comment by Specifer** [comment]
cool!

**Comment by FreakinsPL** [comment]
Only in /haystack we can teleport from main world to minigame world.

While in other minigames this is not possible to teleport to a players who are in a minigame
