### ISSUE TITLE
Ideas with SetPlayerGravity, vehicle keys, minigames

### ISSUE THREAD

**Issue by JTrolin** [LVPlayground/playground#717]
# SetPlayerGravity
We should implement a "**SetPlayerGravity**" pawn function, which would allow us to do some fun stuff.

## Vehicle key

We could have a key which inverts the gravity `SetPlayerGravity(playerid, -0.008)` and flips their vehicle to allow them to drive upside down.

This does not work that great with current jump method (seems to increase coordinates), gravity should be taken into account (so that you jump against the gravity).

## Minigames

The key above can be expanded to create minigames where you need to flip your gravity to drive on weird maps with gaps either above or below you. Possible limiting timers might need to be implemented for this.

Take into account vehicles being upside down might catch fire and try to explode on you. :)

**Comment by RussellLVP** [comment]
This has all been implemented :)
