### ISSUE TITLE
Descramble the word reaction tests

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#718]
It would be cool to have a new kind of reaction test where you have to descramble the word, i.e. an anagram solver.

> First player to unscramble "LCHDIIAL" wins $5,000!

> CHILLIAD

We'd need to seed this with a reasonably large dictionary (~1000 words at least) to avoid too frequent repetition, and would want to avoid words that are either too short or too long. Ideas?

**Comment by BeanerLVP** [comment]
Great idea! We should compile a list of LVP & San Andreas related names/words and fill the rest of the dictionary with random English words that are 8 to 12 characters long, or something along those lines.

**Comment by XilentLVP** [comment]
It’s a great idea I really like it. +1

**Comment by RussellLVP** [comment]
The functionality has now been implemented, we just need the word list... All help is most welcome :)
