### ISSUE TITLE
Marker/checkpoint located at Blackfield & Eastbeach

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#72]
It's just come to my attention that there's a marker/checkpoint located at Blackfield, LV and East Beach, LS, which don't seem to do anything. I've tried rejoining to ensure I wasn't bugged, and approaching the marker on footer as well as in a vehicle. 

![untitled](https://cloud.githubusercontent.com/assets/15123289/12152431/8dc553ca-b4ac-11e5-95d3-87c6bf123fa5.png)

**Comment by BeanerLVP** [comment]
There used to be markers such as this one in various places (don't know if they're all still present). They were meant to start races. I'd suggest approaching that particular one with a Sandking, Sanchez, or Monster Truck. If nothing happens, it probably is useless.

**Comment by xhoogland** [comment]
Case of WontFix, since it is afaik kinda hardcoded in GTA:SA and also apparently impossible to remove in SA-MP.
