### ISSUE TITLE
Vehicles -

### ISSUE THREAD

**Issue by OttoRocket-LVP** [LVPlayground/playground#721]
- House vehicles don't apear to show. (Maybe something to do with too many vehicles in the area?)
- Vehicle decorations gone broken.

**Comment by OttoRocket-LVP** [comment]
/v enter doesn't work as expected anymore.

(Sometimes says there's no vehicle close, other times teleports to a vehicle further away)

**Comment by Specifer** [comment]
Any idea of what could cause it?
