### ISSUE TITLE
No weapons in player's stash after given a handofgod

### ISSUE THREAD

**Issue by SophiaLVP** [LVPlayground/playground#724]
When a player is thrown up by an admin, his/her weapons disappear. Tested it multiple times with the help of fellow admins. All thanks to Finisha, Darkfire, Humza and AzKiller.

**Comment by XilentLVP** [comment]
I don’t understand why weapons are needed after /p handofgod, the player is supposed to die. :)

**Comment by EPIC-striker** [comment]
If anything,  you can fix the player which gives the weapons back. 
There's still a valid point in Xilent's comment though.

**Comment by RussellLVP** [comment]
Yeah, I don't think that this is worth fixing. We'll re-think the command in its entirety when it moves to JavaScript anyway.
