### ISSUE TITLE
Barrels Issue

### ISSUE THREAD

**Issue by FreakinsPL** [LVPlayground/playground#733]
Today I was doing barrel hunting with striker and I notice something that barrels are keep disappearing after it was shot by another player.

In simple words, whenever striker shot the barrel, the barrel get disappear for me and vice versa, 
So he need to use /fix everytime.

**Comment by XilentLVP** [comment]
If you shoot once just one shot, the barrels won’t disappear.

**Comment by RussellLVP** [comment]
Thanks for the issue, @FreakinsPL! Unfortunately this is a SA-MP bug that we can't do anything about: even though _your_ barrel only exists for _you_, SA-MP enables other players to blow it up anyway.

As @XilentLVP mentions, there's a few known work-arounds, so let's stick to those. Maybe we should document them somewhere?
