### ISSUE TITLE
/deathmatch

### ISSUE THREAD

**Issue by XilentLVP** [LVPlayground/playground#735]
I'm thinking about a new look for /deathmatch instead of showing the text '**_Usage: /deathmatch [zone]_**' to look like /minigames(for e.g.) with much more information about deathmatch zones.

e.g.
**Deathmatch zones*
**_/deathmatch 1  - Running Weapons (RW) - skin hit
/deathmatch 2 - Walking Weapons (WW) - skin hit
/deathmatch 3 - Running Weapons (RW) - lag shot_**

**Comment by OttoRocket-LVP** [comment]
Hey Xilent, good thinking!

It's one of the things I still want to add as in #686.

**Comment by EPIC-striker** [comment]
> I'm thinking about a new look for /deathmatch instead of showing the text '**_Usage: /deathmatch [zone]_**' to look like /minigames(e.g.) with much more information about deathmatch zones.
> 
> e.g.
> *_Deathmatch zones_
> **_/deathmatch 1 - Running Weapons (RW) - skin hit /deathmatch 2 - Walking Weapons (WW) - skin hit /deathmatch 3 - Running Weapons (RW) - lag shot_**

Yes, it will be better to add the same concept that was done for /fight invite, prompting you with a dialog menu. 
In the menu, we can then add the type of deathmatch (RW or WW) and (SKIN SHOT or LAG SHOT). 
Followed by the weapons they want to use.

**Comment by OttoRocket-LVP** [comment]
https://puu.sh/FZ7il/e336d00e1e.png

^That's what I've added.

(Removed `lag shot` and `teams` frm the names as we display those with `Yes`/`No`

**Comment by XilentLVP** [comment]
It looks awesome! Good job @OttoRocket-LVP

**Comment by EPIC-striker** [comment]
> https://puu.sh/FZ7il/e336d00e1e.png
> 
> ^That's what I've added.
> 
> (Removed `lag shot` and `teams` frm the names as we display those with `Yes`/`No`

It looks amazing. 
If they can be organized it would be even better. Right now you have RW & WW both mixed in the menu.
