### ISSUE TITLE
Adjust /inf to come with infinite nos

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#74]
If a player spawns an Infernus with /inf, it will come with 10x NOS as standard. I think it would be a neat little addition if it came with infinite nos instead (e.g. what would normally be achieved with "/nos inf").

**Comment by xhoogland** [comment]
Putting this on hold since there appears to be sort of a timing issue.

if(putplayerinvehicle)
    attach_inf_nos

Gives an error of that I am not driving a vehicle. :x

**Comment by mblokker** [comment]
Maybe you're better off using:

```
@list(OnPlayerStateChange)
public onPlayerStateChange(playerId, newState, oldState) {
    if (newState == PLAYER_STATE_DRIVER && GetPlayerVehicleID(playerId) == sprayTagPlayerVehicle[playerId])
        attach_inf_nos
};
```

Added to the end of SprayTags.pwn (if possible).

**Comment by xhoogland** [comment]
Fixed per commit https://github.com/LVPlayground/playground/commit/e6eae4bd724b3aa05cf82e722ca941082b704fcc!
