### ISSUE TITLE
Deathmatch score not clearing.

### ISSUE THREAD

**Issue by OttoRocket-LVP** [LVPlayground/playground#740]
When there's no players left in the DM the score is supposed to get cleared. This is not the case.
Also, sometimes teams seem to be made uneven (When it's 4v3 a player joins it becomes 5v3)

It appears as if the team a player is on is not always cleared.

**Comment by Specifer** [comment]
Do you probably have solution for that Holsje?

**Comment by OttoRocket-LVP** [comment]
I'm not sure what is causing it.

It appears there's a situation where it doesn't delete the player from the `playerTeams_` map. Resulting into a "ghost" player left in the game.

**Comment by OttoRocket-LVP** [comment]
Problem is most likely fixed.
