### ISSUE TITLE
Improve /credits or /about 

### ISSUE THREAD

**Issue by Specifer** [LVPlayground/playground#746]
We need to make /credits more vivid and should look better than the last one.

**Comment by EPIC-striker** [comment]
Indeed it needs improvement and you can probably use the same concept that was used for /guide, taking the color scheme into account.

You can add something like: The Las Venturas Playground community would like to thank these players for their contribution etcetera. 

Note: there's no /about command and it may not be needed. 
![sa-mp-001](https://user-images.githubusercontent.com/35706739/85235020-b5f48000-b3df-11ea-868b-fa9493cd02eb.png)

**Comment by Specifer** [comment]
But I can't add version string.

**Comment by EPIC-striker** [comment]
Do what you can mate :)

**Comment by Specifer** [comment]
@XilentLVP had done this in ae71e28224c7bcda1ef04ac7c6035182a170afdf.
