### ISSUE TITLE
Time randomly changes

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#75]
I've seen this happen on a number of occasions, typically everyday I've been ingame. Sometimes I'll be  driving along as normal, and the time will change from, say, 20:00 to 09:00 (for example). This happens even when /set time [hour] is used, which I would have thought would be permanent, at least until the player dies, but preferably their entire session. 

No admins are changing it, it just sort-of...happens by itself.

**Comment by RussellLVP** [comment]
When using `/set time [hour]`, you change time for **everybody**. It doesn't override the progression of time, however— the normal timers will continue to run. When said update comes, it will continue where it was before the override command was issued.

What I think would be nicer is if the progression of time could use the current hour as the base and progress based on that. Our time infrastructure is a bit messy at the moment, let me use this as an opportunity to clean that up a bit.
