### ISSUE TITLE
Can't use /tp /cardive /tow (After buying barrel hint)

### ISSUE THREAD

**Issue by FreakinsPL** [LVPlayground/playground#753]
After buying the hint of barrel, players can't use /tp /tow /cardive
(Showing not enough cash but actually player have sufficient cash)

Note: Tried couple of times but same result

video: https://youtu.be/HAN0tfMJkCU

**Comment by FreakinsPL** [comment]
I found the temporary fix for this problem
there are two ways you can do it:-
1) Relog
2) Just do /bank all then /withdraw [any amount] 

any of these method can fix this problem
:)

**Comment by RussellLVP** [comment]
Thank you for the report @FreakinsPL! I don't think we've ever spoken in-game, I'm sorry that I keep missing you!

I landed a tentative fix here: 81ef99e7. Let's keep revising because I'm not entirely sure that nips it in the butt. It's live on Staging.

**Comment by RussellLVP** [comment]
This seems to work now, and I haven't seen negative scores anymore :) Closing.
