### ISSUE TITLE
money

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#76]
Hey,
        Developer
                        Can bag of cash starting money Value Can be High  ?? 
# define     MAX_MONEY_BAG_CASH      50000000
# define     MIN_MONEY_BAG_CASH      1000
# define     MONEY_BAG_PICKUP_TYPE   2
# define     MONEY_BAG_PICKUP_MODEL  1550
# define     RANDOM_MONEY_LOCATIONS  136

I it's Self have Not done it ! can u tell me can it done to  
# define     MAX_MONEY_BAG_CASH      50000000
# define     MIN_MONEY_BAG_CASH      100000
# define     MONEY_BAG_PICKUP_TYPE   2
# define     MONEY_BAG_PICKUP_MODEL  1550
# define     RANDOM_MONEY_LOCATIONS  136

**Comment by jadegraaf** [comment]
What is the benefit of increasing the minimum? Won't that mean that the feature will be used less?

**Comment by ghost** [comment]
Dear oostcoast ,
                          No one Find Bag of Cash with that '1000' Cash One Players need to Add it 
                          and no one dose it so i want to make it , Thanks For Reading SIR!

**Comment by GodeyLVP** [comment]
I think you are right, 
I've seen this happening
"Someone finds the moneybag and puts 10million before collecting."
So better is that we start MoneyBag with a Million.

**Comment by ghost** [comment]
There are more than enough ways to **make** money but too little ways to **spend** it. I don't see a good reason to increase the minimum. 

Ultimately we are going to loose players by making it easier and faster to earn cash, as said players fill up a bank account, get bored and don't come back.
