### ISSUE TITLE
IRC Bug

### ISSUE THREAD

**Issue by FreakinsPL** [LVPlayground/playground#760]
![Screenshot_20200623-170121](https://user-images.githubusercontent.com/65241998/85398873-765e9d00-b573-11ea-8ccc-6131c9df979f.png)
 Pm from ingame to irc
Showing the name of "NaN" instead of the player who actually sent the pm from ingame to irc.

**Comment by Specifer** [comment]
Edit: It works no errors !!

**Comment by Specifer** [comment]
This has been fixed in 69ace6f by Russell already! Thank you for your report mate :)
