### ISSUE TITLE
/race issue

### ISSUE THREAD

**Issue by FreakinsPL** [LVPlayground/playground#764]
Races which have issues
1) Quad Race
2) Dirty Race
3) Los Santos Blown Bikes

Issue: There is no way to leave these races other than /q 
(Rest races are working fine and I was able to leave them by just getting out of my vehicle)

Note: I tested all the races and only these 3 are faulty.

**Comment by Specifer** [comment]
Only these three races have this leave vehicle exception since you would make some mistakes like getting out of vehicle.

**Comment by FreakinsPL** [comment]
So how to leave these races coz /leave cmd is not working either

**Comment by Specifer** [comment]
That's a great question.

**Comment by RussellLVP** [comment]
We've got plans to migrate races to the new Games API, so this will automatically be fixed when that happens. Let's close this for now :)

**Comment by FreakinsPL** [comment]
Cool <3
