### ISSUE TITLE
/house goto improvements

### ISSUE THREAD

**Issue by SophiaLVP** [LVPlayground/playground#768]
Recently I have found a way in which a player can teleport in to one of their houses. [https://www.youtube.com/watch?v=_33TNMF-rFQ](url)
The video above me contains Fallen abusing a /house goto command to evade perfectly even after taking some damage. I tested it with Reni and it happens when players have his/her house teleportation popped up already. So I am suggesting a countdown mechanism as similar to /taxi which should provide enough time to players that are chasing the command abuser if house is selected for teleportation. Moreover, I also suggest house teleportation menu disappearance if player is damaged by someone in case of having that opened already.

Regards,
Sophia Naz

**Comment by RussellLVP** [comment]
I actually fixed this a couple of days ago already, so it'll go live with the next update.

We do not have the ability to close dialogs, sadly.

Thank you for the suggestion, let me close this.
