### ISSUE TITLE
Vehicles catch fire (/v save --> /fixvehicles)

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#77]
Sometimes when using /v save, followed by /fixvehicles, the vehicle will respawn as expected, however, it will be on fire and then just explode. I've tested this in numerous locations, with a variety of vehicles (trucks, cars, bikes) -- same problem. It has been happening for quite some time now (at least 4-6 months) though I forgot to report it.

**Comment by mblokker** [comment]
I do not see the need for /fixvehicles in this case, isn't /v respawn sufficient? /fixvehicles is meant for rare moments where hackers spawn 10+ vehicles per second, or change the order of the map. Overusing it gives bad player experience.

**Comment by ghost** [comment]
@mblokker - I understand what you're saying, however even if I wouldn't have used /fixvehicles, the saved vehicle would probably have caught fire on the next gamemode init anyway. I don't think the issue is with the /fixvehicles command.

**Comment by mblokker** [comment]
I have never seen this before, after using /v create. I remember years back a vehicle would respawn burning, and explode, after being exploded by a carbomb. It might have something to do with SAMP logic in resetting vehicle health at respawn?

**Comment by ghost** [comment]
I've created a video in-case it helps:

http://sendvid.com/5fg3vy3e

**Comment by RussellLVP** [comment]
As a meta comment, could you please consider uploading videos to YouTube rather than sites that spawn popups with crap? :)

**Comment by ghost** [comment]
I'm no longer able to re-produce this issue. 

Given that there's been 2 releases since I opened this case, perhaps it's fixed. 

Closing this, I'll re-open it if I see this problem again.
