### ISSUE TITLE
Show correct answer after reaction test time expires

### ISSUE THREAD

**Issue by SophiaLVP** [LVPlayground/playground#770]
As we have a new type of reaction test of letters descrambling, I do like a small addition in reaction tests, not only in that particular type but for all types.

I suggest that a message should show which shows the right answer of the reaction test with the following when time expires:

> "Since nobody was able to solve the reaction test, the correct answer was ________" 

         _Applies only to maths test and descramble tests_

There are a lot of words which are kind of impossible to rearrange it into the word at that time; We are humans, we skip things and it will be a great addition to see the correct word when it's over. Sometimes it's curious enough to know it. If it's a typing speed test and memorizing number, then the message should be like:

>  "Nobody was able to solve the reaction test"

Thank you
Regards,
Sophia Naz

**Comment by RussellLVP** [comment]
I don't think we should do this for unscramble tests, because there's a limited word list. For calculations I think this is reasonable.
