### ISSUE TITLE
Freeze command ( Issues + Suggestions)

### ISSUE THREAD

**Issue by FreakinsPL** [LVPlayground/playground#777]
Firstly I would like to thanks @EPIC-striker for helping me to test the freeze cmd :)

Here some issues with freeze cmd
 
1)Players can easily evade the freeze by using /dive or /cardive .

2)Players can easily evade the freeze by using /taxi or /tow

Some suggestions 
1)Disable all cmd after getting Freeze by an admin.
2)If players try to use cmd, a message should be shown like:-
"You are currently freeze , you can't use commands"
3)Make Freeze cmd easy to type 
Remove /p [id] (un)freeze
Add  /(un)freeze [id]

Cheers!

**Comment by Specifer** [comment]
Cool idea guys!

**Comment by EPIC-striker** [comment]
We appreciate your help too, Freakins!

While I understand where you're going with point # 3, I would like to add that the **simple** and **structured** things are the better. 
It's with this in mind that I've made the Las Venturas Playground Commands documentation many years ago. 

Having commands falling under these categories(/my /set /v /p), if possible, maintains things structured.  

If considerating the removal of a command from under a category, we should check first how that's going to impact those that have it at their disposal. And if it's necessary. Improvements are welcomed though.

**Comment by Specifer** [comment]
Since Jail, Ban and Mute doesn't come under /p. I assume it is perhaps right for /freeze to not come under /p too.

**Comment by BeanerLVP** [comment]
I think it's pointless to move freeze and unfreeze from /p. How often are the two commands used to warrant this change? Crew members have a lot of commands at their disposal, and several of them are used to certain commands, so let's not create any confusion.

**Comment by EPIC-striker** [comment]
Specifer, 

Those commands can very well go under /p, but that's not the point we are trying to make here. 
While we are open to improvements and changes, this is not necessary for obvious reasons. 
Just an example, there's /engine id [on/off] while this can be under /v. 

By doing so, 1) it's organized, and 2) crew members have the idea of what commands they have at their disposal.

**Comment by Specifer** [comment]
ok mates, you make a meaningful point there. As you wish :D !

**Comment by RussellLVP** [comment]
The challenge here is that we can't easily observe whether a player is frozen or not: SA-MP doesn't give us the necessary tools to track whether a player is frozen, only to freeze them. Creating a comprehensive system is _really difficult_ because of our split codebase.

Since these comments are only being used by administrators actively investigating particular players, they're being looked at anyway. Trying to avoid capture by admins isn't going to help their case.
