### ISSUE TITLE
Bring /house settings cmd outside the house 

### ISSUE THREAD

**Issue by FreakinsPL** [LVPlayground/playground#782]
If a player try to do /kill and immediately do /house goto, he/she will able to use /house settings command outside his/her house.

Video:https://youtu.be/xZ5Pw1WBCKM

Possible Solution: Prevent players from using /house goto at the time of their death.

Cheers!

**Comment by OttoRocket-LVP** [comment]
Hey Freakins,

Is there any way players can abuse this?
If it's only somebody able to open a menu they kind of shouldn't then I don't think it's really worth the time to be fixed. (As there'll be no reason to use this bug)

**Comment by RussellLVP** [comment]
Yeah, I agree with Holsje that I don't think this is abusable. Let's close this for now.
