### ISSUE TITLE
Minor improvement in  /cruise start [id]

### ISSUE THREAD

**Issue by FreakinsPL** [LVPlayground/playground#783]
**Note:** Maximum ingame admin commands (/ban /kick /reconnect ) doesn't work on bots and if tried player got a this message "This player is a NPC or You can't ____ a NPC"

Improvement: Prevent bots from leading the cruise( /cruise start [id])
Add: "This player is a NPC" message, when this command is use on bots.

![sa-mp-346](https://user-images.githubusercontent.com/65241998/86874773-b0e14180-c0fe-11ea-9c9c-dc0f45ca921a.png)

Cheers!

**Comment by Specifer** [comment]
That's really awesome man!

**Comment by Specifer** [comment]
Closing Issue as it was fixed per #784.
