### ISSUE TITLE
Evade /p [id] cage command

### ISSUE THREAD

**Issue by FreakinsPL** [LVPlayground/playground#785]
Caged player can easily evade by using /kill command.

**Comment by BeanerLVP** [comment]
/p cage is mostly used for fun and can be combined with /slow for some weird passenger glitch in vehicles, or to troll hackers. It's probably best to let it reset on death in case an administrator leaves the server before disabling it or forgets to do so.

**Comment by FreakinsPL** [comment]
ok mate :)
