### ISSUE TITLE
(Minor Issue) Getting Error after coming from Liberty City

### ISSUE THREAD

**Issue by FreakinsPL** [LVPlayground/playground#786]
If a player goes to **Liberty City** he/she starts getting an error **"There are no flights departing right now! Try again later"** **Which is common** (when the player stands near the info symbol) but when the player return back to any city ( LV, LS or SF ), he/she again starts getting the same error **when the player stands near a property.**

Video:https://youtu.be/bW_1vOXRV7o

Cheers!

**Comment by RussellLVP** [comment]
This was fixed by Specifer: https://github.com/LVPlayground/playground/commit/5a8a3e6d56cfb3866c6da5a4d60b191d013d0798
