### ISSUE TITLE
Some suggestions to improve the overall gameplay experience

### ISSUE THREAD

**Issue by FinishaLVP** [LVPlayground/playground#792]
Hi ,

I want to make a few suggestions that were discussed in-game by three Administrators (Darkfire, Finisha and Sophia);

We tested the fighting cooldown timer, apparently it's only 25 seconds until the player is allowed (by the server) to use commands *if did not fire again* such as /dive, /world or entering Ammunation or houses.

(A) We noticed that the players inside a vehicle being shot can use the commands if they didn't receive direct hits to their skin although they are being attacked and their vehicles are about to explode and get killed but still get away, we suggest to include the vehicle damage in the fighting cooldown so it doesn't make things complicated and easier for everyone to comprehend as well as less reports and complaints.

(B) I also suggest to treat Administrators the same as regulars in the usage of regular (/tp), /tow /ctp and /taxi which means Administrators should also have a 3-minute cooldown teleportation /tp, /tow as well as /taxi. Because Administrators have the command /stp which can be used to force teleport on whoever and whenever needed. This is to prevent Administrators abuse unintentionally or intentionally during their fights or activities.

**Comment by Specifer** [comment]
Nice suggestion on point 2. But doesn't vehicular damage become annoying for most players who are in dm activity. Think of it someone keeps wantedly hitting their car so he can't teleport to their desired place .

**Comment by FinishaLVP** [comment]
> Nice suggestion on point 2. But doesn't vehicular damage become annoying for most players who are in dm activity. Think of it someone keeps wantedly hitting their car so he can't teleport to their desired place .

Vehicle damage as in being shot at by players using their weapons, and not collision damage

**Comment by FreakinsPL** [comment]
> > Nice suggestion on point 2. But doesn't vehicular damage become annoying for most players who are in dm activity. Think of it someone keeps wantedly hitting their car so he can't teleport to their desired place .
> 
> Vehicle damage as in being shot at by players using their weapons, and not collision damage

I don't think so it is possible

Am I right? @Specifer

**Comment by Specifer** [comment]
Maybe it is possible but idk.

**Comment by RussellLVP** [comment]
Both have been addressed, thank you for the suggestions!
