### ISSUE TITLE
/p [id] hide + /my hide on

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#80]
/p [id] hide on and /my hide on function as expected to a certain degree, however, on the radar/mini-map, a blip is still present. Can this function be modified so that the radar/mini-map blip is made invisible? 

![sa-mp-003](https://cloud.githubusercontent.com/assets/15123289/12299753/3d1c85ce-ba10-11e5-8843-bba7fb0c19cd.png)

https://wiki.sa-mp.com/wiki/SetPlayerMarkerForPlayer
http://forum.sa-mp.com/showthread.php?t=72853

**Comment by mblokker** [comment]
Thanks for providing the necessary sources Grannypants.
