### ISSUE TITLE
Gang joining and leaving announcements 

### ISSUE THREAD

**Issue by FinishaLVP** [LVPlayground/playground#821]
Hi ,

I noticed recently that leaving a gang gives the announcement "Joined" instead of "Left", it looked so confusing for everyone thinking they can join two gangs at the same time.

**Comment by SophiaLVP** [comment]
https://github.com/LVPlayground/playground/pull/820
I have created PR for the fix :)

**Comment by OttoRocket-LVP** [comment]
Has been fixed by Sophia 👍
