### ISSUE TITLE
news message 

### ISSUE THREAD

**Issue by FreakinsPL** [LVPlayground/playground#827]
![sa-mp-440](https://user-images.githubusercontent.com/65241998/93694353-50bc4200-fb28-11ea-9f8e-4c240d8f40da.png)
As you guys can see the news message is showing "**[nL] Freakins has signed up for deathmatch 4 (//deathmatch 4)** with an extra forward slash  in **(//deathmatch [id] ) instead of (/deathmatch [id] )**

**Comment by SophiaLVP** [comment]
I'll get it fixed

**Comment by OttoRocket-LVP** [comment]
Solved in ad4ad91
