### ISSUE TITLE
Refactoring saving vehicles permanently in favor of vehicle-stream-in

### ISSUE THREAD

**Issue by xhoogland** [LVPlayground/playground#83]
https://github.com/LVPlayground/playground/issues/1

In the above issue I kinda refactored that method to make it easier to drive with trailers again and not having sudden rotations. As we all know and cake also agreed this is not the best solution!

The SA-MP bug (cake: "then, the player moves the vehicle to a certain spot, and saves it (/v save). we store the vehicle's position and rotation, but the game still has the old figures in mind. the game only remembers the position the vehicle was created in") should be 'solved' at/in saving the vehicle so we do not need checks anymore in the vehicle-stream-in.

**Comment by ghost** [comment]
So, are we essentially looking for a replacement method for the (now temporarily(?) removed) OnVehicleStreamIn function?

**Comment by GodeyLVP** [comment]
> The SA-MP bug (cake: "then, the player moves the vehicle to a certain spot, and saves it (/v save). we store the vehicle's position and rotation, but the game still has the old figures in mind. the game only remembers the position the vehicle was created in") should be 'solved' at/in saving the vehicle so we do not need checks anymore in the vehicle-stream-in.

You said It saves the position and rotaion..
Does it even save the vehicle?
`new Mycar;
Mycar = GetPlayerVehicleID(playerid);`

**Comment by mblokker** [comment]
???

**Comment by RussellLVP** [comment]
The new vehicle streamer will probably fix this. Closing.
