### ISSUE TITLE
Pawn Editor download link no longer working

### ISSUE THREAD

**Issue by mblokker** [LVPlayground/playground#88]
https://forum.sa-mp.nl/showthread.php?tid=30442 is linking to http://downloads.sa-mp.nl/PawnEditor/, which no longer works. I suggest open-sourcing it here, or providing a download hosted at LVP again.

**Comment by SanderRutten** [comment]
Not sure why the download is gone, but I still have it.
[PawnEditor-1.0-rc2.zip](https://github.com/LVPlayground/playground/files/103840/PawnEditor-1.0-rc2.zip)

Now lets ask someone with knowledge what happened :+1:

**Comment by RussellLVP** [comment]
I published the latest version here:

https://github.com/LVPlayground/pawn-editor/releases/tag/1.0

Once someone figures out how to build it, we should open source the whole thing and make updating it happen.

**Comment by ghost** [comment]
thanks :+1: 

But i can't on it :-1: 

Telling some ERRO

**Comment by ghost** [comment]
Updated the aforementioned thread with a link to the Pawn Editor.
