### ISSUE TITLE
/watch quick skip to next player

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#9]
http://trac.sa-mp.nl/lvp/ticket/1590

@rstiekema:

> While /watch'ing the ability to skip to the next or previous player using the arrow buttons.

**Comment by xhoogland** [comment]
WIP, still need to do testing.

**Comment by xhoogland** [comment]
Needs some better (local) testing, doesn't seem to work in the main-server.

**Comment by xhoogland** [comment]
Found problem, changed code for it in upcoming commit! Still needs a small change and tweaks to make stuff a bit cooler and better usable. :)
