### ISSUE TITLE
Improve consistency between /settings newsmsg and /settings showmsg

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#90]
Under /settings, there are two options:
- /settings newsmsg
- /settings showmsg

**Output of /settings newsmsg:**
![newsmsg](https://cloud.githubusercontent.com/assets/15123289/12704784/8bba335e-c85a-11e5-9e81-71545c8c3c3e.png)

**Output of /settings showmsg:**
![showmsg](https://cloud.githubusercontent.com/assets/15123289/12704794/a557c416-c85a-11e5-8ead-47aab184b677.png)

**Output of /settings newsmsg on:**
![newsmsg_disable](https://cloud.githubusercontent.com/assets/15123289/12704806/f3335880-c85a-11e5-8766-25532858df0a.png)

**Output of /settings newsmsg off:**
![newsmsg_disable1](https://cloud.githubusercontent.com/assets/15123289/12704809/136ae974-c85b-11e5-87fb-3eb025608fc9.png)

**Output of /settings showmsg on:**
![showmsg_on](https://cloud.githubusercontent.com/assets/15123289/12704816/3a1fd5de-c85b-11e5-9ebb-259f5b8c9056.png)

**Output of /settings showmsg off:**
![showmsg_disable](https://cloud.githubusercontent.com/assets/15123289/12704817/55f10b98-c85b-11e5-8487-0e91a21bf77d.png)

The newsmsg is the more attractive of the two, given that it shows the user's current preference if no on/off argument is specified, and given that a different font colour is used to specify the enabled/disabled option. It'd be nice if we could merge the aesthetics of newsmsg into showmsg.

**Comment by xhoogland** [comment]
Done per https://github.com/LVPlayground/playground/commit/f94705c5a236cdfa1ff1d438dcb08035b98708d1 as referenced above. :)
