### ISSUE TITLE
Remove NetStats_PacketLossPercent

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#95]
The Packetloss counter implemented using NetStats_PacketLossPercent was removed from bottom right hand corner in https://github.com/LVPlayground/playground/commit/0f4325d84ae462b0c84f0f93676221dc215b0437

We still use this function elsewhere: https://github.com/LVPlayground/playground/search?utf8=%E2%9C%93&q=NetStats_PacketLossPercent

Given that we have not had success with it, backed by SA:MP's own statement: "This function has been found to be currently unreliable the output is not as expected when compared to the client. Therefore this function should not be used as a packet loss kicker." - should it be removed?

**Comment by mblokker** [comment]
Don't see the harm in removing it. We could increase the drawing distance while fixing this.
