### ISSUE TITLE
Improve minigame winning consistency

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#96]
There's currently a mish-mash of messages that are displayed when various minigames end. We should try and identify a style that we like, and stick to it for all minigames. In the screenshot below, I've identified two examples, but there are others, like in the Island DM:

SendClientMessageToAll(Color::Information, "\* The Soldiers have won the Island DM!");

![untitled](https://cloud.githubusercontent.com/assets/15123289/12823778/c6cf1834-cb65-11e5-83c7-2d35493f6888.png)

**Comment by xhoogland** [comment]
Then I even rather have those messages as NewsMessage where you also see the sign-ups, so on the bottom of the screen.
