### ISSUE TITLE
login

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#98]
hii,

When i login and forgot password and i type Wrong pass 3 time then I need to play as guest 

so add a new cmd : /relog or /rejoin

so that we can able to login again new correct password :+1:

**Comment by mblokker** [comment]
Do you mean a password reset functionality, or just simply a reconnect command so you can have 3 fresh tries?

**Comment by ghost** [comment]
If players fail to enter the correct password within the 3 attempts, they will be assigned a random nickname, and they can play using that. I think the logic would be to simply quit and rejoin to try again, and that we will just end up further complicating the account/login process by adding new command.

**Comment by ghost** [comment]
I mean Both @mblokker , If Players Get a Lag and he  need a fix and no admins Online so he will do /relog but he can't do it while fighting ,[fight/duel/minigames etc]

**Comment by mblokker** [comment]
I don't get it, I thought the relog command was meant for players stuck in the password dialog screen? How can such a player be fighting?

From what we can conclude I think we don't have the need for such a command.
